In [11]:
#All libraries import here
import torch
import torch.nn as nn
import torch.optim as optim
import requests
import json
import pandas as pd
import datetime as dt
import time
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [12]:
# ============================================================
# BITCOIN DM TESTS
# STEP 1: LOAD AND ALIGN ERNN SI-SELF PREDICTIONS
# UPDATED TO USE THE 800-TRIAL PENALTY MODEL
# ============================================================

from pathlib import Path

import numpy as np
import pandas as pd


# ------------------------------------------------------------
# 1. Project path and levels
# ------------------------------------------------------------

PROJECT_DIR = Path(
    "/Users/miaomiaochen/Desktop/PhD program/Project 1"
)

LEVELS = np.array([
    0.025,
    0.050,
    0.250,
    0.500,
    0.750,
    0.950,
    0.975
])

LEVEL_CODES = [
    "0025",
    "0050",
    "0250",
    "0500",
    "0750",
    "0950",
    "0975"
]


# ------------------------------------------------------------
# 2. Saved prediction paths
# ------------------------------------------------------------

prediction_paths = {
    "Sorting": (
        PROJECT_DIR
        / "sorting_crossover_results"
        / "ernn_si_self"
        / "sorting_ernn_si_self_test_predictions.csv"
    ),

    "PAVA": (
        PROJECT_DIR
        / "pava_crossover_results"
        / "ernn_si_self"
        / "pava_ernn_si_self_test_predictions.csv"
    ),

    # Updated from the preliminary 200-trial penalty model
    # to the final 800-trial penalty model.
    "Penalty": (
        PROJECT_DIR
        / "penalty_crossover_results_800trials"
        / "ernn_si_self"
        / "penalty_ernn_si_self_test_predictions.csv"
    ),

    "Method 1b": (
        PROJECT_DIR
        / "method1b_joint_ernn_si_self_test_predictions.csv"
    ),

    "Method 3": (
        PROJECT_DIR
        / "method3_spacing_ernn_si_self_results"
        / "ernn_si_self"
        / "method3_spacing_ernn_si_self_test_predictions.csv"
    )
}


# ------------------------------------------------------------
# 3. Check that every required file exists
# ------------------------------------------------------------

missing_files = [
    str(path)
    for path in prediction_paths.values()
    if not path.exists()
]

if missing_files:
    raise FileNotFoundError(
        "The following prediction files are missing:\n"
        + "\n".join(missing_files)
    )

print("All five prediction files were found.")

print("\nPrediction sources:")
for method_name, path in prediction_paths.items():
    print(f"{method_name}: {path}")


# ------------------------------------------------------------
# 4. Load the original files
# ------------------------------------------------------------

sorting_raw = pd.read_csv(
    prediction_paths["Sorting"],
    parse_dates=["Date"]
)

pava_raw = pd.read_csv(
    prediction_paths["PAVA"],
    parse_dates=["Date"]
)

penalty_raw = pd.read_csv(
    prediction_paths["Penalty"]
)

method1b_raw = pd.read_csv(
    prediction_paths["Method 1b"],
    parse_dates=["Date"]
)

method3_raw = pd.read_csv(
    prediction_paths["Method 3"],
    parse_dates=["date"]
)


# ------------------------------------------------------------
# 5. Use the sorting dates as the reference test dates
# ------------------------------------------------------------

reference_dates = pd.DatetimeIndex(
    sorting_raw["Date"]
)

number_of_test_observations = len(
    reference_dates
)

if reference_dates.duplicated().any():
    raise ValueError(
        "Duplicated dates were found in the reference file."
    )


# ------------------------------------------------------------
# 6. Standardise actual returns and forecasts
# ------------------------------------------------------------

actual_returns = {
    "Sorting":
        sorting_raw["Actual"].to_numpy(),

    "PAVA":
        pava_raw["Actual"].to_numpy(),

    "Penalty":
        penalty_raw["actual"].to_numpy(),

    "Method 1b":
        method1b_raw["Actual"].to_numpy(),

    "Method 3":
        method3_raw["actual"].to_numpy()
}

forecast_matrices = {
    "Sorting": sorting_raw[
        [
            f"Sorted_{code}"
            for code in LEVEL_CODES
        ]
    ].to_numpy(),

    "PAVA": pava_raw[
        [
            f"PAVA_{code}"
            for code in LEVEL_CODES
        ]
    ].to_numpy(),

    "Penalty": penalty_raw[
        [
            f"q_{level:.3f}"
            for level in LEVELS
        ]
    ].to_numpy(),

    "Method 1b": method1b_raw[
        [
            f"E_{level:.3f}"
            for level in LEVELS
        ]
    ].to_numpy(),

    "Method 3": method3_raw[
        [
            f"e_{level:.3f}"
            for level in LEVELS
        ]
    ].to_numpy()
}


# ------------------------------------------------------------
# 7. Verify the dates in files that contain dates
# ------------------------------------------------------------

dated_files = {
    "PAVA":
        pd.DatetimeIndex(
            pava_raw["Date"]
        ),

    "Method 1b":
        pd.DatetimeIndex(
            method1b_raw["Date"]
        ),

    "Method 3":
        pd.DatetimeIndex(
            method3_raw["date"]
        )
}

for method_name, method_dates in dated_files.items():

    if not method_dates.equals(
        reference_dates
    ):
        raise ValueError(
            f"{method_name} dates do not match "
            "the reference test dates."
        )


# ------------------------------------------------------------
# 8. Verify lengths, shapes and actual returns
# ------------------------------------------------------------

reference_actual = actual_returns["Sorting"]

alignment_rows = []

for method_name in prediction_paths:

    method_actual = actual_returns[
        method_name
    ]

    method_forecasts = forecast_matrices[
        method_name
    ]

    correct_length = (
        len(method_actual)
        == number_of_test_observations
    )

    correct_shape = (
        method_forecasts.shape
        == (
            number_of_test_observations,
            len(LEVELS)
        )
    )

    actuals_match = (
        correct_length
        and np.allclose(
            method_actual,
            reference_actual,
            rtol=1e-7,
            atol=1e-9
        )
    )

    finite_actuals = np.isfinite(
        method_actual
    ).all()

    finite_forecasts = np.isfinite(
        method_forecasts
    ).all()

    alignment_rows.append({
        "Method": method_name,
        "Observations": len(method_actual),
        "Forecast_shape": str(
            method_forecasts.shape
        ),
        "Correct_length": correct_length,
        "Correct_shape": correct_shape,
        "Actuals_match": actuals_match,
        "Finite_actuals": finite_actuals,
        "Finite_forecasts": finite_forecasts
    })

alignment_summary = pd.DataFrame(
    alignment_rows
)

display(alignment_summary)


# ------------------------------------------------------------
# 9. Stop if any comparison is not aligned
# ------------------------------------------------------------

if not alignment_summary[
    "Correct_length"
].all():
    raise RuntimeError(
        "At least one method has an incorrect "
        "number of test observations."
    )

if not alignment_summary[
    "Correct_shape"
].all():
    raise RuntimeError(
        "At least one method does not have a "
        "(454, 7) forecast matrix."
    )

if not alignment_summary[
    "Actuals_match"
].all():
    raise RuntimeError(
        "The actual returns are not identical across "
        "all five methods. Do not run the DM test yet."
    )

if not alignment_summary[
    "Finite_actuals"
].all():
    raise RuntimeError(
        "At least one prediction file contains "
        "non-finite actual returns."
    )

if not alignment_summary[
    "Finite_forecasts"
].all():
    raise RuntimeError(
        "At least one prediction file contains "
        "non-finite forecast values."
    )


# ------------------------------------------------------------
# 10. Create a standardised forecast table
# ------------------------------------------------------------

standardised_forecasts = pd.DataFrame({
    "Date": reference_dates,
    "Actual": reference_actual
})

for method_name, forecasts in (
    forecast_matrices.items()
):

    safe_method_name = (
        method_name
        .lower()
        .replace(" ", "_")
    )

    for level_index, level in enumerate(
        LEVELS
    ):

        column_name = (
            f"{safe_method_name}_"
            f"{level:.3f}"
        )

        standardised_forecasts[
            column_name
        ] = forecasts[:, level_index]


# ------------------------------------------------------------
# 11. Save the aligned comparison dataset
# ------------------------------------------------------------

# Use a separate folder so the previous 200-trial
# penalty DM-test results are not overwritten.
DM_OUTPUT_DIR = (
    PROJECT_DIR
    / "dm_test_results_800trials"
    / "ernn_si_self"
)

DM_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

aligned_output_path = (
    DM_OUTPUT_DIR
    / "ernn_si_self_aligned_predictions.csv"
)

standardised_forecasts.to_csv(
    aligned_output_path,
    index=False
)


# ------------------------------------------------------------
# 12. Final confirmation
# ------------------------------------------------------------

print(
    "\nAlignment successfully completed."
)

print(
    "Penalty source:",
    prediction_paths["Penalty"]
)

print(
    "Test period:",
    reference_dates.min().date(),
    "to",
    reference_dates.max().date()
)

print(
    "Number of observations:",
    number_of_test_observations
)

print(
    "Number of levels:",
    len(LEVELS)
)

print(
    "Aligned data saved to:",
    aligned_output_path
)

display(
    standardised_forecasts.head()
)

All five prediction files were found.

Prediction sources:
Sorting: /Users/miaomiaochen/Desktop/PhD program/Project 1/sorting_crossover_results/ernn_si_self/sorting_ernn_si_self_test_predictions.csv
PAVA: /Users/miaomiaochen/Desktop/PhD program/Project 1/pava_crossover_results/ernn_si_self/pava_ernn_si_self_test_predictions.csv
Penalty: /Users/miaomiaochen/Desktop/PhD program/Project 1/penalty_crossover_results_800trials/ernn_si_self/penalty_ernn_si_self_test_predictions.csv
Method 1b: /Users/miaomiaochen/Desktop/PhD program/Project 1/method1b_joint_ernn_si_self_test_predictions.csv
Method 3: /Users/miaomiaochen/Desktop/PhD program/Project 1/method3_spacing_ernn_si_self_results/ernn_si_self/method3_spacing_ernn_si_self_test_predictions.csv

,Method,Observations,Forecast_shape,Correct_length,Correct_shape,Actuals_match,Finite_actuals,Finite_forecasts
0,Sorting,454,"(454, 7)",True,True,True,True,True
1,PAVA,454,"(454, 7)",True,True,True,True,True
2,Penalty,454,"(454, 7)",True,True,True,True,True
3,Method 1b,454,"(454, 7)",True,True,True,True,True
4,Method 3,454,"(454, 7)",True,True,True,True,True

Alignment successfully completed.
Penalty source: /Users/miaomiaochen/Desktop/PhD program/Project 1/penalty_crossover_results_800trials/ernn_si_self/penalty_ernn_si_self_test_predictions.csv
Test period: 2025-01-28 to 2026-04-26
Number of observations: 454
Number of levels: 7
Aligned data saved to: /Users/miaomiaochen/Desktop/PhD program/Project 1/dm_test_results_800trials/ernn_si_self/ernn_si_self_aligned_predictions.csv

,Date,Actual,sorting_0.025,sorting_0.050,sorting_0.250,sorting_0.500,sorting_0.750,sorting_0.950,sorting_0.975,pava_0.025,...,method_1b_0.750,method_1b_0.950,method_1b_0.975,method_3_0.025,method_3_0.050,method_3_0.250,method_3_0.500,method_3_0.750,method_3_0.950,method_3_0.975
0,2025-01-28,-0.007348,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-0.011363,-0.004656,-0.002242,-0.045185,-0.039505,-0.027747,-0.019753,-0.013229,-0.002338,0.003533
1,2025-01-29,0.023386,-0.016629,-0.012351,0.004526,0.004684,0.014084,0.026935,0.031262,-0.016629,...,0.005112,0.011550,0.013707,-0.021012,-0.015626,-0.003155,0.005261,0.008683,0.019570,0.025197
2,2025-01-30,0.009496,-0.008266,0.004347,0.017689,0.024264,0.034248,0.043000,0.046067,-0.008266,...,0.014319,0.020607,0.022403,-0.003193,0.001904,0.014931,0.023614,0.025218,0.036117,0.041798
3,2025-01-31,-0.022143,-0.016097,-0.008423,0.004168,0.006130,0.016249,0.031607,0.031992,-0.016097,...,0.012371,0.019676,0.022076,-0.018349,-0.013326,-0.000735,0.006323,0.010460,0.021344,0.026848
4,2025-02-01,-0.017669,-0.052173,-0.046104,-0.033027,-0.025515,-0.024055,-0.005879,-0.002005,-0.052173,...,-0.015149,-0.008505,-0.006442,-0.060020,-0.053846,-0.043476,-0.031648,-0.025883,-0.015038,-0.009466

In [16]:
# ============================================================
# BITCOIN DM TESTS
# STEP 2: ERNN SI-SELF AGD-NLL DM TESTS
# UPDATED TO USE THE 800-TRIAL PENALTY MODEL
# ============================================================

from scipy.stats import norm


# ------------------------------------------------------------
# 0. Confirm that Step 1 has been run
# ------------------------------------------------------------

required_objects = [
    "PROJECT_DIR",
    "LEVELS",
    "LEVEL_CODES",
    "reference_dates",
    "reference_actual",
    "forecast_matrices",
    "sorting_raw",
    "pava_raw",
    "DM_OUTPUT_DIR"
]

missing_objects = [
    name
    for name in required_objects
    if name not in globals()
]

if missing_objects:
    raise RuntimeError(
        "Run the updated Step 1 alignment cell first. "
        "The following objects are missing:\n"
        + ", ".join(missing_objects)
    )


# ------------------------------------------------------------
# 1. Paths to the saved per-level sigma estimates
# ------------------------------------------------------------

sigma_paths = {
    # Sorting and PAVA use the same unrestricted model.
    "Sorting/PAVA": (
        PROJECT_DIR
        / "pava_crossover_results"
        / "ernn_si_self"
        / "pava_ernn_si_self_test_metrics.csv"
    ),

    # Updated from the 200-trial penalty model
    # to the final 800-trial penalty model.
    "Penalty": (
        PROJECT_DIR
        / "penalty_crossover_results_800trials"
        / "ernn_si_self"
        / "penalty_ernn_si_self_test_metrics.csv"
    ),

    "Method 1b": (
        PROJECT_DIR
        / "method1b_joint_ernn_si_self_test_metrics.csv"
    ),

    "Method 3": (
        PROJECT_DIR
        / "method3_spacing_ernn_si_self_results"
        / "ernn_si_self"
        / "method3_spacing_ernn_si_self_test_metrics.csv"
    )
}


# ------------------------------------------------------------
# 2. Check that every sigma file exists
# ------------------------------------------------------------

missing_sigma_files = [
    str(path)
    for path in sigma_paths.values()
    if not path.exists()
]

if missing_sigma_files:
    raise FileNotFoundError(
        "Missing sigma files:\n"
        + "\n".join(missing_sigma_files)
    )

print("All required sigma files were found.")

print("\nSigma sources:")
for method_name, path in sigma_paths.items():
    print(f"{method_name}: {path}")


# ------------------------------------------------------------
# 3. Helper for loading sigma in the correct level order
# ------------------------------------------------------------

def load_ordered_sigma(
    path,
    level_column
):
    metrics = pd.read_csv(path)

    required_columns = [
        level_column,
        "sigma"
    ]

    missing_columns = [
        column
        for column in required_columns
        if column not in metrics.columns
    ]

    if missing_columns:
        raise ValueError(
            f"Missing columns in {path}:\n"
            + ", ".join(missing_columns)
        )

    ordered_metrics = (
        metrics
        .sort_values(level_column)
        .reset_index(drop=True)
    )

    saved_levels = ordered_metrics[
        level_column
    ].to_numpy(dtype=float)

    if not np.allclose(
        saved_levels,
        LEVELS,
        rtol=0,
        atol=1e-10
    ):
        raise ValueError(
            f"Incorrect levels in {path}.\n"
            f"Expected: {LEVELS}\n"
            f"Found: {saved_levels}"
        )

    sigma = ordered_metrics[
        "sigma"
    ].to_numpy(dtype=float)

    if len(sigma) != len(LEVELS):
        raise ValueError(
            f"Incorrect number of sigma values in {path}."
        )

    if not np.isfinite(sigma).all():
        raise ValueError(
            f"Non-finite sigma values in {path}."
        )

    if np.any(sigma <= 0):
        raise ValueError(
            f"Non-positive sigma values in {path}."
        )

    return sigma


# ------------------------------------------------------------
# 4. Verify that Sorting and PAVA use the same raw forecasts
# ------------------------------------------------------------

sorting_raw_forecasts = sorting_raw[
    [
        f"Raw_{code}"
        for code in LEVEL_CODES
    ]
].to_numpy()

pava_raw_forecasts = pava_raw[
    [
        f"Raw_{code}"
        for code in LEVEL_CODES
    ]
].to_numpy()

if not np.allclose(
    sorting_raw_forecasts,
    pava_raw_forecasts,
    rtol=1e-7,
    atol=1e-9
):
    raise RuntimeError(
        "Sorting and PAVA were not generated from "
        "the same unrestricted forecasts. Their sigma "
        "values cannot automatically be shared."
    )

print(
    "\nSorting and PAVA raw forecasts match. "
    "The common unrestricted-model sigma values will be used."
)


# ------------------------------------------------------------
# 5. Load the seven sigma estimates for each method
# ------------------------------------------------------------

postprocessing_sigma = load_ordered_sigma(
    sigma_paths["Sorting/PAVA"],
    level_column="level"
)

method_sigma = {
    "Sorting":
        postprocessing_sigma.copy(),

    "PAVA":
        postprocessing_sigma.copy(),

    "Penalty": load_ordered_sigma(
        sigma_paths["Penalty"],
        level_column="tau"
    ),

    "Method 1b": load_ordered_sigma(
        sigma_paths["Method 1b"],
        level_column="level"
    ),

    "Method 3": load_ordered_sigma(
        sigma_paths["Method 3"],
        level_column="tau"
    )
}

sigma_summary = pd.DataFrame({
    "Level": LEVELS,
    **{
        method_name: sigma
        for method_name, sigma
        in method_sigma.items()
    }
})

print("\nPer-level sigma values:")

display(
    sigma_summary.style.format(
        "{:.8f}"
    )
)


# ------------------------------------------------------------
# 6. Observation-level AGD NLL
# ------------------------------------------------------------

def ernn_agd_nll(
    actual,
    forecasts,
    sigma,
    levels
):
    """
    Calculate AGD NLL for every observation and level.

    Parameters
    ----------
    actual:
        Actual return vector with shape (T,).

    forecasts:
        Expectile forecast matrix with shape (T, K).

    sigma:
        Positive scale parameters with shape (K,).

    levels:
        Expectile levels with shape (K,).

    Returns
    -------
    level_nll:
        AGD NLL matrix with shape (T, K).

    average_nll:
        Per-date average AGD NLL with shape (T,),
        obtained by averaging across the seven levels.
    """

    actual = np.asarray(
        actual,
        dtype=float
    )

    forecasts = np.asarray(
        forecasts,
        dtype=float
    )

    sigma = np.asarray(
        sigma,
        dtype=float
    )

    levels = np.asarray(
        levels,
        dtype=float
    )

    expected_shape = (
        len(actual),
        len(levels)
    )

    if forecasts.shape != expected_shape:
        raise ValueError(
            "Incorrect forecast shape.\n"
            f"Expected: {expected_shape}\n"
            f"Found: {forecasts.shape}"
        )

    if sigma.shape != (
        len(levels),
    ):
        raise ValueError(
            "Incorrect sigma shape.\n"
            f"Expected: {(len(levels),)}\n"
            f"Found: {sigma.shape}"
        )

    if not np.isfinite(actual).all():
        raise ValueError(
            "Actual returns contain non-finite values."
        )

    if not np.isfinite(forecasts).all():
        raise ValueError(
            "Forecasts contain non-finite values."
        )

    if (
        not np.isfinite(sigma).all()
        or np.any(sigma <= 0)
    ):
        raise ValueError(
            "Sigma must contain positive finite values."
        )

    residuals = (
        actual[:, None]
        - forecasts
    )

    asymmetric_weights = np.abs(
        levels[None, :]
        - (residuals < 0).astype(float)
    )

    weighted_squared_residuals = (
        asymmetric_weights
        * residuals**2
    )

    agd_constant = (
        np.log(
            np.sqrt(
                np.pi / levels
            )
            + np.sqrt(
                np.pi / (1.0 - levels)
            )
        )
        - np.log(2.0)
    )

    level_nll = (
        np.log(sigma)[None, :]
        + agd_constant[None, :]
        + weighted_squared_residuals
        / sigma[None, :]**2
    )

    average_nll = level_nll.mean(
        axis=1
    )

    return (
        level_nll,
        average_nll
    )


# ------------------------------------------------------------
# 7. Calculate the NLL series for every method
# ------------------------------------------------------------

method_level_nll = {}
method_average_nll = {}

for method_name, forecasts in (
    forecast_matrices.items()
):

    (
        level_nll,
        average_nll
    ) = ernn_agd_nll(
        actual=reference_actual,
        forecasts=forecasts,
        sigma=method_sigma[method_name],
        levels=LEVELS
    )

    method_level_nll[
        method_name
    ] = level_nll

    method_average_nll[
        method_name
    ] = average_nll


# ------------------------------------------------------------
# 8. Average test NLL summary
# ------------------------------------------------------------

average_nll_summary = pd.DataFrame({
    "Method": list(
        method_average_nll.keys()
    ),

    "Average_AGD_NLL": [
        losses.mean()
        for losses
        in method_average_nll.values()
    ]
}).sort_values(
    "Average_AGD_NLL"
).reset_index(
    drop=True
)

print("\nAverage AGD NLL:")

display(
    average_nll_summary.style.format({
        "Average_AGD_NLL": "{:.8f}"
    })
)


# ------------------------------------------------------------
# 9. Newey-West long-run variance
# ------------------------------------------------------------

def newey_west_long_run_variance(
    series,
    max_lag
):
    series = np.asarray(
        series,
        dtype=float
    )

    if series.ndim != 1:
        raise ValueError(
            "The loss-difference series must be one-dimensional."
        )

    if not np.isfinite(series).all():
        raise ValueError(
            "The loss-difference series contains "
            "non-finite values."
        )

    if max_lag < 0:
        raise ValueError(
            "max_lag cannot be negative."
        )

    centred = (
        series
        - series.mean()
    )

    sample_size = len(centred)

    long_run_variance = (
        np.dot(
            centred,
            centred
        )
        / sample_size
    )

    for lag in range(
        1,
        max_lag + 1
    ):
        autocovariance = (
            np.dot(
                centred[lag:],
                centred[:-lag]
            )
            / sample_size
        )

        bartlett_weight = (
            1.0
            - lag / (max_lag + 1.0)
        )

        long_run_variance += (
            2.0
            * bartlett_weight
            * autocovariance
        )

    return long_run_variance


# ------------------------------------------------------------
# 10. DM test with HAC variance
# ------------------------------------------------------------

def dm_test_hac(
    loss_method_1,
    loss_method_2,
    max_lag=None
):
    """
    Perform a two-sided DM test using a Newey-West
    estimate of the long-run variance.

    d_t = loss_method_1,t - loss_method_2,t

    Negative difference:
        Method 1 has lower average NLL.

    Positive difference:
        Method 2 has lower average NLL.
    """

    loss_method_1 = np.asarray(
        loss_method_1,
        dtype=float
    )

    loss_method_2 = np.asarray(
        loss_method_2,
        dtype=float
    )

    if loss_method_1.ndim != 1:
        raise ValueError(
            "Method 1 loss must be one-dimensional."
        )

    if loss_method_2.ndim != 1:
        raise ValueError(
            "Method 2 loss must be one-dimensional."
        )

    if len(loss_method_1) != len(
        loss_method_2
    ):
        raise ValueError(
            "The loss series have different lengths."
        )

    if not np.isfinite(
        loss_method_1
    ).all():
        raise ValueError(
            "Method 1 loss contains non-finite values."
        )

    if not np.isfinite(
        loss_method_2
    ).all():
        raise ValueError(
            "Method 2 loss contains non-finite values."
        )

    loss_difference = (
        loss_method_1
        - loss_method_2
    )

    sample_size = len(
        loss_difference
    )

    if max_lag is None:
        max_lag = int(
            np.floor(
                4
                * (
                    sample_size / 100.0
                )**(2.0 / 9.0)
            )
        )

    long_run_variance = (
        newey_west_long_run_variance(
            loss_difference,
            max_lag
        )
    )

    if (
        not np.isfinite(
            long_run_variance
        )
        or long_run_variance <= 0
    ):
        raise ValueError(
            "The estimated long-run variance "
            "is not positive and finite."
        )

    mean_difference = (
        loss_difference.mean()
    )

    standard_error = np.sqrt(
        long_run_variance
        / sample_size
    )

    dm_statistic = (
        mean_difference
        / standard_error
    )

    p_value = (
        2.0
        * norm.sf(
            np.abs(dm_statistic)
        )
    )

    return {
        "mean_difference":
            mean_difference,

        "dm_statistic":
            dm_statistic,

        "p_value":
            p_value,

        "hac_lag":
            max_lag,

        "long_run_variance":
            long_run_variance
    }


# ------------------------------------------------------------
# 11. Holm multiple-testing correction
# ------------------------------------------------------------

def holm_adjustment(p_values):

    p_values = np.asarray(
        p_values,
        dtype=float
    )

    number_of_tests = len(
        p_values
    )

    order = np.argsort(
        p_values
    )

    ordered_p_values = (
        p_values[order]
    )

    ordered_adjusted = np.empty(
        number_of_tests
    )

    previous_adjusted = 0.0

    for rank, p_value in enumerate(
        ordered_p_values
    ):
        adjusted = (
            number_of_tests - rank
        ) * p_value

        adjusted = max(
            adjusted,
            previous_adjusted
        )

        adjusted = min(
            adjusted,
            1.0
        )

        ordered_adjusted[
            rank
        ] = adjusted

        previous_adjusted = adjusted

    adjusted_p_values = np.empty(
        number_of_tests
    )

    adjusted_p_values[
        order
    ] = ordered_adjusted

    return adjusted_p_values


# ------------------------------------------------------------
# 12. Seven planned method comparisons
# ------------------------------------------------------------

planned_comparisons = [
    ("Method 1b", "Method 3"),
    ("Method 1b", "Sorting"),
    ("Method 1b", "PAVA"),
    ("Method 1b", "Penalty"),
    ("Method 3", "Sorting"),
    ("Method 3", "PAVA"),
    ("Method 3", "Penalty")
]

dm_rows = []

for method_1, method_2 in (
    planned_comparisons
):

    test_result = dm_test_hac(
        loss_method_1=method_average_nll[
            method_1
        ],

        loss_method_2=method_average_nll[
            method_2
        ]
    )

    mean_difference = test_result[
        "mean_difference"
    ]

    if mean_difference < 0:
        lower_nll_method = method_1

    elif mean_difference > 0:
        lower_nll_method = method_2

    else:
        lower_nll_method = "Equal"

    dm_rows.append({
        "Method_1":
            method_1,

        "Method_2":
            method_2,

        "Mean_NLL_1":
            method_average_nll[
                method_1
            ].mean(),

        "Mean_NLL_2":
            method_average_nll[
                method_2
            ].mean(),

        "Mean_difference_1_minus_2":
            mean_difference,

        "DM_statistic":
            test_result[
                "dm_statistic"
            ],

        "Raw_p_value":
            test_result[
                "p_value"
            ],

        "Lower_NLL_method":
            lower_nll_method,

        "HAC_lag":
            test_result[
                "hac_lag"
            ]
    })

dm_nll_results = pd.DataFrame(
    dm_rows
)


# ------------------------------------------------------------
# 13. Apply Holm correction
# ------------------------------------------------------------

dm_nll_results[
    "Holm_p_value"
] = holm_adjustment(
    dm_nll_results[
        "Raw_p_value"
    ].to_numpy()
)

# Raw p-values remain available as the primary
# individual-comparison results.
dm_nll_results[
    "Significant_5pct_raw"
] = (
    dm_nll_results[
        "Raw_p_value"
    ]
    < 0.05
)

# Holm-adjusted results are retained as a
# multiple-comparison robustness check.
dm_nll_results[
    "Significant_5pct_Holm"
] = (
    dm_nll_results[
        "Holm_p_value"
    ]
    < 0.05
)


# ------------------------------------------------------------
# 14. Save per-date and per-level NLL
# ------------------------------------------------------------

nll_series_df = pd.DataFrame({
    "Date":
        reference_dates,

    "Actual":
        reference_actual
})

for method_name in method_average_nll:

    safe_name = (
        method_name
        .lower()
        .replace(" ", "_")
    )

    nll_series_df[
        f"{safe_name}_average_nll"
    ] = method_average_nll[
        method_name
    ]

    for level_index, level in enumerate(
        LEVELS
    ):
        nll_series_df[
            (
                f"{safe_name}_nll_"
                f"{level:.3f}"
            )
        ] = method_level_nll[
            method_name
        ][:, level_index]


nll_series_path = (
    DM_OUTPUT_DIR
    / "ernn_si_self_observation_agd_nll.csv"
)

nll_series_df.to_csv(
    nll_series_path,
    index=False
)


# ------------------------------------------------------------
# 15. Save the DM-test results
# ------------------------------------------------------------

dm_nll_results_path = (
    DM_OUTPUT_DIR
    / "ernn_si_self_dm_agd_nll_results.csv"
)

average_nll_summary_path = (
    DM_OUTPUT_DIR
    / "ernn_si_self_average_agd_nll.csv"
)

sigma_summary_path = (
    DM_OUTPUT_DIR
    / "ernn_si_self_sigma_summary.csv"
)

dm_nll_results.to_csv(
    dm_nll_results_path,
    index=False
)

average_nll_summary.to_csv(
    average_nll_summary_path,
    index=False
)

sigma_summary.to_csv(
    sigma_summary_path,
    index=False
)


# ------------------------------------------------------------
# 16. Display final results
# ------------------------------------------------------------

print(
    "\nDM TEST RESULTS — "
    "BITCOIN ERNN SI SELF — AGD NLL"
)

print(
    "A negative statistic means Method 1 "
    "has lower NLL than Method 2."
)

print(
    "The penalty forecasts and sigma values "
    "come from the 800-trial penalty model."
)

display(
    dm_nll_results.style.format({
        "Mean_NLL_1":
            "{:.8f}",

        "Mean_NLL_2":
            "{:.8f}",

        "Mean_difference_1_minus_2":
            "{:.8f}",

        "DM_statistic":
            "{:.4f}",

        "Raw_p_value":
            "{:.6f}",

        "Holm_p_value":
            "{:.6f}"
    })
)


# ------------------------------------------------------------
# 17. Saved-file confirmation
# ------------------------------------------------------------

print("\nSaved:")
print(nll_series_path)
print(dm_nll_results_path)
print(average_nll_summary_path)
print(sigma_summary_path)

print(
    "\nOutput directory:",
    DM_OUTPUT_DIR
)

print("\nNo model was retrained.")

All required sigma files were found.

Sigma sources:
Sorting/PAVA: /Users/miaomiaochen/Desktop/PhD program/Project 1/pava_crossover_results/ernn_si_self/pava_ernn_si_self_test_metrics.csv
Penalty: /Users/miaomiaochen/Desktop/PhD program/Project 1/penalty_crossover_results_800trials/ernn_si_self/penalty_ernn_si_self_test_metrics.csv
Method 1b: /Users/miaomiaochen/Desktop/PhD program/Project 1/method1b_joint_ernn_si_self_test_metrics.csv
Method 3: /Users/miaomiaochen/Desktop/PhD program/Project 1/method3_spacing_ernn_si_self_results/ernn_si_self/method3_spacing_ernn_si_self_test_metrics.csv

Sorting and PAVA raw forecasts match. The common unrestricted-model sigma values will be used.

Per-level sigma values:

Average AGD NLL:

DM TEST RESULTS — BITCOIN ERNN SI SELF — AGD NLL
A negative statistic means Method 1 has lower NLL than Method 2.
The penalty forecasts and sigma values come from the 800-trial penalty model.

Saved:
/Users/miaomiaochen/Desktop/PhD program/Project 1/dm_test_results_800trials/ernn_si_self/ernn_si_self_observation_agd_nll.csv
/Users/miaomiaochen/Desktop/PhD program/Project 1/dm_test_results_800trials/ernn_si_self/ernn_si_self_dm_agd_nll_results.csv
/Users/miaomiaochen/Desktop/PhD program/Project 1/dm_test_results_800trials/ernn_si_self/ernn_si_self_average_agd_nll.csv
/Users/miaomiaochen/Desktop/PhD program/Project 1/dm_test_results_800trials/ernn_si_self/ernn_si_self_sigma_summary.csv

Output directory: /Users/miaomiaochen/Desktop/PhD program/Project 1/dm_test_results_800trials/ernn_si_self

No model was retrained.

In [18]:
# ============================================================
# BITCOIN DM TESTS
# QRNN SI-SELF — ALD-NLL DM TESTS
# UPDATED TO USE THE 800-TRIAL PENALTY MODEL
# ============================================================

import torch
import torch.nn.functional as F


# ------------------------------------------------------------
# 1. Verify objects created by the ERNN cells
# ------------------------------------------------------------

required_objects = [
    "PROJECT_DIR",
    "LEVELS",
    "LEVEL_CODES",
    "load_ordered_sigma",
    "dm_test_hac",
    "holm_adjustment",
    "planned_comparisons"
]

missing_objects = [
    name
    for name in required_objects
    if name not in globals()
]

if missing_objects:
    raise RuntimeError(
        "Missing required objects:\n"
        + ", ".join(missing_objects)
        + "\nRun the updated ERNN alignment and "
          "AGD-NLL DM-test cells first."
    )


# ------------------------------------------------------------
# 2. QRNN SI-Self prediction paths
# ------------------------------------------------------------

qrnn_prediction_paths = {
    "Sorting": (
        PROJECT_DIR
        / "sorting_crossover_results"
        / "qrnn_si_self"
        / "sorting_qrnn_si_self_test_predictions.csv"
    ),

    "PAVA": (
        PROJECT_DIR
        / "pava_crossover_results"
        / "qrnn_si_self"
        / "pava_qrnn_si_self_test_predictions.csv"
    ),

    # Updated from the 200-trial penalty model
    # to the final 800-trial penalty model.
    "Penalty": (
        PROJECT_DIR
        / "penalty_crossover_results_800trials"
        / "qrnn_si_self"
        / "penalty_qrnn_si_self_test_predictions.csv"
    ),

    "Method 1b": (
        PROJECT_DIR
        / "method1b_joint_qrnn_si_self_test_predictions.csv"
    ),

    "Method 3": (
        PROJECT_DIR
        / "method3_spacing_qrnn_si_self_results"
        / "qrnn_si_self"
        / "method3_spacing_qrnn_si_self_test_predictions.csv"
    )
}


# ------------------------------------------------------------
# 3. Check prediction files
# ------------------------------------------------------------

missing_files = [
    str(path)
    for path in qrnn_prediction_paths.values()
    if not path.exists()
]

if missing_files:
    raise FileNotFoundError(
        "Missing QRNN prediction files:\n"
        + "\n".join(missing_files)
    )

print("All five QRNN prediction files were found.")

print("\nQRNN prediction sources:")
for method_name, path in (
    qrnn_prediction_paths.items()
):
    print(f"{method_name}: {path}")


# ------------------------------------------------------------
# 4. Load saved predictions
# ------------------------------------------------------------

qrnn_sorting_raw = pd.read_csv(
    qrnn_prediction_paths["Sorting"],
    parse_dates=["Date"]
)

qrnn_pava_raw = pd.read_csv(
    qrnn_prediction_paths["PAVA"],
    parse_dates=["Date"]
)

qrnn_penalty_raw = pd.read_csv(
    qrnn_prediction_paths["Penalty"]
)

qrnn_method1b_raw = pd.read_csv(
    qrnn_prediction_paths["Method 1b"],
    parse_dates=["Date"]
)

qrnn_method3_raw = pd.read_csv(
    qrnn_prediction_paths["Method 3"],
    parse_dates=["date"]
)


# ------------------------------------------------------------
# 5. Standardise dates, actual returns and forecasts
# ------------------------------------------------------------

qrnn_reference_dates = pd.DatetimeIndex(
    qrnn_sorting_raw["Date"]
)

qrnn_actual_returns = {
    "Sorting":
        qrnn_sorting_raw["Actual"].to_numpy(),

    "PAVA":
        qrnn_pava_raw["Actual"].to_numpy(),

    "Penalty":
        qrnn_penalty_raw["actual"].to_numpy(),

    "Method 1b":
        qrnn_method1b_raw["Actual"].to_numpy(),

    "Method 3":
        qrnn_method3_raw["actual"].to_numpy()
}

qrnn_forecast_matrices = {
    "Sorting": qrnn_sorting_raw[
        [
            f"Sorted_{code}"
            for code in LEVEL_CODES
        ]
    ].to_numpy(),

    "PAVA": qrnn_pava_raw[
        [
            f"PAVA_{code}"
            for code in LEVEL_CODES
        ]
    ].to_numpy(),

    "Penalty": qrnn_penalty_raw[
        [
            f"q_{level:.3f}"
            for level in LEVELS
        ]
    ].to_numpy(),

    "Method 1b": qrnn_method1b_raw[
        [
            f"Q_{level:.3f}"
            for level in LEVELS
        ]
    ].to_numpy(),

    "Method 3": qrnn_method3_raw[
        [
            f"q_{level:.3f}"
            for level in LEVELS
        ]
    ].to_numpy()
}


# ------------------------------------------------------------
# 6. Validate dates
# ------------------------------------------------------------

qrnn_dated_methods = {
    "PAVA": pd.DatetimeIndex(
        qrnn_pava_raw["Date"]
    ),

    "Method 1b": pd.DatetimeIndex(
        qrnn_method1b_raw["Date"]
    ),

    "Method 3": pd.DatetimeIndex(
        qrnn_method3_raw["date"]
    )
}

for method_name, method_dates in (
    qrnn_dated_methods.items()
):
    if not method_dates.equals(
        qrnn_reference_dates
    ):
        raise ValueError(
            f"{method_name} dates do not match "
            "the QRNN reference dates."
        )


# ------------------------------------------------------------
# 7. Validate actual returns and forecast matrices
# ------------------------------------------------------------

qrnn_reference_actual = (
    qrnn_actual_returns["Sorting"]
)

qrnn_alignment_rows = []

for method_name in qrnn_prediction_paths:

    method_actual = (
        qrnn_actual_returns[method_name]
    )

    method_forecasts = (
        qrnn_forecast_matrices[method_name]
    )

    correct_length = (
        len(method_actual)
        == len(qrnn_reference_actual)
    )

    correct_shape = (
        method_forecasts.shape
        == (
            len(qrnn_reference_actual),
            len(LEVELS)
        )
    )

    actuals_match = (
        correct_length
        and np.allclose(
            method_actual,
            qrnn_reference_actual,
            rtol=1e-7,
            atol=1e-9
        )
    )

    finite_actuals = np.isfinite(
        method_actual
    ).all()

    finite_forecasts = np.isfinite(
        method_forecasts
    ).all()

    qrnn_alignment_rows.append({
        "Method": method_name,
        "Observations": len(method_actual),
        "Forecast_shape": str(
            method_forecasts.shape
        ),
        "Correct_length": correct_length,
        "Correct_shape": correct_shape,
        "Actuals_match": actuals_match,
        "Finite_actuals": finite_actuals,
        "Finite_forecasts": finite_forecasts
    })

qrnn_alignment_summary = pd.DataFrame(
    qrnn_alignment_rows
)

display(qrnn_alignment_summary)

if not qrnn_alignment_summary[
    "Correct_length"
].all():
    raise RuntimeError(
        "At least one QRNN method has an incorrect "
        "number of observations."
    )

if not qrnn_alignment_summary[
    "Correct_shape"
].all():
    raise RuntimeError(
        "At least one QRNN forecast matrix has an "
        "incorrect shape."
    )

if not qrnn_alignment_summary[
    "Actuals_match"
].all():
    raise RuntimeError(
        "Actual returns are not identical across "
        "the QRNN methods."
    )

if not qrnn_alignment_summary[
    "Finite_actuals"
].all():
    raise RuntimeError(
        "At least one QRNN file contains non-finite "
        "actual returns."
    )

if not qrnn_alignment_summary[
    "Finite_forecasts"
].all():
    raise RuntimeError(
        "At least one QRNN file contains non-finite "
        "forecasts."
    )

print(
    "\nAll QRNN SI-Self predictions are aligned."
)


# ------------------------------------------------------------
# 8. Sigma paths
# ------------------------------------------------------------

qrnn_sigma_paths = {
    # Sorting and PAVA share the unrestricted-model sigma.
    "Sorting/PAVA": (
        PROJECT_DIR
        / "pava_crossover_results"
        / "qrnn_si_self"
        / "pava_qrnn_si_self_test_metrics.csv"
    ),

    # Updated to the final 800-trial penalty model.
    "Penalty": (
        PROJECT_DIR
        / "penalty_crossover_results_800trials"
        / "qrnn_si_self"
        / "penalty_qrnn_si_self_test_metrics.csv"
    ),

    "Method 1b": (
        PROJECT_DIR
        / "method1b_joint_qrnn_si_self_test_metrics.csv"
    ),

    "Method 3 checkpoint": (
        PROJECT_DIR
        / "method3_spacing_qrnn_si_self_results"
        / "qrnn_si_self"
        / "method3_spacing_qrnn_si_self_best.pt"
    )
}

missing_sigma_files = [
    str(path)
    for path in qrnn_sigma_paths.values()
    if not path.exists()
]

if missing_sigma_files:
    raise FileNotFoundError(
        "Missing QRNN sigma files:\n"
        + "\n".join(missing_sigma_files)
    )

print("\nQRNN sigma sources:")
for method_name, path in (
    qrnn_sigma_paths.items()
):
    print(f"{method_name}: {path}")


# ------------------------------------------------------------
# 9. Verify Sorting and PAVA use the same raw model
# ------------------------------------------------------------

qrnn_sorting_raw_forecasts = (
    qrnn_sorting_raw[
        [
            f"Raw_{code}"
            for code in LEVEL_CODES
        ]
    ].to_numpy()
)

qrnn_pava_raw_forecasts = (
    qrnn_pava_raw[
        [
            f"Raw_{code}"
            for code in LEVEL_CODES
        ]
    ].to_numpy()
)

if not np.allclose(
    qrnn_sorting_raw_forecasts,
    qrnn_pava_raw_forecasts,
    rtol=1e-7,
    atol=1e-9
):
    raise RuntimeError(
        "Sorting and PAVA do not use the same "
        "unrestricted QRNN forecasts."
    )

print(
    "\nSorting and PAVA raw QRNN forecasts match."
)


# ------------------------------------------------------------
# 10. Load sigma values
# ------------------------------------------------------------

qrnn_postprocessing_sigma = (
    load_ordered_sigma(
        qrnn_sigma_paths["Sorting/PAVA"],
        level_column="level"
    )
)

qrnn_method3_checkpoint = torch.load(
    qrnn_sigma_paths["Method 3 checkpoint"],
    map_location="cpu",
    weights_only=False
)

qrnn_method3_sigma = np.array([
    (
        F.softplus(
            qrnn_method3_checkpoint[
                "model_state_dicts"
            ][float(level)]["sigma_raw"]
        ).item()
        + 1e-6
    )
    for level in LEVELS
])

if not np.isfinite(
    qrnn_method3_sigma
).all():
    raise ValueError(
        "Method 3 contains non-finite sigma values."
    )

if np.any(
    qrnn_method3_sigma <= 0
):
    raise ValueError(
        "Method 3 contains non-positive sigma values."
    )

qrnn_method_sigma = {
    "Sorting":
        qrnn_postprocessing_sigma.copy(),

    "PAVA":
        qrnn_postprocessing_sigma.copy(),

    "Penalty": load_ordered_sigma(
        qrnn_sigma_paths["Penalty"],
        level_column="alpha"
    ),

    "Method 1b": load_ordered_sigma(
        qrnn_sigma_paths["Method 1b"],
        level_column="level"
    ),

    "Method 3":
        qrnn_method3_sigma
}

qrnn_sigma_summary = pd.DataFrame({
    "Level": LEVELS,
    **qrnn_method_sigma
})

print("\nQRNN per-level sigma values:")

display(
    qrnn_sigma_summary.style.format(
        "{:.8f}"
    )
)


# ------------------------------------------------------------
# 11. Observation-level ALD NLL
# ------------------------------------------------------------

def qrnn_ald_nll(
    actual,
    forecasts,
    sigma,
    levels
):
    """
    Calculate ALD NLL for every observation and level.

    Returns
    -------
    level_nll:
        ALD NLL matrix with shape (T, K).

    average_nll:
        Per-date average ALD NLL with shape (T,),
        obtained by averaging across the seven levels.
    """

    actual = np.asarray(
        actual,
        dtype=float
    )

    forecasts = np.asarray(
        forecasts,
        dtype=float
    )

    sigma = np.asarray(
        sigma,
        dtype=float
    )

    levels = np.asarray(
        levels,
        dtype=float
    )

    expected_shape = (
        len(actual),
        len(levels)
    )

    if forecasts.shape != expected_shape:
        raise ValueError(
            "Incorrect QRNN forecast shape.\n"
            f"Expected: {expected_shape}\n"
            f"Found: {forecasts.shape}"
        )

    if sigma.shape != (
        len(levels),
    ):
        raise ValueError(
            "Incorrect QRNN sigma shape."
        )

    if not np.isfinite(
        actual
    ).all():
        raise ValueError(
            "Actual returns contain non-finite values."
        )

    if not np.isfinite(
        forecasts
    ).all():
        raise ValueError(
            "QRNN forecasts contain non-finite values."
        )

    if (
        not np.isfinite(sigma).all()
        or np.any(sigma <= 0)
    ):
        raise ValueError(
            "QRNN sigma values must be positive and finite."
        )

    residuals = (
        actual[:, None]
        - forecasts
    )

    indicators = (
        residuals < 0
    ).astype(float)

    pinball_losses = (
        residuals
        * (
            levels[None, :]
            - indicators
        )
    )

    level_nll = (
        -np.log(
            levels[None, :]
            * (1.0 - levels[None, :])
        )
        + np.log(
            sigma[None, :]
        )
        + pinball_losses
        / sigma[None, :]
    )

    average_nll = level_nll.mean(
        axis=1
    )

    return (
        level_nll,
        average_nll
    )


# ------------------------------------------------------------
# 12. Calculate NLL series for every method
# ------------------------------------------------------------

qrnn_method_level_nll = {}
qrnn_method_average_nll = {}

for method_name, forecasts in (
    qrnn_forecast_matrices.items()
):
    (
        level_nll,
        average_nll
    ) = qrnn_ald_nll(
        actual=qrnn_reference_actual,
        forecasts=forecasts,
        sigma=qrnn_method_sigma[method_name],
        levels=LEVELS
    )

    qrnn_method_level_nll[
        method_name
    ] = level_nll

    qrnn_method_average_nll[
        method_name
    ] = average_nll


# ------------------------------------------------------------
# 13. Average NLL summary
# ------------------------------------------------------------

qrnn_average_nll_summary = pd.DataFrame({
    "Method": list(
        qrnn_method_average_nll.keys()
    ),

    "Average_ALD_NLL": [
        losses.mean()
        for losses
        in qrnn_method_average_nll.values()
    ]
}).sort_values(
    "Average_ALD_NLL"
).reset_index(
    drop=True
)

print("\nAverage ALD NLL:")

display(
    qrnn_average_nll_summary.style.format({
        "Average_ALD_NLL": "{:.8f}"
    })
)


# ------------------------------------------------------------
# 14. Run the seven DM comparisons
# ------------------------------------------------------------

qrnn_dm_rows = []

for method_1, method_2 in (
    planned_comparisons
):
    result = dm_test_hac(
        loss_method_1=(
            qrnn_method_average_nll[
                method_1
            ]
        ),

        loss_method_2=(
            qrnn_method_average_nll[
                method_2
            ]
        )
    )

    mean_difference = result[
        "mean_difference"
    ]

    if mean_difference < 0:
        lower_nll_method = method_1

    elif mean_difference > 0:
        lower_nll_method = method_2

    else:
        lower_nll_method = "Equal"

    qrnn_dm_rows.append({
        "Method_1":
            method_1,

        "Method_2":
            method_2,

        "Mean_NLL_1":
            qrnn_method_average_nll[
                method_1
            ].mean(),

        "Mean_NLL_2":
            qrnn_method_average_nll[
                method_2
            ].mean(),

        "Mean_difference_1_minus_2":
            mean_difference,

        "DM_statistic":
            result["dm_statistic"],

        "Raw_p_value":
            result["p_value"],

        "Lower_NLL_method":
            lower_nll_method,

        "HAC_lag":
            result["hac_lag"]
    })

qrnn_dm_results = pd.DataFrame(
    qrnn_dm_rows
)


# ------------------------------------------------------------
# 15. Raw and Holm-adjusted significance
# ------------------------------------------------------------

# Raw p-values are the primary pairwise DM-test results.
qrnn_dm_results[
    "Significant_5pct_raw"
] = (
    qrnn_dm_results[
        "Raw_p_value"
    ]
    < 0.05
)

# Holm is retained only as a multiple-testing robustness check.
qrnn_dm_results[
    "Holm_p_value"
] = holm_adjustment(
    qrnn_dm_results[
        "Raw_p_value"
    ].to_numpy()
)

qrnn_dm_results[
    "Significant_5pct_Holm"
] = (
    qrnn_dm_results[
        "Holm_p_value"
    ]
    < 0.05
)


# ------------------------------------------------------------
# 16. Save results separately from the 200-trial analysis
# ------------------------------------------------------------

QRNN_DM_OUTPUT_DIR = (
    PROJECT_DIR
    / "dm_test_results_800trials"
    / "qrnn_si_self"
)

QRNN_DM_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

qrnn_nll_series = pd.DataFrame({
    "Date":
        qrnn_reference_dates,

    "Actual":
        qrnn_reference_actual
})

for method_name in (
    qrnn_method_average_nll
):
    safe_name = (
        method_name
        .lower()
        .replace(" ", "_")
    )

    qrnn_nll_series[
        f"{safe_name}_average_nll"
    ] = qrnn_method_average_nll[
        method_name
    ]

    for level_index, level in enumerate(
        LEVELS
    ):
        qrnn_nll_series[
            f"{safe_name}_nll_{level:.3f}"
        ] = qrnn_method_level_nll[
            method_name
        ][:, level_index]


# ------------------------------------------------------------
# 17. Output paths
# ------------------------------------------------------------

qrnn_nll_series_path = (
    QRNN_DM_OUTPUT_DIR
    / "qrnn_si_self_observation_ald_nll.csv"
)

qrnn_dm_results_path = (
    QRNN_DM_OUTPUT_DIR
    / "qrnn_si_self_dm_ald_nll_results.csv"
)

qrnn_average_nll_path = (
    QRNN_DM_OUTPUT_DIR
    / "qrnn_si_self_average_ald_nll.csv"
)

qrnn_sigma_summary_path = (
    QRNN_DM_OUTPUT_DIR
    / "qrnn_si_self_sigma_summary.csv"
)


# ------------------------------------------------------------
# 18. Save CSV files
# ------------------------------------------------------------

qrnn_nll_series.to_csv(
    qrnn_nll_series_path,
    index=False
)

qrnn_dm_results.to_csv(
    qrnn_dm_results_path,
    index=False
)

qrnn_average_nll_summary.to_csv(
    qrnn_average_nll_path,
    index=False
)

qrnn_sigma_summary.to_csv(
    qrnn_sigma_summary_path,
    index=False
)


# ------------------------------------------------------------
# 19. Display final results
# ------------------------------------------------------------

print(
    "\nDM TEST RESULTS — "
    "BITCOIN QRNN SI SELF — ALD NLL"
)

print(
    "A negative statistic means Method 1 "
    "has lower NLL than Method 2."
)

print(
    "Raw p-values are the primary pairwise results. "
    "Holm-adjusted values are retained as a robustness check."
)

print(
    "The penalty forecasts and sigma values "
    "come from the 800-trial penalty model."
)

main_display_columns = [
    "Method_1",
    "Method_2",
    "Mean_NLL_1",
    "Mean_NLL_2",
    "Mean_difference_1_minus_2",
    "DM_statistic",
    "Raw_p_value",
    "Lower_NLL_method",
    "Significant_5pct_raw"
]

display(
    qrnn_dm_results[
        main_display_columns
    ].style.format({
        "Mean_NLL_1":
            "{:.8f}",

        "Mean_NLL_2":
            "{:.8f}",

        "Mean_difference_1_minus_2":
            "{:.8f}",

        "DM_statistic":
            "{:.4f}",

        "Raw_p_value":
            "{:.6f}"
    })
)


# ------------------------------------------------------------
# 20. Display Holm robustness results separately
# ------------------------------------------------------------

holm_display_columns = [
    "Method_1",
    "Method_2",
    "Raw_p_value",
    "Holm_p_value",
    "Significant_5pct_Holm"
]

print("\nHolm multiple-testing robustness check:")

display(
    qrnn_dm_results[
        holm_display_columns
    ].style.format({
        "Raw_p_value":
            "{:.6f}",

        "Holm_p_value":
            "{:.6f}"
    })
)


# ------------------------------------------------------------
# 21. Saved-file confirmation
# ------------------------------------------------------------

print("\nSaved:")
print(qrnn_nll_series_path)
print(qrnn_dm_results_path)
print(qrnn_average_nll_path)
print(qrnn_sigma_summary_path)

print(
    "\nOutput directory:",
    QRNN_DM_OUTPUT_DIR
)

print("\nNo model was retrained.")

All five QRNN prediction files were found.

QRNN prediction sources:
Sorting: /Users/miaomiaochen/Desktop/PhD program/Project 1/sorting_crossover_results/qrnn_si_self/sorting_qrnn_si_self_test_predictions.csv
PAVA: /Users/miaomiaochen/Desktop/PhD program/Project 1/pava_crossover_results/qrnn_si_self/pava_qrnn_si_self_test_predictions.csv
Penalty: /Users/miaomiaochen/Desktop/PhD program/Project 1/penalty_crossover_results_800trials/qrnn_si_self/penalty_qrnn_si_self_test_predictions.csv
Method 1b: /Users/miaomiaochen/Desktop/PhD program/Project 1/method1b_joint_qrnn_si_self_test_predictions.csv
Method 3: /Users/miaomiaochen/Desktop/PhD program/Project 1/method3_spacing_qrnn_si_self_results/qrnn_si_self/method3_spacing_qrnn_si_self_test_predictions.csv

,Method,Observations,Forecast_shape,Correct_length,Correct_shape,Actuals_match,Finite_actuals,Finite_forecasts
0,Sorting,454,"(454, 7)",True,True,True,True,True
1,PAVA,454,"(454, 7)",True,True,True,True,True
2,Penalty,454,"(454, 7)",True,True,True,True,True
3,Method 1b,454,"(454, 7)",True,True,True,True,True
4,Method 3,454,"(454, 7)",True,True,True,True,True

All QRNN SI-Self predictions are aligned.

QRNN sigma sources:
Sorting/PAVA: /Users/miaomiaochen/Desktop/PhD program/Project 1/pava_crossover_results/qrnn_si_self/pava_qrnn_si_self_test_metrics.csv
Penalty: /Users/miaomiaochen/Desktop/PhD program/Project 1/penalty_crossover_results_800trials/qrnn_si_self/penalty_qrnn_si_self_test_metrics.csv
Method 1b: /Users/miaomiaochen/Desktop/PhD program/Project 1/method1b_joint_qrnn_si_self_test_metrics.csv
Method 3 checkpoint: /Users/miaomiaochen/Desktop/PhD program/Project 1/method3_spacing_qrnn_si_self_results/qrnn_si_self/method3_spacing_qrnn_si_self_best.pt

Sorting and PAVA raw QRNN forecasts match.

QRNN per-level sigma values:

Average ALD NLL:

DM TEST RESULTS — BITCOIN QRNN SI SELF — ALD NLL
A negative statistic means Method 1 has lower NLL than Method 2.
Raw p-values are the primary pairwise results. Holm-adjusted values are retained as a robustness check.
The penalty forecasts and sigma values come from the 800-trial penalty model.

Holm multiple-testing robustness check:

Saved:
/Users/miaomiaochen/Desktop/PhD program/Project 1/dm_test_results_800trials/qrnn_si_self/qrnn_si_self_observation_ald_nll.csv
/Users/miaomiaochen/Desktop/PhD program/Project 1/dm_test_results_800trials/qrnn_si_self/qrnn_si_self_dm_ald_nll_results.csv
/Users/miaomiaochen/Desktop/PhD program/Project 1/dm_test_results_800trials/qrnn_si_self/qrnn_si_self_average_ald_nll.csv
/Users/miaomiaochen/Desktop/PhD program/Project 1/dm_test_results_800trials/qrnn_si_self/qrnn_si_self_sigma_summary.csv

Output directory: /Users/miaomiaochen/Desktop/PhD program/Project 1/dm_test_results_800trials/qrnn_si_self

No model was retrained.

# Kupiec test

## Kupiec unconditional-coverage tests

In [ ]:
# ============================================================
# BITCOIN KUPIEC UNCONDITIONAL-COVERAGE TESTS
# QRNN SI-SELF: METHOD 1B, METHOD 3, AND PENALTY
# ALL SEVEN QUANTILE LEVELS
# ============================================================

import numpy as np
import pandas as pd
from scipy.stats import chi2


# ------------------------------------------------------------
# 1. Verify the aligned forecasts from the QRNN DM section
# ------------------------------------------------------------

required_objects = [
    "PROJECT_DIR",
    "LEVELS",
    "qrnn_reference_dates",
    "qrnn_reference_actual",
    "qrnn_forecast_matrices",
    "holm_adjustment",
]

missing_objects = [
    name for name in required_objects
    if name not in globals()
]

if missing_objects:
    raise RuntimeError(
        "Run the preceding QRNN SI-Self DM-test cell first. Missing:\n"
        + ", ".join(missing_objects)
    )

KUPIEC_METHODS = ["Method 1b", "Method 3", "Penalty"]

for method_name in KUPIEC_METHODS:
    if method_name not in qrnn_forecast_matrices:
        raise KeyError(
            f"Forecasts are unavailable for {method_name}."
        )


# ------------------------------------------------------------
# 2. Kupiec likelihood-ratio test of unconditional coverage
# ------------------------------------------------------------

def kupiec_unconditional_coverage(hits, expected_probability):
    """Return the Kupiec LRuc statistic and asymptotic p-value."""

    hits = np.asarray(hits, dtype=int)

    if hits.ndim != 1:
        raise ValueError("hits must be a one-dimensional sequence.")

    if not np.isin(hits, [0, 1]).all():
        raise ValueError("hits must contain only zeros and ones.")

    sample_size = int(len(hits))
    hit_count = int(hits.sum())
    expected_probability = float(expected_probability)

    if not 0.0 < expected_probability < 1.0:
        raise ValueError(
            "expected_probability must lie strictly between 0 and 1."
        )

    observed_probability = hit_count / sample_size

    null_log_likelihood = (
        hit_count * np.log(expected_probability)
        + (sample_size - hit_count)
        * np.log(1.0 - expected_probability)
    )

    alternative_log_likelihood = 0.0

    if hit_count > 0:
        alternative_log_likelihood += (
            hit_count * np.log(observed_probability)
        )

    if hit_count < sample_size:
        alternative_log_likelihood += (
            (sample_size - hit_count)
            * np.log(1.0 - observed_probability)
        )

    lr_uc = max(
        0.0,
        -2.0 * (
            null_log_likelihood
            - alternative_log_likelihood
        ),
    )

    return {
        "sample_size": sample_size,
        "hit_count": hit_count,
        "expected_probability": expected_probability,
        "observed_probability": observed_probability,
        "expected_hits": sample_size * expected_probability,
        "lr_uc": lr_uc,
        "p_value": float(chi2.sf(lr_uc, df=1)),
    }


# ------------------------------------------------------------
# 3. Test P(y_t < q_alpha,t) = alpha at all seven levels
# ------------------------------------------------------------

actual = np.asarray(qrnn_reference_actual, dtype=float)
kupiec_rows = []

for method_name in KUPIEC_METHODS:
    forecasts = np.asarray(
        qrnn_forecast_matrices[method_name],
        dtype=float,
    )

    if forecasts.shape != (len(actual), len(LEVELS)):
        raise ValueError(
            f"Unexpected forecast shape for {method_name}: "
            f"{forecasts.shape}"
        )

    for level_index, quantile_level in enumerate(LEVELS):
        quantile_level = float(quantile_level)
        forecast = forecasts[:, level_index]

        # For a correctly calibrated alpha-quantile forecast,
        # Pr(y_t < q_alpha,t) should equal alpha.
        hits = (actual < forecast).astype(int)

        result = kupiec_unconditional_coverage(
            hits=hits,
            expected_probability=quantile_level,
        )

        kupiec_rows.append({
            "Method": method_name,
            "Quantile_Level": quantile_level,
            "Test_Observations": result["sample_size"],
            "Expected_Hits": result["expected_hits"],
            "Observed_Hits": result["hit_count"],
            "Expected_Coverage": result["expected_probability"],
            "Observed_Coverage": result["observed_probability"],
            "Coverage_Error": (
                result["observed_probability"]
                - result["expected_probability"]
            ),
            "Kupiec_LRuc": result["lr_uc"],
            "Raw_p_value": result["p_value"],
        })


kupiec_results = pd.DataFrame(kupiec_rows)

# Raw p-values are the primary reported results. Holm values are retained
# as an optional robustness column across all 21 planned tests.
kupiec_results["Holm_p_value"] = holm_adjustment(
    kupiec_results["Raw_p_value"].to_numpy()
)

kupiec_results["Reject_5pct_raw"] = (
    kupiec_results["Raw_p_value"] < 0.05
)

kupiec_results["Reject_5pct_Holm"] = (
    kupiec_results["Holm_p_value"] < 0.05
)

kupiec_results["Raw_Coverage_Decision"] = np.where(
    kupiec_results["Reject_5pct_raw"],
    "Reject coverage",
    "Do not reject coverage",
)


# ------------------------------------------------------------
# 4. Save and display results
# ------------------------------------------------------------

KUPIEC_OUTPUT_DIR = (
    PROJECT_DIR
    / "dm_test_results"
    / "qrnn_si_self"
)
KUPIEC_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

kupiec_results_path = (
    KUPIEC_OUTPUT_DIR
    / "qrnn_si_self_kupiec_method1b_method3_penalty_all_levels.csv"
)

kupiec_results.to_csv(kupiec_results_path, index=False)

print(
    "KUPIEC UNCONDITIONAL-COVERAGE TESTS — "
    "QRNN SI-SELF, ALL SEVEN LEVELS"
)
print(
    "H0: Pr(y_t < q_alpha,t) = alpha. "
    "Raw p-values are used for the main decision."
)

display_columns = [
    "Method",
    "Quantile_Level",
    "Observed_Hits",
    "Expected_Coverage",
    "Observed_Coverage",
    "Coverage_Error",
    "Kupiec_LRuc",
    "Raw_p_value",
    "Raw_Coverage_Decision",
]

display(
    kupiec_results[display_columns].style.format({
        "Quantile_Level": "{:.3f}",
        "Expected_Coverage": "{:.4f}",
        "Observed_Coverage": "{:.4f}",
        "Coverage_Error": "{:+.4f}",
        "Kupiec_LRuc": "{:.4f}",
        "Raw_p_value": "{:.6f}",
    })
)

print(f"\nSaved to:\n{kupiec_results_path}")
print("No model was retrained.")