# SPY Hybrid QRNN S Cross-lagged

Original unrestricted model tuning with seven separately estimated quantile levels and rank-based model selection.

In [1]:
# ============================================================
# SPY MODELLING DATA PREPARATION
# Common setup for all ERNN and QRNN specifications
# ============================================================

from pathlib import Path
import random
import numpy as np
import pandas as pd
import torch


# ------------------------------------------------------------
# 1. Reproducibility and device
# ------------------------------------------------------------

BASE_SEED = 2026

random.seed(BASE_SEED)
np.random.seed(BASE_SEED)
torch.manual_seed(BASE_SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(BASE_SEED)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", device)


# ------------------------------------------------------------
# 2. Load the scaled SPY dataset
# ------------------------------------------------------------

DATA_PATH = Path.home() / "SPY_features_scaled.csv"

df = pd.read_csv(
    DATA_PATH,
    index_col="Date",
    parse_dates=True
)

df = (
    df
    .sort_index()
    .drop_duplicates()
    .dropna()
    .copy()
)


# ------------------------------------------------------------
# 3. Response and predictors
# ------------------------------------------------------------

target_col = "log_return"

feature_cols = [
    "Volatility",
    "RSI_14",
    "ATR_14",
    "QQQ_LogReturns",
    "VIX_LogChange",
    "Volume_LogChange",
]

required_cols = [target_col] + feature_cols

missing_cols = [
    column
    for column in required_cols
    if column not in df.columns
]

if missing_cols:
    raise ValueError(
        "Missing required columns: "
        + ", ".join(missing_cols)
    )


# ------------------------------------------------------------
# 4. Chronological 70%-15%-15% split
# ------------------------------------------------------------

train_size = int(len(df) * 0.70)
val_size = int(len(df) * 0.15)

train_df = df.iloc[:train_size].copy()
val_df = df.iloc[train_size:train_size + val_size].copy()
test_df = df.iloc[train_size + val_size:].copy()


# ------------------------------------------------------------
# 5. Convert samples to tensors
# ------------------------------------------------------------

def dataframe_to_tensors(sample):
    X = torch.tensor(
        sample[feature_cols].to_numpy(),
        dtype=torch.float32,
        device=device
    )
    y = torch.tensor(
        sample[target_col].to_numpy(),
        dtype=torch.float32,
        device=device
    )
    return X, y


X_train, y_train = dataframe_to_tensors(train_df)
X_val, y_val = dataframe_to_tensors(val_df)
X_test, y_test = dataframe_to_tensors(test_df)

# Compatibility aliases used by later QRNN cells.
X_test_q = X_test
y_test_q = y_test

levels = [
    0.025,
    0.050,
    0.250,
    0.500,
    0.750,
    0.950,
    0.975,
]

alpha_levels = levels
tau_levels = levels


# ------------------------------------------------------------
# 6. Checks and split summary
# ------------------------------------------------------------

assert len(X_train) == len(y_train)
assert len(X_val) == len(y_val)
assert len(X_test) == len(y_test)
assert X_train.shape[1] == len(feature_cols)
assert torch.isfinite(X_train).all()
assert torch.isfinite(X_val).all()
assert torch.isfinite(X_test).all()
assert torch.isfinite(y_train).all()
assert torch.isfinite(y_val).all()
assert torch.isfinite(y_test).all()

split_summary = pd.DataFrame({
    "Sample": ["Training", "Validation", "Test"],
    "Observations": [len(train_df), len(val_df), len(test_df)],
    "Start": [
        train_df.index.min().date(),
        val_df.index.min().date(),
        test_df.index.min().date(),
    ],
    "End": [
        train_df.index.max().date(),
        val_df.index.max().date(),
        test_df.index.max().date(),
    ],
})

display(split_summary)

print("Input features:", feature_cols)
print("Number of predictors:", len(feature_cols))
print("X_train shape:", tuple(X_train.shape))
print("X_val shape:  ", tuple(X_val.shape))
print("X_test shape: ", tuple(X_test.shape))

Device: cpu

       Sample  Observations       Start         End
0    Training          2219  2014-01-23  2022-11-11
1  Validation           475  2022-11-14  2024-10-04
2        Test           476  2024-10-07  2026-08-31

Input features: ['Volatility', 'RSI_14', 'ATR_14', 'QQQ_LogReturns', 'VIX_LogChange', 'Volume_LogChange']
Number of predictors: 6
X_train shape: (2219, 6)
X_val shape:   (475, 6)
X_test shape:  (476, 6)

## Original tuning

Run after the preparation cell.

In [3]:
# ============================================================
# ORIGINAL TUNING — SPY HYBRID QRNN S CROSS-LAGGED
# Seven separately estimated levels; 200 Optuna trials per level
# ============================================================

import copy
import json
import time

import optuna
import torch.nn as nn
import torch.nn.functional as F
from optuna.samplers import TPESampler


MODEL_NAME = "spy_qrnn_s_cross"
FORM = "S"
LAG_TYPE = "cross"
N_TRIALS = 200
MAX_EPOCHS = 200

ALPHA_LEVELS = [
    0.025, 0.050, 0.250, 0.500,
    0.750, 0.950, 0.975,
]

OUTPUT_DIR = Path("spy_original_tuning_results") / MODEL_NAME
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("Model:", MODEL_NAME)
print("Output directory:", OUTPUT_DIR.resolve())


def set_model_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def hybrid_qrnn_loss(y, q_hybrid, sigma_al, alpha):
    """Mean asymmetric-Laplace negative log-likelihood."""
    eps = torch.finfo(q_hybrid.dtype).eps
    sigma_al = torch.clamp(sigma_al, min=eps)
    alpha_tensor = torch.as_tensor(
        alpha,
        dtype=q_hybrid.dtype,
        device=q_hybrid.device
    )
    residual = y - q_hybrid
    indicator = (residual < 0).to(q_hybrid.dtype)
    check_loss = residual * (alpha_tensor - indicator)
    nll = (
        -torch.log(alpha_tensor * (1.0 - alpha_tensor))
        + torch.log(sigma_al)
        + check_loss / sigma_al
    )
    return nll.mean()


def compute_hybrid_location(y, X, beta1, beta2, beta3, fnn, psi):
    """S-form cross-lagged CAViaR-hybrid recursion."""
    fnn_output = fnn(X).squeeze(-1)
    zero_value = y.new_zeros(())
    statistical_forecasts = [zero_value]
    hybrid_forecasts = [zero_value]

    for time_index in range(1, len(y)):
        previous_return = y[time_index - 1]
        previous_state = hybrid_forecasts[time_index - 1]
        absolute_return = torch.abs(previous_return)
        statistical_value = (
            beta1 * previous_state
            + beta2 * absolute_return
        )
        hybrid_value = (
            psi * statistical_value
            + (1.0 - psi) * fnn_output[time_index]
        )
        statistical_forecasts.append(statistical_value)
        hybrid_forecasts.append(hybrid_value)

    return (
        torch.stack(hybrid_forecasts),
        torch.stack(statistical_forecasts),
    )


class HybridQRNN_S_Cross(nn.Module):
    def __init__(self, input_dim, config):
        super().__init__()
        self.eps = 1e-6
        self.beta1_raw = nn.Parameter(torch.tensor(1.386))
        self.beta2_raw = nn.Parameter(torch.tensor(0.3))
        self.psi_raw = nn.Parameter(torch.tensor(0.0))
        self.sigma_raw = nn.Parameter(torch.tensor(0.5))

        layers = []
        previous_dimension = input_dim
        for layer_index in range(config["n_hidden_layers"]):
            hidden_dimension = config[f"hidden_dim_{layer_index}"]
            layers.append(nn.Linear(previous_dimension, hidden_dimension))
            if config["layernorm"]:
                layers.append(nn.LayerNorm(hidden_dimension))
            layers.append(self.get_activation(config["activation"]))
            if config["dropout"] > 0:
                layers.append(nn.Dropout(config["dropout"]))
            previous_dimension = hidden_dimension
        layers.append(nn.Linear(previous_dimension, 1))
        self.fnn = nn.Sequential(*layers)
        self.initialise_weights(config["weight_init"])

    @staticmethod
    def get_activation(name):
        return {
            "relu": nn.ReLU(),
            "elu": nn.ELU(),
            "gelu": nn.GELU(),
            "tanh": nn.Tanh(),
        }[name]

    def initialise_weights(self, method):
        for module in self.fnn.modules():
            if not isinstance(module, nn.Linear):
                continue
            if method == "glorot":
                nn.init.xavier_uniform_(module.weight)
            else:
                nn.init.kaiming_uniform_(module.weight)
            if module.bias is not None:
                nn.init.zeros_(module.bias)

    def forward(self, y, X):
        beta1 = torch.sigmoid(self.beta1_raw)
        beta2 = F.softplus(self.beta2_raw)
        beta3 = None
        psi = torch.sigmoid(self.psi_raw)
        sigma = F.softplus(self.sigma_raw) + self.eps
        hybrid, statistical = compute_hybrid_location(
            y, X, beta1, beta2, beta3, self.fnn, psi
        )
        return hybrid, sigma, statistical


def calculate_crp(y, forecast, alpha):
    if alpha <= 0.5:
        empirical = (y <= forecast).float().mean().item()
        target = alpha
    else:
        empirical = (y > forecast).float().mean().item()
        target = 1.0 - alpha
    crp = empirical / target
    return crp, (crp - 1.0) ** 2, empirical


def suggest_config(trial):
    config = {
        "n_hidden_layers": trial.suggest_int("n_hidden_layers", 1, 3),
        "activation": trial.suggest_categorical(
            "activation", ["relu", "elu", "gelu", "tanh"]
        ),
        "dropout": trial.suggest_float("dropout", 0.0, 0.5),
        "layernorm": trial.suggest_categorical("layernorm", [True, False]),
        "weight_init": trial.suggest_categorical(
            "weight_init", ["glorot", "he"]
        ),
        "lr": trial.suggest_float("lr", 1e-4, 5e-2, log=True),
        "optimizer": trial.suggest_categorical(
            "optimizer", ["adam", "adamw"]
        ),
        "weight_decay": trial.suggest_float("weight_decay", 0.0, 1e-4),
        "gradient_clip": trial.suggest_categorical(
            "gradient_clip", [0.1, 1.0, 5.0]
        ),
        "patience": trial.suggest_categorical(
            "patience", [10, 20, 30]
        ),
    }
    for layer_index in range(config["n_hidden_layers"]):
        config[f"hidden_dim_{layer_index}"] = trial.suggest_int(
            f"hidden_dim_{layer_index}", 32, 256
        )
    return config


def make_optimizer(model, config):
    arguments = {
        "params": model.parameters(),
        "lr": config["lr"],
        "weight_decay": config["weight_decay"],
    }
    if config["optimizer"] == "adam":
        return torch.optim.Adam(**arguments)
    return torch.optim.AdamW(**arguments)


def train_configuration(config, alpha, model_seed=BASE_SEED):
    set_model_seed(model_seed)
    model = HybridQRNN_S_Cross(X_train.shape[1], config).to(device)
    optimizer = make_optimizer(model, config)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="min",
        patience=10,
        factor=0.5,
        min_lr=1e-6,
    )
    best_nll = np.inf
    best_state = None
    patience_counter = 0
    epochs_completed = 0

    for epoch in range(MAX_EPOCHS):
        epochs_completed = epoch + 1
        model.train()
        optimizer.zero_grad()
        train_forecast, train_sigma, _ = model(y_train, X_train)
        train_loss = hybrid_qrnn_loss(
            y_train, train_forecast, train_sigma, alpha
        )
        if not torch.isfinite(train_loss):
            return None
        train_loss.backward()
        nn.utils.clip_grad_norm_(
            model.parameters(), config["gradient_clip"]
        )
        optimizer.step()

        model.eval()
        with torch.no_grad():
            validation_forecast, validation_sigma, _ = model(y_val, X_val)
            validation_loss = hybrid_qrnn_loss(
                y_val, validation_forecast, validation_sigma, alpha
            )
        if not torch.isfinite(validation_loss):
            return None
        scheduler.step(validation_loss)
        current_nll = validation_loss.item()
        if current_nll < best_nll:
            best_nll = current_nll
            best_state = copy.deepcopy(model.state_dict())
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= config["patience"]:
                break

    if best_state is None:
        return None
    model.load_state_dict(best_state)
    model.eval()
    with torch.no_grad():
        validation_forecast, validation_sigma, _ = model(y_val, X_val)
        validation_nll = hybrid_qrnn_loss(
            y_val, validation_forecast, validation_sigma, alpha
        ).item()
        crp, crp_penalty, hit_rate = calculate_crp(
            y_val, validation_forecast, alpha
        )
    parameters = {
        "beta1": torch.sigmoid(model.beta1_raw).item(),
        "beta2": F.softplus(model.beta2_raw).item(),
        "beta3": np.nan,
        "psi": torch.sigmoid(model.psi_raw).item(),
        "sigma": (F.softplus(model.sigma_raw) + model.eps).item(),
    }
    return {
        "model": model,
        "validation_nll": validation_nll,
        "validation_crp": crp,
        "validation_crp_penalty": crp_penalty,
        "validation_hit_rate": hit_rate,
        "epochs_completed": epochs_completed,
        **parameters,
    }


def objective(trial, alpha):
    config = suggest_config(trial)
    result = train_configuration(config, alpha)
    if result is None:
        raise optuna.TrialPruned("Non-finite loss or no valid checkpoint.")
    for name in [
        "validation_nll", "validation_crp", "validation_crp_penalty",
        "validation_hit_rate", "epochs_completed", "beta1", "beta2",
        "beta3", "psi", "sigma",
    ]:
        trial.set_user_attr(name, result[name])
    return result["validation_nll"]


def rank_trials(study):
    trials = [
        trial for trial in study.trials
        if trial.state == optuna.trial.TrialState.COMPLETE
        and trial.value is not None
        and np.isfinite(trial.value)
        and "validation_crp_penalty" in trial.user_attrs
    ]
    if not trials:
        raise RuntimeError("No valid completed Optuna trials.")
    nll_order = sorted(
        trials, key=lambda trial: trial.user_attrs["validation_nll"]
    )
    crp_order = sorted(
        trials,
        key=lambda trial: trial.user_attrs["validation_crp_penalty"],
    )
    nll_rank = {trial.number: rank for rank, trial in enumerate(nll_order, 1)}
    crp_rank = {trial.number: rank for rank, trial in enumerate(crp_order, 1)}
    records = []
    for trial in trials:
        record = {
            "trial": trial.number,
            **trial.user_attrs,
            "rank_nll": nll_rank[trial.number],
            "rank_crp": crp_rank[trial.number],
            "sum_rank": nll_rank[trial.number] + crp_rank[trial.number],
            **trial.params,
        }
        records.append(record)
    table = pd.DataFrame(records).sort_values(
        [
            "sum_rank",
            "validation_nll",
            "validation_crp_penalty",
            "trial",
        ]
    ).reset_index(drop=True)
    selected_number = int(table.iloc[0]["trial"])
    selected_trial = next(
        trial for trial in trials if trial.number == selected_number
    )
    return selected_trial, table


best_configs_spy_qrnn_s_cross = {}
best_models_spy_qrnn_s_cross = {}
summary_records = []
overall_start = time.time()

for level_index, alpha in enumerate(ALPHA_LEVELS):
    level_start = time.time()
    sampler_seed = BASE_SEED + level_index
    print("\n" + "=" * 72)
    print(f"Tuning {MODEL_NAME} at alpha={alpha:.3f}")
    print(f"Trials={N_TRIALS} | sampler seed={sampler_seed}")
    print("=" * 72)

    study = optuna.create_study(
        direction="minimize",
        sampler=TPESampler(seed=sampler_seed),
        study_name=f"{MODEL_NAME}_alpha_{alpha:.3f}",
    )
    study.optimize(
        lambda trial, current_alpha=alpha: objective(trial, current_alpha),
        n_trials=N_TRIALS,
        show_progress_bar=True,
        gc_after_trial=True,
    )
    selected_trial, ranking_table = rank_trials(study)
    alpha_label = f"{alpha:.3f}"
    ranking_table.insert(0, "alpha", alpha)
    ranking_path = OUTPUT_DIR / (
        f"{MODEL_NAME}_ranking_alpha_{alpha_label}.csv"
    )
    ranking_table.to_csv(ranking_path, index=False)

    selected_config = selected_trial.params.copy()
    selected_result = train_configuration(selected_config, alpha)
    if selected_result is None:
        raise RuntimeError(
            f"Selected trial could not be reproduced for alpha={alpha}."
        )
    selected_model = selected_result["model"]
    checkpoint_path = OUTPUT_DIR / (
        f"{MODEL_NAME}_best_alpha_{alpha_label}.pt"
    )
    torch.save(
        {
            "model_name": MODEL_NAME,
            "asset": "SPY",
            "form": FORM,
            "lag_type": LAG_TYPE,
            "alpha": alpha,
            "selected_trial": selected_trial.number,
            "config": selected_config,
            "model_state_dict": {
                key: value.detach().cpu()
                for key, value in selected_model.state_dict().items()
            },
            "validation_nll": selected_result["validation_nll"],
            "validation_crp": selected_result["validation_crp"],
            "validation_crp_penalty": selected_result[
                "validation_crp_penalty"
            ],
            "validation_hit_rate": selected_result["validation_hit_rate"],
            "estimated_parameters": {
                name: selected_result[name]
                for name in ["beta1", "beta2", "beta3", "psi", "sigma"]
            },
            "feature_cols": feature_cols,
            "number_of_trials": N_TRIALS,
            "base_seed": BASE_SEED,
            "sampler_seed": sampler_seed,
        },
        checkpoint_path,
    )
    selected_record = {
        **selected_config,
        "selected_trial": selected_trial.number,
        **{
            name: selected_result[name]
            for name in [
                "validation_nll", "validation_crp",
                "validation_crp_penalty", "validation_hit_rate",
                "beta1", "beta2", "beta3", "psi", "sigma",
            ]
        },
    }
    best_configs_spy_qrnn_s_cross[alpha] = selected_record
    best_models_spy_qrnn_s_cross[alpha] = selected_model
    runtime_hours = (time.time() - level_start) / 3600
    summary_records.append({
        "alpha": alpha,
        "selected_trial": selected_trial.number,
        "validation_nll": selected_result["validation_nll"],
        "validation_crp": selected_result["validation_crp"],
        "validation_crp_penalty": selected_result[
            "validation_crp_penalty"
        ],
        "validation_hit_rate": selected_result["validation_hit_rate"],
        "beta1": selected_result["beta1"],
        "beta2": selected_result["beta2"],
        "beta3": selected_result["beta3"],
        "psi": selected_result["psi"],
        "sigma": selected_result["sigma"],
        "valid_trials": len(ranking_table),
        "runtime_hours": runtime_hours,
    })
    print("\nTop 10 rank-based trials:")
    print(ranking_table[[
        "trial", "validation_nll", "validation_crp",
        "validation_crp_penalty", "rank_nll", "rank_crp", "sum_rank",
    ]].head(10).to_string(index=False))
    print("\nSelected trial:", selected_trial.number)
    print("Validation NLL:", f"{selected_result['validation_nll']:.8f}")
    print("Validation CRP:", f"{selected_result['validation_crp']:.8f}")
    print("Ranking saved to:", ranking_path)
    print("Checkpoint saved to:", checkpoint_path)


summary_spy_qrnn_s_cross = pd.DataFrame(summary_records)
summary_path = OUTPUT_DIR / f"{MODEL_NAME}_tuning_summary.csv"
summary_spy_qrnn_s_cross.to_csv(summary_path, index=False)

config_path = OUTPUT_DIR / f"{MODEL_NAME}_selected_configs.json"
with open(config_path, "w") as configuration_file:
    json.dump(
        {f"{alpha:.3f}": config for alpha, config in best_configs_spy_qrnn_s_cross.items()},
        configuration_file,
        indent=2,
    )

print("\n" + "=" * 72)
print("SPY ORIGINAL TUNING COMPLETED:", MODEL_NAME)
print("=" * 72)
display(summary_spy_qrnn_s_cross)
print("Total runtime (hours):", f"{(time.time() - overall_start) / 3600:.3f}")
print("Summary saved to:", summary_path)
print("Selected configurations saved to:", config_path)

[I 2026-09-14 14:12:28,643] A new study created in memory with name: spy_qrnn_s_cross_alpha_0.025

Model: spy_qrnn_s_cross
Output directory: /Users/miaomiaochen/Desktop/PhD program/Project 1/spy_original_tuning_results/spy_qrnn_s_cross

========================================================================
Tuning spy_qrnn_s_cross at alpha=0.025
Trials=200 | sampler seed=2026
========================================================================

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-09-14 14:12:47,001] Trial 0 finished with value: 3.621666431427002 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.49377524711883497, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0006552020421842752, 'optimizer': 'adam', 'weight_decay': 8.940884610144999e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 38}. Best is trial 0 with value: 3.621666431427002.
[I 2026-09-14 14:13:08,313] Trial 1 finished with value: 2.5747435092926025 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.07458356653667625, 'layernorm': False, 'weight_init': 'he', 'lr': 0.006969178688110181, 'optimizer': 'adam', 'weight_decay': 2.574006001095316e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 102}. Best is trial 1 with value: 2.5747435092926025.
[I 2026-09-14 14:13:10,387] Trial 2 finished with value: 3.6963376998901367 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.37112272198735796, 'layernorm': True, 'weight_init': 'he', 'lr': 0.00010150090104324205, 'optimizer': 'adam', 'weight_decay': 6.518207314586205e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 164}. Best is trial 1 with value: 2.5747435092926025.
[I 2026-09-14 14:13:35,640] Trial 3 finished with value: 3.438979148864746 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.08410371275195383, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0018347830260217095, 'optimizer': 'adamw', 'weight_decay': 1.0709415904194131e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 237}. Best is trial 1 with value: 2.5747435092926025.
[I 2026-09-14 14:13:57,241] Trial 4 finished with value: 3.069941520690918 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.04674566511461714, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.004179064253320389, 'optimizer': 'adam', 'weight_decay': 6.125656858808738e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 104}. Best is trial 1 with value: 2.5747435092926025.
[I 2026-09-14 14:13:59,608] Trial 5 finished with value: 3.7108254432678223 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.45911076747236795, 'layernorm': True, 'weight_init': 'he', 'lr': 0.0001416875352388753, 'optimizer': 'adam', 'weight_decay': 9.345394674549201e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 223, 'hidden_dim_1': 87}. Best is trial 1 with value: 2.5747435092926025.
[I 2026-09-14 14:14:02,228] Trial 6 finished with value: 3.7096779346466064 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.38970064512862934, 'layernorm': True, 'weight_init': 'he', 'lr': 0.0006254792571683692, 'optimizer': 'adamw', 'weight_decay': 6.801313798751197e-05, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 218, 'hidden_dim_1': 178}. Best is trial 1 with value: 2.5747435092926025.
[I 2026-09-14 14:14:07,200] Trial 7 finished with value: 3.6960840225219727 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.36032432475263065, 'layernorm': True, 'weight_init': 'he', 'lr': 0.00020173841324002415, 'optimizer': 'adam', 'weight_decay': 4.1767279869402754e-05, 'gradient_clip': 0.1, 'patience': 30, 'hidden_dim_0': 154, 'hidden_dim_1': 109}. Best is trial 1 with value: 2.5747435092926025.
[I 2026-09-14 14:14:08,671] Trial 8 finished with value: 3.693678617477417 and parameters: {'n_hidden_layers': 3, 'activation': 'relu', 'dropout': 0.4362763457742629, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0005717356849949265, 'optimizer': 'adamw', 'weight_decay': 9.916771691263823e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 79, 'hidden_dim_1': 56, 'hidden_dim_2': 37}. Best is trial 1 with value: 2.5747435092926025.
[I 2026-09-14 14:14:11,524] Trial 9 finished with value: 3.6905877590179443 and parameters: {'n_hidden_layers': 3, 'activation': 'relu', 'dropout': 0.013151451801451775, 'layernorm': False, 'weight_init': 'he', 'lr': 0.00012716878126572782, 'optimizer': 'adam', 'weight_decay': 1.9095096534588543e-05, 'gradient_clip': 1.0, 'patience': 10, 'hidden_dim_0': 51, 'hidden_dim_1': 132, 'hidden_dim_2': 126}. Best is trial 1 with value: 2.5747435092926025.
[I 2026-09-14 14:14:35,000] Trial 10 finished with value: -3.152611017227173 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.15097474024909283, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.037908135375982255, 'optimizer': 'adamw', 'weight_decay': 3.1379335590221484e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 119}. Best is trial 10 with value: -3.152611017227173.
[I 2026-09-14 14:14:55,479] Trial 11 finished with value: -2.7086806297302246 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.16366513375091546, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.03402526330326022, 'optimizer': 'adamw', 'weight_decay': 3.117485972962536e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 121}. Best is trial 10 with value: -3.152611017227173.
[I 2026-09-14 14:15:15,618] Trial 12 finished with value: -3.5744409561157227 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.19279633488923958, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.046620580362009216, 'optimizer': 'adamw', 'weight_decay': 3.4990129609403785e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 128}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:15:39,230] Trial 13 finished with value: -2.646056890487671 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.23786332849750252, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.04229974646761679, 'optimizer': 'adamw', 'weight_decay': 4.3634634603570556e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 192, 'hidden_dim_1': 239}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:16:00,265] Trial 14 finished with value: 0.6415412425994873 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.17542264147037007, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.016247339371683493, 'optimizer': 'adamw', 'weight_decay': 7.599168284062825e-07, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 132}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:16:22,474] Trial 15 finished with value: 0.704182505607605 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.2754717932164122, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.016198403756051395, 'optimizer': 'adamw', 'weight_decay': 3.6091669365685415e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 180, 'hidden_dim_1': 242}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:16:40,795] Trial 16 finished with value: 0.43779227137565613 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.17042674969881644, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.01725021139952443, 'optimizer': 'adamw', 'weight_decay': 4.984887925511083e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 75}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:17:04,069] Trial 17 finished with value: -2.6409547328948975 and parameters: {'n_hidden_layers': 3, 'activation': 'tanh', 'dropout': 0.28403198494904347, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.046646192138245494, 'optimizer': 'adamw', 'weight_decay': 1.3722887436408784e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 143, 'hidden_dim_1': 180, 'hidden_dim_2': 249}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:17:23,239] Trial 18 finished with value: 2.541790246963501 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.11622355342152524, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.007540162647618844, 'optimizer': 'adamw', 'weight_decay': 5.638805838779985e-05, 'gradient_clip': 0.1, 'patience': 30, 'hidden_dim_0': 103, 'hidden_dim_1': 36}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:17:41,870] Trial 19 finished with value: 3.3600659370422363 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.21730471203723295, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.002361491930434552, 'optimizer': 'adamw', 'weight_decay': 7.443533388013251e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 74}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:18:02,776] Trial 20 finished with value: -1.0002944469451904 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.12294994945901927, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.02665004069440385, 'optimizer': 'adamw', 'weight_decay': 2.384435522984006e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 186, 'hidden_dim_1': 187}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:18:21,040] Trial 21 finished with value: -2.8028576374053955 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.17769929550418978, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.03385701823652554, 'optimizer': 'adamw', 'weight_decay': 3.173883413050123e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 124}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:18:43,099] Trial 22 finished with value: -0.6524108648300171 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.2139358939611884, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.022269765387671486, 'optimizer': 'adamw', 'weight_decay': 3.430166330891219e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 120}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:19:02,536] Trial 23 finished with value: 2.019047737121582 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.2968013747653401, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.009742581043231096, 'optimizer': 'adamw', 'weight_decay': 4.654281796155235e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 161}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:19:22,133] Trial 24 finished with value: 1.689509630203247 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.13962949400927063, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.011324775592540373, 'optimizer': 'adamw', 'weight_decay': 2.8055355272513846e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 134}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:19:41,179] Trial 25 finished with value: -3.443040132522583 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.3228354189479162, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.04801714730145811, 'optimizer': 'adamw', 'weight_decay': 3.7891125736284943e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 97}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:20:00,894] Trial 26 finished with value: -3.5341808795928955 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.33208086549744587, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.04755770856212327, 'optimizer': 'adamw', 'weight_decay': 1.6637959296164182e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 85}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:20:19,814] Trial 27 finished with value: 3.00868821144104 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.314646090041121, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.004553392003049117, 'optimizer': 'adamw', 'weight_decay': 2.467367891745566e-06, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 89}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:20:40,906] Trial 28 finished with value: -0.5923928618431091 and parameters: {'n_hidden_layers': 2, 'activation': 'relu', 'dropout': 0.41298130847894826, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.024354837941113976, 'optimizer': 'adamw', 'weight_decay': 1.7565674150104476e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 45, 'hidden_dim_1': 209}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:21:01,057] Trial 29 finished with value: -3.5732004642486572 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.3237854667552162, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.04723669561956735, 'optimizer': 'adamw', 'weight_decay': 7.780315809079073e-06, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 32}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:21:20,602] Trial 30 finished with value: 1.4455729722976685 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.3392209305147823, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.012430897785103543, 'optimizer': 'adamw', 'weight_decay': 4.403034592732811e-06, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 34}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:21:39,457] Trial 31 finished with value: -3.5064785480499268 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.3248802040677366, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.047916752060683694, 'optimizer': 'adamw', 'weight_decay': 1.050630683868547e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 55}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:21:58,471] Trial 32 finished with value: -1.3327407836914062 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.2576080072368222, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.026431922624427326, 'optimizer': 'adamw', 'weight_decay': 9.227570957849488e-06, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 51}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:22:16,103] Trial 33 finished with value: -3.4056403636932373 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.49167930576991786, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.04866843221060017, 'optimizer': 'adamw', 'weight_decay': 2.1680052175279396e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 64}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:22:34,914] Trial 34 finished with value: -0.4105552136898041 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.35189943128100143, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.021173853691452686, 'optimizer': 'adam', 'weight_decay': 1.0782030183975053e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 61}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:22:53,952] Trial 35 finished with value: -2.295905828475952 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.38155341502341117, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.03180407868580118, 'optimizer': 'adamw', 'weight_decay': 1.4891704349384834e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 40}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:22:55,119] Trial 36 finished with value: 3.6956818103790283 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.24605218173826565, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.004813620375630201, 'optimizer': 'adam', 'weight_decay': 7.289908603307072e-06, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 63}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:22:57,154] Trial 37 finished with value: 3.6913723945617676 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.310934369764591, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.000990708532822946, 'optimizer': 'adamw', 'weight_decay': 2.4686718294087736e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 89}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:23:15,569] Trial 38 finished with value: 2.28474497795105 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.2092941795181181, 'layernorm': True, 'weight_init': 'he', 'lr': 0.008392481729727513, 'optimizer': 'adam', 'weight_decay': 1.7072039204089338e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 57}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:23:35,133] Trial 39 finished with value: 1.093331217765808 and parameters: {'n_hidden_layers': 2, 'activation': 'relu', 'dropout': 0.406336725435686, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.014029975872995626, 'optimizer': 'adamw', 'weight_decay': 6.52002082222235e-06, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 39, 'hidden_dim_1': 145}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:23:55,025] Trial 40 finished with value: 3.3424556255340576 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.34381396275855347, 'layernorm': True, 'weight_init': 'he', 'lr': 0.0025347536779104438, 'optimizer': 'adamw', 'weight_decay': 1.2921436996394532e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 85, 'hidden_dim_1': 78}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:24:14,018] Trial 41 finished with value: -3.41375470161438 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.32663442302605405, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.04423860390069956, 'optimizer': 'adamw', 'weight_decay': 5.4927943070382045e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 106}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:24:33,531] Trial 42 finished with value: -2.2390036582946777 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.27372688391735855, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.03053302939811539, 'optimizer': 'adamw', 'weight_decay': 8.399296484642153e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 96}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:24:51,895] Trial 43 finished with value: -3.538889169692993 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.38201909442708476, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.04959687728450286, 'optimizer': 'adamw', 'weight_decay': 2.6981169472566953e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 69}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:24:52,995] Trial 44 finished with value: 3.70744252204895 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.44498697784482266, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.0002787496968119477, 'optimizer': 'adamw', 'weight_decay': 2.8246969618375537e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 255}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:25:11,389] Trial 45 finished with value: -2.824706792831421 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.3800354688730539, 'layernorm': True, 'weight_init': 'he', 'lr': 0.03552542846666567, 'optimizer': 'adam', 'weight_decay': 2.2131982022970475e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 72}. Best is trial 12 with value: -3.5744409561157227.
[I 2026-09-14 14:25:30,901] Trial 46 finished with value: -0.1341148018836975 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.36333684018525225, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.02240782468967625, 'optimizer': 'adamw', 'weight_decay': 4.034634342669814e-05, 'gradient_clip': 0.1, 'patience': 30, 'hidden_dim_0': 51}. Best is trial 12 with value: -3.5744409561157227.

[I 2026-09-14 15:17:06,180] A new study created in memory with name: spy_qrnn_s_cross_alpha_0.050

Top 10 rank-based trials:
 trial  validation_nll  validation_crp  validation_crp_penalty  rank_nll  rank_crp  sum_rank
   183       -3.815248        0.926316                0.005429         1        10        11
   192       -3.770140        0.926316                0.005429         6        11        17
    91       -3.728126        1.010526                0.000111        18         1        19
   198       -3.756759        0.926316                0.005429        10        12        22
   162       -3.763365        1.094737                0.008975         8        20        28
    75       -3.706465        0.926316                0.005429        29         8        37
    52       -3.724619        1.094737                0.008975        24        14        38
   107       -3.748166        0.842105                0.024931        13        26        39
   191       -3.693171        1.010526                0.000111        35         5        40
    72       -3.711775        1.094737                0.008975        27        17        44

Selected trial: 183
Validation NLL: -3.81524825
Validation CRP: 0.92631578
Ranking saved to: spy_original_tuning_results/spy_qrnn_s_cross/spy_qrnn_s_cross_ranking_alpha_0.025.csv
Checkpoint saved to: spy_original_tuning_results/spy_qrnn_s_cross/spy_qrnn_s_cross_best_alpha_0.025.pt

========================================================================
Tuning spy_qrnn_s_cross at alpha=0.050
Trials=200 | sampler seed=2027
========================================================================

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-09-14 15:17:31,289] Trial 0 finished with value: 2.8871026039123535 and parameters: {'n_hidden_layers': 3, 'activation': 'relu', 'dropout': 0.05498225107357002, 'layernorm': True, 'weight_init': 'he', 'lr': 0.001007193483885585, 'optimizer': 'adam', 'weight_decay': 5.273500806799822e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 146, 'hidden_dim_1': 251, 'hidden_dim_2': 82}. Best is trial 0 with value: 2.8871026039123535.
[I 2026-09-14 15:17:39,288] Trial 1 finished with value: 3.0244505405426025 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.025049491897366605, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.00015333527280501685, 'optimizer': 'adam', 'weight_decay': 1.7649100996182442e-05, 'gradient_clip': 0.1, 'patience': 30, 'hidden_dim_0': 55}. Best is trial 0 with value: 2.8871026039123535.
[I 2026-09-14 15:18:02,292] Trial 2 finished with value: -0.2286006361246109 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.40022516295292937, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.017828108789207167, 'optimizer': 'adamw', 'weight_decay': 4.256897134040472e-06, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 136, 'hidden_dim_1': 190}. Best is trial 2 with value: -0.2286006361246109.
[I 2026-09-14 15:18:21,888] Trial 3 finished with value: 1.5750752687454224 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.4906149686619623, 'layernorm': False, 'weight_init': 'he', 'lr': 0.008621938608035565, 'optimizer': 'adam', 'weight_decay': 3.0729486183155077e-06, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 98}. Best is trial 2 with value: -0.2286006361246109.
[I 2026-09-14 15:18:42,283] Trial 4 finished with value: -0.617540717124939 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.0623479532787809, 'layernorm': False, 'weight_init': 'he', 'lr': 0.020955780471493032, 'optimizer': 'adamw', 'weight_decay': 8.175143400839332e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 241}. Best is trial 4 with value: -0.617540717124939.
[I 2026-09-14 15:19:03,429] Trial 5 finished with value: 2.359355926513672 and parameters: {'n_hidden_layers': 2, 'activation': 'relu', 'dropout': 0.011881323908210506, 'layernorm': True, 'weight_init': 'he', 'lr': 0.004589621599355884, 'optimizer': 'adam', 'weight_decay': 8.749163991655252e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 43, 'hidden_dim_1': 83}. Best is trial 4 with value: -0.617540717124939.
[I 2026-09-14 15:19:05,481] Trial 6 finished with value: 3.0245702266693115 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.1197802920592731, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0002617502610814452, 'optimizer': 'adamw', 'weight_decay': 9.409600716806149e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 138, 'hidden_dim_1': 143, 'hidden_dim_2': 129}. Best is trial 4 with value: -0.617540717124939.
[I 2026-09-14 15:19:11,314] Trial 7 finished with value: 3.0435001850128174 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.14154848266700237, 'layernorm': True, 'weight_init': 'he', 'lr': 0.00035648317294578567, 'optimizer': 'adamw', 'weight_decay': 7.877310735173911e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 132, 'hidden_dim_1': 215}. Best is trial 4 with value: -0.617540717124939.
[I 2026-09-14 15:19:36,365] Trial 8 finished with value: 1.3448394536972046 and parameters: {'n_hidden_layers': 3, 'activation': 'relu', 'dropout': 0.11813572389419386, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.00997390293260971, 'optimizer': 'adam', 'weight_decay': 2.970971168033766e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 49, 'hidden_dim_1': 97, 'hidden_dim_2': 239}. Best is trial 4 with value: -0.617540717124939.
[I 2026-09-14 15:20:01,953] Trial 9 finished with value: 2.6496422290802 and parameters: {'n_hidden_layers': 3, 'activation': 'tanh', 'dropout': 0.10870062798473645, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.002659841143325214, 'optimizer': 'adamw', 'weight_decay': 1.4264804986270363e-07, 'gradient_clip': 1.0, 'patience': 10, 'hidden_dim_0': 66, 'hidden_dim_1': 209, 'hidden_dim_2': 232}. Best is trial 4 with value: -0.617540717124939.
[I 2026-09-14 15:20:24,012] Trial 10 finished with value: -3.852684497833252 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.256769197132948, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04996707562652885, 'optimizer': 'adamw', 'weight_decay': 6.285399164875321e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 253}. Best is trial 10 with value: -3.852684497833252.
[I 2026-09-14 15:20:48,106] Trial 11 finished with value: -3.6704139709472656 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.26896687967141275, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0413804237138205, 'optimizer': 'adamw', 'weight_decay': 6.402777845486389e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 256}. Best is trial 10 with value: -3.852684497833252.
[I 2026-09-14 15:21:08,475] Trial 12 finished with value: -3.8403310775756836 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.2662277603250139, 'layernorm': False, 'weight_init': 'he', 'lr': 0.048502724196620786, 'optimizer': 'adamw', 'weight_decay': 6.195759754591005e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 254}. Best is trial 10 with value: -3.852684497833252.
[I 2026-09-14 15:21:29,944] Trial 13 finished with value: -3.8209033012390137 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.26213438123078076, 'layernorm': False, 'weight_init': 'he', 'lr': 0.049592204253433435, 'optimizer': 'adamw', 'weight_decay': 6.455546555174494e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 210}. Best is trial 10 with value: -3.852684497833252.
[I 2026-09-14 15:21:51,827] Trial 14 finished with value: 2.968087911605835 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.34330886061646537, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0009283054569567131, 'optimizer': 'adamw', 'weight_decay': 4.618193538382704e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 206}. Best is trial 10 with value: -3.852684497833252.
[I 2026-09-14 15:22:13,647] Trial 15 finished with value: -1.0076826810836792 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.20133274810836993, 'layernorm': False, 'weight_init': 'he', 'lr': 0.025173870752998047, 'optimizer': 'adamw', 'weight_decay': 4.370056763788798e-05, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 210, 'hidden_dim_1': 40}. Best is trial 10 with value: -3.852684497833252.
[I 2026-09-14 15:22:33,692] Trial 16 finished with value: 1.3198474645614624 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.3231415327501519, 'layernorm': False, 'weight_init': 'he', 'lr': 0.010786535287149115, 'optimizer': 'adamw', 'weight_decay': 6.894329086168082e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 175}. Best is trial 10 with value: -3.852684497833252.
[I 2026-09-14 15:22:57,248] Trial 17 finished with value: 2.523254632949829 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.3960820341577769, 'layernorm': False, 'weight_init': 'he', 'lr': 0.00352725511885507, 'optimizer': 'adamw', 'weight_decay': 3.506050121644803e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 235, 'hidden_dim_1': 155}. Best is trial 10 with value: -3.852684497833252.
[I 2026-09-14 15:23:18,057] Trial 18 finished with value: 2.94490647315979 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.19848817369539148, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.001102634182388153, 'optimizer': 'adamw', 'weight_decay': 5.605490413549919e-05, 'gradient_clip': 0.1, 'patience': 30, 'hidden_dim_0': 188}. Best is trial 10 with value: -3.852684497833252.
[I 2026-09-14 15:23:19,464] Trial 19 finished with value: 3.021838426589966 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.19847621597850756, 'layernorm': False, 'weight_init': 'he', 'lr': 0.005830743635560729, 'optimizer': 'adamw', 'weight_decay': 7.113899612624308e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 234}. Best is trial 10 with value: -3.852684497833252.
[I 2026-09-14 15:23:41,020] Trial 20 finished with value: -1.5325599908828735 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.2889798331834716, 'layernorm': False, 'weight_init': 'he', 'lr': 0.02851346620861953, 'optimizer': 'adamw', 'weight_decay': 9.960034849866e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 174, 'hidden_dim_1': 35}. Best is trial 10 with value: -3.852684497833252.
[I 2026-09-14 15:24:01,440] Trial 21 finished with value: -3.396111249923706 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.22783976071962292, 'layernorm': False, 'weight_init': 'he', 'lr': 0.03883049768101141, 'optimizer': 'adamw', 'weight_decay': 5.8974599291882336e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 216}. Best is trial 10 with value: -3.852684497833252.
[I 2026-09-14 15:24:23,107] Trial 22 finished with value: -3.8475749492645264 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.2983373525502464, 'layernorm': False, 'weight_init': 'he', 'lr': 0.048055686448552945, 'optimizer': 'adamw', 'weight_decay': 7.370103919226658e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 251}. Best is trial 10 with value: -3.852684497833252.
[I 2026-09-14 15:24:45,200] Trial 23 finished with value: 0.41246047616004944 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.35141321602392817, 'layernorm': False, 'weight_init': 'he', 'lr': 0.015629743889327866, 'optimizer': 'adamw', 'weight_decay': 7.24033308542827e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 252}. Best is trial 10 with value: -3.852684497833252.
[I 2026-09-14 15:25:11,016] Trial 24 finished with value: -3.8558714389801025 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.30021261036959773, 'layernorm': False, 'weight_init': 'he', 'lr': 0.049833677606678006, 'optimizer': 'adamw', 'weight_decay': 7.759522126789488e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 227}. Best is trial 24 with value: -3.8558714389801025.
[I 2026-09-14 15:25:34,631] Trial 25 finished with value: -1.4378294944763184 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.39173192609521224, 'layernorm': False, 'weight_init': 'he', 'lr': 0.028532595031499592, 'optimizer': 'adamw', 'weight_decay': 8.32963212886707e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 228, 'hidden_dim_1': 109}. Best is trial 24 with value: -3.8558714389801025.
[I 2026-09-14 15:25:54,635] Trial 26 finished with value: -0.16170085966587067 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.3077476335301386, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.018983864330030433, 'optimizer': 'adam', 'weight_decay': 7.679796204483159e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 193}. Best is trial 24 with value: -3.8558714389801025.
[I 2026-09-14 15:26:15,062] Trial 27 finished with value: 0.6939082145690918 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.48603127277039926, 'layernorm': False, 'weight_init': 'he', 'lr': 0.014681748773164728, 'optimizer': 'adamw', 'weight_decay': 9.406204854079075e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 226}. Best is trial 24 with value: -3.8558714389801025.
[I 2026-09-14 15:26:38,810] Trial 28 finished with value: 1.9793922901153564 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.4401995767640237, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0063671753934192755, 'optimizer': 'adamw', 'weight_decay': 8.718710012608654e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 168, 'hidden_dim_1': 255}. Best is trial 24 with value: -3.8558714389801025.
[I 2026-09-14 15:26:39,884] Trial 29 finished with value: 3.031590700149536 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.24083760376797891, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0014334512638802684, 'optimizer': 'adam', 'weight_decay': 5.123011570367748e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 108}. Best is trial 24 with value: -3.8558714389801025.
[I 2026-09-14 15:27:00,604] Trial 30 finished with value: -3.3940517902374268 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.35892206094776274, 'layernorm': False, 'weight_init': 'he', 'lr': 0.03429755364613739, 'optimizer': 'adamw', 'weight_decay': 3.901849810514477e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 194}. Best is trial 24 with value: -3.8558714389801025.
[I 2026-09-14 15:27:21,473] Trial 31 finished with value: -3.805668830871582 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.28710325083897315, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04754860752433765, 'optimizer': 'adamw', 'weight_decay': 6.127458118421253e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 249}. Best is trial 24 with value: -3.8558714389801025.
[I 2026-09-14 15:27:42,114] Trial 32 finished with value: -2.29109787940979 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.22892538789350297, 'layernorm': False, 'weight_init': 'he', 'lr': 0.030014339682689097, 'optimizer': 'adamw', 'weight_decay': 5.36399029886296e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 244}. Best is trial 24 with value: -3.8558714389801025.
[I 2026-09-14 15:28:03,558] Trial 33 finished with value: -3.90312123298645 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.1603885435294234, 'layernorm': False, 'weight_init': 'he', 'lr': 0.049759451708002035, 'optimizer': 'adamw', 'weight_decay': 7.370643655141297e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 256}. Best is trial 33 with value: -3.90312123298645.
[I 2026-09-14 15:28:24,553] Trial 34 finished with value: 0.9216001033782959 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.18170549696050708, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.012817033476865204, 'optimizer': 'adam', 'weight_decay': 7.553058947097822e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 222}. Best is trial 33 with value: -3.90312123298645.
[I 2026-09-14 15:28:45,112] Trial 35 finished with value: -0.9342302083969116 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.31432968543939566, 'layernorm': False, 'weight_init': 'he', 'lr': 0.02262277704021655, 'optimizer': 'adamw', 'weight_decay': 6.704003194664719e-05, 'gradient_clip': 0.1, 'patience': 30, 'hidden_dim_0': 239}. Best is trial 33 with value: -3.90312123298645.
[I 2026-09-14 15:28:47,669] Trial 36 finished with value: 3.024933099746704 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.16131152592094491, 'layernorm': False, 'weight_init': 'he', 'lr': 0.00011324449615758977, 'optimizer': 'adamw', 'weight_decay': 8.600140456715906e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 256, 'hidden_dim_1': 152}. Best is trial 33 with value: -3.90312123298645.
[I 2026-09-14 15:29:09,718] Trial 37 finished with value: -0.3321959376335144 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.06535508162490339, 'layernorm': True, 'weight_init': 'he', 'lr': 0.02003304395600928, 'optimizer': 'adam', 'weight_decay': 7.988334969462865e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 158}. Best is trial 33 with value: -3.90312123298645.
[I 2026-09-14 15:29:30,433] Trial 38 finished with value: -2.5631797313690186 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.3738896461655035, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.03372820240123826, 'optimizer': 'adamw', 'weight_decay': 1.1047406452074801e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 240}. Best is trial 33 with value: -3.90312123298645.
[I 2026-09-14 15:29:34,235] Trial 39 finished with value: 3.032498359680176 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.42595730280483357, 'layernorm': True, 'weight_init': 'he', 'lr': 0.0004615740729006471, 'optimizer': 'adamw', 'weight_decay': 7.402665289371306e-05, 'gradient_clip': 0.1, 'patience': 30, 'hidden_dim_0': 200, 'hidden_dim_1': 60}. Best is trial 33 with value: -3.90312123298645.
[I 2026-09-14 15:29:54,491] Trial 40 finished with value: 1.6637343168258667 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.1505380331206641, 'layernorm': False, 'weight_init': 'he', 'lr': 0.008243106818205012, 'optimizer': 'adam', 'weight_decay': 9.224124183552628e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 222}. Best is trial 33 with value: -3.90312123298645.
[I 2026-09-14 15:30:15,031] Trial 41 finished with value: -3.831416606903076 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.25728095155878977, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04651696609743372, 'optimizer': 'adamw', 'weight_decay': 6.13196751805436e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 242}. Best is trial 33 with value: -3.90312123298645.
[I 2026-09-14 15:30:35,291] Trial 42 finished with value: -3.7667436599731445 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.2847090553690502, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04944434908344222, 'optimizer': 'adamw', 'weight_decay': 6.928137161304387e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 256}. Best is trial 33 with value: -3.90312123298645.
[I 2026-09-14 15:30:55,240] Trial 43 finished with value: -1.158820390701294 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.23314060688069504, 'layernorm': False, 'weight_init': 'he', 'lr': 0.023740057374634478, 'optimizer': 'adamw', 'weight_decay': 5.669686955893896e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 229}. Best is trial 33 with value: -3.90312123298645.
[I 2026-09-14 15:31:14,085] Trial 44 finished with value: -3.0243678092956543 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.32682940825803053, 'layernorm': False, 'weight_init': 'he', 'lr': 0.03738308521852752, 'optimizer': 'adamw', 'weight_decay': 6.505224024437492e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 32}. Best is trial 33 with value: -3.90312123298645.
[I 2026-09-14 15:31:15,372] Trial 45 finished with value: 3.0242998600006104 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.09981428696924272, 'layernorm': False, 'weight_init': 'he', 'lr': 0.01889046963806489, 'optimizer': 'adamw', 'weight_decay': 8.179176471630547e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 244}. Best is trial 33 with value: -3.90312123298645.
[I 2026-09-14 15:31:35,497] Trial 46 finished with value: -2.5087640285491943 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.27173259838466424, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.03642740724172102, 'optimizer': 'adamw', 'weight_decay': 2.3096556209313037e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 115}. Best is trial 33 with value: -3.90312123298645.

[I 2026-09-14 16:21:56,056] A new study created in memory with name: spy_qrnn_s_cross_alpha_0.250

Top 10 rank-based trials:
 trial  validation_nll  validation_crp  validation_crp_penalty  rank_nll  rank_crp  sum_rank
    33       -3.903121        1.010526                0.000111         8         1         9
   182       -3.914011        0.968421                0.000997         4        10        14
   133       -3.907068        0.926316                0.005429         5        20        25
   113       -3.872815        1.010526                0.000111        22         3        25
    61       -3.958892        1.094737                0.008975         1        25        26
    52       -3.902766        0.926316                0.005429         9        19        28
    95       -3.869423        1.010526                0.000111        27         2        29
   123       -3.870690        1.010526                0.000111        26         4        30
   183       -3.886719        0.926316                0.005429        13        22        35
   181       -3.858797        1.010526                0.000111        32         6        38

Selected trial: 33
Validation NLL: -3.90312123
Validation CRP: 1.01052634
Ranking saved to: spy_original_tuning_results/spy_qrnn_s_cross/spy_qrnn_s_cross_ranking_alpha_0.050.csv
Checkpoint saved to: spy_original_tuning_results/spy_qrnn_s_cross/spy_qrnn_s_cross_best_alpha_0.050.pt

========================================================================
Tuning spy_qrnn_s_cross at alpha=0.250
Trials=200 | sampler seed=2028
========================================================================

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-09-14 16:22:01,816] Trial 0 finished with value: 1.651132583618164 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.16735790150049712, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.00021817327615682693, 'optimizer': 'adamw', 'weight_decay': 1.8728142576828257e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 153}. Best is trial 0 with value: 1.651132583618164.
[I 2026-09-14 16:22:22,830] Trial 1 finished with value: -0.7718679308891296 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.16523551215002763, 'layernorm': True, 'weight_init': 'he', 'lr': 0.03513192693765672, 'optimizer': 'adam', 'weight_decay': 8.393147658894028e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 151, 'hidden_dim_1': 164}. Best is trial 1 with value: -0.7718679308891296.
[I 2026-09-14 16:22:42,060] Trial 2 finished with value: 1.0605617761611938 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.40467624618546233, 'layernorm': True, 'weight_init': 'he', 'lr': 0.004998926730458613, 'optimizer': 'adam', 'weight_decay': 9.677061342631243e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 205}. Best is trial 1 with value: -0.7718679308891296.
[I 2026-09-14 16:22:47,220] Trial 3 finished with value: 1.673518180847168 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.13929427762702068, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0001717675806228961, 'optimizer': 'adam', 'weight_decay': 2.3464876409463944e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 209}. Best is trial 1 with value: -0.7718679308891296.
[I 2026-09-14 16:22:51,468] Trial 4 finished with value: 1.6795122623443604 and parameters: {'n_hidden_layers': 3, 'activation': 'relu', 'dropout': 0.41708117020410185, 'layernorm': True, 'weight_init': 'he', 'lr': 0.00014529179343189966, 'optimizer': 'adamw', 'weight_decay': 3.72599213953136e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 165, 'hidden_dim_1': 210, 'hidden_dim_2': 63}. Best is trial 1 with value: -0.7718679308891296.
[I 2026-09-14 16:23:10,332] Trial 5 finished with value: 1.5108166933059692 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.01524985411289953, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0010580394795166419, 'optimizer': 'adamw', 'weight_decay': 3.214851640707384e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 157}. Best is trial 1 with value: -0.7718679308891296.
[I 2026-09-14 16:23:32,093] Trial 6 finished with value: -3.010249614715576 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.32662396314728465, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.030716901443002907, 'optimizer': 'adam', 'weight_decay': 5.1538718916548065e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 221, 'hidden_dim_1': 136, 'hidden_dim_2': 57}. Best is trial 6 with value: -3.010249614715576.
[I 2026-09-14 16:23:54,326] Trial 7 finished with value: 1.4295700788497925 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.31595813340701023, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.0014904732749482215, 'optimizer': 'adamw', 'weight_decay': 8.180408818357401e-05, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 191, 'hidden_dim_1': 205}. Best is trial 6 with value: -3.010249614715576.
[I 2026-09-14 16:24:13,098] Trial 8 finished with value: 0.9143683314323425 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.20774298026688887, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.005008299917705367, 'optimizer': 'adam', 'weight_decay': 4.875430436862313e-05, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 71}. Best is trial 6 with value: -3.010249614715576.
[I 2026-09-14 16:24:34,052] Trial 9 finished with value: -0.38157927989959717 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.48533031232141854, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.012045452763888867, 'optimizer': 'adamw', 'weight_decay': 2.0628115673203342e-05, 'gradient_clip': 0.1, 'patience': 30, 'hidden_dim_0': 141, 'hidden_dim_1': 152, 'hidden_dim_2': 38}. Best is trial 6 with value: -3.010249614715576.
[I 2026-09-14 16:24:54,361] Trial 10 finished with value: -3.239224910736084 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.30595792806861905, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.04781539871558882, 'optimizer': 'adam', 'weight_decay': 2.010941659325747e-06, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 247, 'hidden_dim_1': 38, 'hidden_dim_2': 235}. Best is trial 10 with value: -3.239224910736084.
[I 2026-09-14 16:25:16,834] Trial 11 finished with value: -3.235997200012207 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.30078549308066116, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.041741128744992174, 'optimizer': 'adam', 'weight_decay': 3.242855805192148e-06, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 255, 'hidden_dim_1': 39, 'hidden_dim_2': 255}. Best is trial 10 with value: -3.239224910736084.
[I 2026-09-14 16:25:36,192] Trial 12 finished with value: -3.626270055770874 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.2868792687715407, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.045427396401161314, 'optimizer': 'adam', 'weight_decay': 2.473756606621607e-06, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 256, 'hidden_dim_1': 35, 'hidden_dim_2': 254}. Best is trial 12 with value: -3.626270055770874.
[I 2026-09-14 16:25:56,395] Trial 13 finished with value: -0.5970159769058228 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.26466809135995795, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.012590943740618728, 'optimizer': 'adam', 'weight_decay': 1.5555150371632652e-06, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 244, 'hidden_dim_1': 33}. Best is trial 12 with value: -3.626270055770874.
[I 2026-09-14 16:26:18,133] Trial 14 finished with value: -0.2053736448287964 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.38102046293742, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.010766783970622654, 'optimizer': 'adam', 'weight_decay': 8.204526166929023e-06, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 95, 'hidden_dim_1': 82, 'hidden_dim_2': 253}. Best is trial 12 with value: -3.626270055770874.
[I 2026-09-14 16:26:40,920] Trial 15 finished with value: 1.5890101194381714 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.24192970678278353, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.0004661129989048314, 'optimizer': 'adam', 'weight_decay': 6.047361246930141e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 235, 'hidden_dim_1': 88, 'hidden_dim_2': 195}. Best is trial 12 with value: -3.626270055770874.
[I 2026-09-14 16:26:59,954] Trial 16 finished with value: 1.070337176322937 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.10527973277402397, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.0039459121488176156, 'optimizer': 'adam', 'weight_decay': 1.2466172389554694e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 37, 'hidden_dim_1': 77}. Best is trial 12 with value: -3.626270055770874.
[I 2026-09-14 16:27:22,137] Trial 17 finished with value: -1.6587181091308594 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.49625356781327257, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.017927351539958745, 'optimizer': 'adam', 'weight_decay': 3.2964649225982746e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 181, 'hidden_dim_1': 62, 'hidden_dim_2': 190}. Best is trial 12 with value: -3.626270055770874.
[I 2026-09-14 16:27:46,312] Trial 18 finished with value: -2.76570987701416 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.35619363300141677, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.02493977850914521, 'optimizer': 'adam', 'weight_decay': 6.962930266812125e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 255, 'hidden_dim_1': 254}. Best is trial 12 with value: -3.626270055770874.
[I 2026-09-14 16:28:09,040] Trial 19 finished with value: 0.4497077167034149 and parameters: {'n_hidden_layers': 3, 'activation': 'relu', 'dropout': 0.2552022215879973, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.007863853358098359, 'optimizer': 'adam', 'weight_decay': 3.892354424549105e-07, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 226, 'hidden_dim_1': 120, 'hidden_dim_2': 198}. Best is trial 12 with value: -3.626270055770874.
[I 2026-09-14 16:28:29,102] Trial 20 finished with value: -4.090570449829102 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.4335805675911216, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.048963690845807185, 'optimizer': 'adam', 'weight_decay': 4.317767513375096e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 116, 'hidden_dim_1': 106}. Best is trial 20 with value: -4.090570449829102.
[I 2026-09-14 16:28:48,944] Trial 21 finished with value: -4.094137191772461 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.45441606088188674, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.047173731896252055, 'optimizer': 'adam', 'weight_decay': 1.186726929611483e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 118, 'hidden_dim_1': 110}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:29:08,947] Trial 22 finished with value: -2.2211287021636963 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.4538118589479474, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.02072872388684517, 'optimizer': 'adam', 'weight_decay': 4.336608965231927e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 113, 'hidden_dim_1': 111}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:29:29,296] Trial 23 finished with value: -2.105616569519043 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.4404920478415355, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.020088071505378922, 'optimizer': 'adam', 'weight_decay': 1.3530173749460772e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 124, 'hidden_dim_1': 109}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:29:49,590] Trial 24 finished with value: -3.9816038608551025 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.3742799597615383, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.03727879205169217, 'optimizer': 'adam', 'weight_decay': 2.9738276028281458e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 86, 'hidden_dim_1': 170}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:30:09,488] Trial 25 finished with value: 1.2494359016418457 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.3640639809561668, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.002828005327938672, 'optimizer': 'adam', 'weight_decay': 2.6251240561623813e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 81, 'hidden_dim_1': 174}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:30:29,486] Trial 26 finished with value: 0.39324185252189636 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.4511998049425075, 'layernorm': True, 'weight_init': 'he', 'lr': 0.007461937577443341, 'optimizer': 'adamw', 'weight_decay': 3.985400421555206e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 62, 'hidden_dim_1': 133}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:30:48,899] Trial 27 finished with value: -2.9167845249176025 and parameters: {'n_hidden_layers': 2, 'activation': 'relu', 'dropout': 0.40901458946368235, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.02664054210472389, 'optimizer': 'adam', 'weight_decay': 5.817651597274587e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 108, 'hidden_dim_1': 173}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:31:09,491] Trial 28 finished with value: -3.9870529174804688 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.467545490884239, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.04995749277359545, 'optimizer': 'adam', 'weight_decay': 2.930060443357519e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 130, 'hidden_dim_1': 209}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:31:10,980] Trial 29 finished with value: 1.6516869068145752 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.47354648143465317, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.00031681197572734984, 'optimizer': 'adamw', 'weight_decay': 1.746894410102633e-05, 'gradient_clip': 1.0, 'patience': 10, 'hidden_dim_0': 133}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:31:31,943] Trial 30 finished with value: -1.0663366317749023 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.49696299860659987, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.015982193173939944, 'optimizer': 'adam', 'weight_decay': 4.496960649250623e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 109, 'hidden_dim_1': 243}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:31:52,007] Trial 31 finished with value: -3.9707236289978027 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.4101726850512474, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.04622860495331982, 'optimizer': 'adam', 'weight_decay': 2.7254867763161133e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 92, 'hidden_dim_1': 194}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:32:12,706] Trial 32 finished with value: -3.399083137512207 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.4367718200931033, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.0306424094614529, 'optimizer': 'adam', 'weight_decay': 3.1123783384619666e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 124, 'hidden_dim_1': 220}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:32:32,776] Trial 33 finished with value: -2.5495858192443848 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.37699544210266156, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.03225735856099385, 'optimizer': 'adam', 'weight_decay': 1.7670346400609198e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 56, 'hidden_dim_1': 190}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:32:53,640] Trial 34 finished with value: -2.2918922901153564 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.34047979078209323, 'layernorm': True, 'weight_init': 'he', 'lr': 0.0499770430958953, 'optimizer': 'adam', 'weight_decay': 3.698293837735015e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 90, 'hidden_dim_1': 228}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:33:13,325] Trial 35 finished with value: -2.4721767902374268 and parameters: {'n_hidden_layers': 2, 'activation': 'relu', 'dropout': 0.3927530388244033, 'layernorm': False, 'weight_init': 'he', 'lr': 0.031078460214701082, 'optimizer': 'adam', 'weight_decay': 5.3961502955349976e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 172, 'hidden_dim_1': 98}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:33:32,632] Trial 36 finished with value: -1.1229461431503296 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.46791147598739863, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.015962349840014472, 'optimizer': 'adam', 'weight_decay': 2.5101222691426218e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 149}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:33:52,842] Trial 37 finished with value: 1.5348727703094482 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.42840725356376214, 'layernorm': False, 'weight_init': 'he', 'lr': 0.007655693856087421, 'optimizer': 'adamw', 'weight_decay': 9.939883500640068e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 128, 'hidden_dim_1': 152}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:34:11,930] Trial 38 finished with value: 1.6555625200271606 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.4664383774473939, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.00011165535285824409, 'optimizer': 'adam', 'weight_decay': 3.510875872158045e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 103, 'hidden_dim_1': 166}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:34:30,471] Trial 39 finished with value: -2.869374990463257 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.402205257281704, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.024091924105544466, 'optimizer': 'adam', 'weight_decay': 4.271338825030595e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 78}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:34:49,029] Trial 40 finished with value: 1.6016417741775513 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.017843285278107968, 'layernorm': False, 'weight_init': 'he', 'lr': 0.000738306252637811, 'optimizer': 'adamw', 'weight_decay': 6.488268268593921e-05, 'gradient_clip': 0.1, 'patience': 30, 'hidden_dim_0': 139}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:35:09,249] Trial 41 finished with value: -3.700509786605835 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.415509667312996, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.03719423929109089, 'optimizer': 'adam', 'weight_decay': 2.7404409283906277e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 94, 'hidden_dim_1': 190}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:35:30,889] Trial 42 finished with value: -3.5814883708953857 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.34839903485045026, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.036975864262590315, 'optimizer': 'adam', 'weight_decay': 2.220959271115196e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 157, 'hidden_dim_1': 198}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:35:51,114] Trial 43 finished with value: -3.956324338912964 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.42780525724764884, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.04860822142882342, 'optimizer': 'adam', 'weight_decay': 1.3346039228140248e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 118, 'hidden_dim_1': 183}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:36:10,755] Trial 44 finished with value: -3.5227267742156982 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.38440851845692997, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.03518267083468603, 'optimizer': 'adam', 'weight_decay': 2.860308931409227e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 86, 'hidden_dim_1': 132}. Best is trial 21 with value: -4.094137191772461.
[I 2026-09-14 16:36:31,079] Trial 45 finished with value: -2.5161185264587402 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.4591387702108828, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.026839167194160306, 'optimizer': 'adam', 'weight_decay': 5.026883725269913e-05, 'gradient_clip': 1.0, 'patience': 10, 'hidden_dim_0': 65, 'hidden_dim_1': 213}. Best is trial 21 with value: -4.094137191772461.

[I 2026-09-14 17:26:41,236] A new study created in memory with name: spy_qrnn_s_cross_alpha_0.500

Top 10 rank-based trials:
 trial  validation_nll  validation_crp  validation_crp_penalty  rank_nll  rank_crp  sum_rank
   107       -4.292467        1.018947                0.000359         7        11        18
    71       -4.277058        1.010526                0.000111        16         6        22
   132       -4.293138        0.968421                0.000997         6        17        23
   187       -4.267927        0.985263                0.000217        20         9        29
   193       -4.307364        0.934737                0.004259         2        30        32
   112       -4.279156        1.035789                0.001281        14        19        33
   128       -4.296613        1.069474                0.004827         5        31        36
   134       -4.283577        0.934737                0.004259         9        28        37
   164       -4.259218        1.018947                0.000359        32        12        44
   167       -4.244156        1.010526                0.000111        43         7        50

Selected trial: 107
Validation NLL: -4.29246664
Validation CRP: 1.01894736
Ranking saved to: spy_original_tuning_results/spy_qrnn_s_cross/spy_qrnn_s_cross_ranking_alpha_0.250.csv
Checkpoint saved to: spy_original_tuning_results/spy_qrnn_s_cross/spy_qrnn_s_cross_best_alpha_0.250.pt

========================================================================
Tuning spy_qrnn_s_cross at alpha=0.500
Trials=200 | sampler seed=2029
========================================================================

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-09-14 17:26:43,230] Trial 0 finished with value: 1.387371301651001 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.2759148998079755, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.007024831190142553, 'optimizer': 'adamw', 'weight_decay': 4.1560787907729995e-05, 'gradient_clip': 1.0, 'patience': 10, 'hidden_dim_0': 247}. Best is trial 0 with value: 1.387371301651001.
[I 2026-09-14 17:27:02,458] Trial 1 finished with value: -2.925395965576172 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.4187938977063561, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.03427756963192871, 'optimizer': 'adam', 'weight_decay': 6.657050304270963e-05, 'gradient_clip': 0.1, 'patience': 30, 'hidden_dim_0': 246}. Best is trial 1 with value: -2.925395965576172.
[I 2026-09-14 17:27:20,594] Trial 2 finished with value: -1.381179690361023 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.12720587027501107, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.01607032726653695, 'optimizer': 'adam', 'weight_decay': 5.1591837522709986e-05, 'gradient_clip': 1.0, 'patience': 10, 'hidden_dim_0': 83}. Best is trial 1 with value: -2.925395965576172.
[I 2026-09-14 17:27:22,767] Trial 3 finished with value: 1.4118866920471191 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.2767536628793943, 'layernorm': True, 'weight_init': 'he', 'lr': 0.0011548082694504728, 'optimizer': 'adam', 'weight_decay': 4.806793383069813e-05, 'gradient_clip': 1.0, 'patience': 10, 'hidden_dim_0': 105}. Best is trial 1 with value: -2.925395965576172.
[I 2026-09-14 17:27:40,502] Trial 4 finished with value: -4.007266044616699 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.4588268217204195, 'layernorm': False, 'weight_init': 'he', 'lr': 0.03145498089364558, 'optimizer': 'adamw', 'weight_decay': 8.755603397932516e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 68}. Best is trial 4 with value: -4.007266044616699.
[I 2026-09-14 17:28:02,042] Trial 5 finished with value: 0.8780222535133362 and parameters: {'n_hidden_layers': 3, 'activation': 'relu', 'dropout': 0.43020454186114854, 'layernorm': True, 'weight_init': 'he', 'lr': 0.0032880374198537435, 'optimizer': 'adamw', 'weight_decay': 5.104019255409577e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 202, 'hidden_dim_1': 50, 'hidden_dim_2': 237}. Best is trial 4 with value: -4.007266044616699.
[I 2026-09-14 17:28:23,428] Trial 6 finished with value: 1.326521635055542 and parameters: {'n_hidden_layers': 3, 'activation': 'relu', 'dropout': 0.24807197728715097, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.00028017991848010916, 'optimizer': 'adamw', 'weight_decay': 3.67396445552398e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 135, 'hidden_dim_1': 99, 'hidden_dim_2': 209}. Best is trial 4 with value: -4.007266044616699.
[I 2026-09-14 17:28:25,984] Trial 7 finished with value: 1.3855520486831665 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.2398019201221976, 'layernorm': True, 'weight_init': 'he', 'lr': 0.0004626453383191004, 'optimizer': 'adam', 'weight_decay': 2.9332959553440563e-05, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 217, 'hidden_dim_1': 90}. Best is trial 4 with value: -4.007266044616699.
[I 2026-09-14 17:28:28,632] Trial 8 finished with value: 1.384952425956726 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.40025174511509976, 'layernorm': False, 'weight_init': 'he', 'lr': 0.00031464186606354694, 'optimizer': 'adamw', 'weight_decay': 2.7627127682945754e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 253, 'hidden_dim_1': 86, 'hidden_dim_2': 79}. Best is trial 4 with value: -4.007266044616699.
[I 2026-09-14 17:28:48,454] Trial 9 finished with value: 0.5586382150650024 and parameters: {'n_hidden_layers': 2, 'activation': 'relu', 'dropout': 0.36581257631927877, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.006492817763150637, 'optimizer': 'adamw', 'weight_decay': 7.691886438393831e-05, 'gradient_clip': 0.1, 'patience': 30, 'hidden_dim_0': 126, 'hidden_dim_1': 130}. Best is trial 4 with value: -4.007266044616699.
[I 2026-09-14 17:29:09,117] Trial 10 finished with value: -3.7722530364990234 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.4904983739528276, 'layernorm': False, 'weight_init': 'he', 'lr': 0.03053426141638634, 'optimizer': 'adamw', 'weight_decay': 9.181360439097146e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 43, 'hidden_dim_1': 252}. Best is trial 4 with value: -4.007266044616699.
[I 2026-09-14 17:29:29,305] Trial 11 finished with value: -4.211493968963623 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.4961673833997236, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04261084386631357, 'optimizer': 'adamw', 'weight_decay': 9.982113464255559e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 35, 'hidden_dim_1': 252}. Best is trial 11 with value: -4.211493968963623.
[I 2026-09-14 17:29:48,345] Trial 12 finished with value: -4.2173051834106445 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.4980077391838991, 'layernorm': False, 'weight_init': 'he', 'lr': 0.047635200186820326, 'optimizer': 'adamw', 'weight_decay': 5.692269926181435e-07, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 32, 'hidden_dim_1': 255}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:30:08,292] Trial 13 finished with value: -0.6061983704566956 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.04667214740496872, 'layernorm': False, 'weight_init': 'he', 'lr': 0.011038818139096103, 'optimizer': 'adamw', 'weight_decay': 2.32000785681091e-06, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 41, 'hidden_dim_1': 254}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:30:29,316] Trial 14 finished with value: -3.7303826808929443 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.4980559012832221, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0461854369939696, 'optimizer': 'adamw', 'weight_decay': 5.795174597638793e-07, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 176, 'hidden_dim_1': 202}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:30:33,966] Trial 15 finished with value: 1.3703486919403076 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.35510037147289597, 'layernorm': False, 'weight_init': 'he', 'lr': 0.00010317680349525299, 'optimizer': 'adamw', 'weight_decay': 1.5121840734493376e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 69, 'hidden_dim_1': 195}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:30:54,446] Trial 16 finished with value: 1.0977283716201782 and parameters: {'n_hidden_layers': 3, 'activation': 'tanh', 'dropout': 0.17561405421567736, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0018883736562752271, 'optimizer': 'adamw', 'weight_decay': 6.240472688705086e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 103, 'hidden_dim_1': 206, 'hidden_dim_2': 35}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:31:14,042] Trial 17 finished with value: -1.755183458328247 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.3452249386620498, 'layernorm': False, 'weight_init': 'he', 'lr': 0.016491630064865263, 'optimizer': 'adamw', 'weight_decay': 1.8222129555147293e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 32, 'hidden_dim_1': 226}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:31:33,892] Trial 18 finished with value: -4.039543151855469 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.006520003078658243, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04989295149013581, 'optimizer': 'adam', 'weight_decay': 9.593882633283248e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 61, 'hidden_dim_1': 151}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:31:55,812] Trial 19 finished with value: 0.6717736124992371 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.3214825915073414, 'layernorm': False, 'weight_init': 'he', 'lr': 0.004460637276981811, 'optimizer': 'adamw', 'weight_decay': 7.984122174853073e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 156, 'hidden_dim_1': 167, 'hidden_dim_2': 156}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:32:16,065] Trial 20 finished with value: -1.8020966053009033 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.45362171104148474, 'layernorm': False, 'weight_init': 'he', 'lr': 0.019029153728687576, 'optimizer': 'adamw', 'weight_decay': 9.992141762911965e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 96, 'hidden_dim_1': 232}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:32:35,806] Trial 21 finished with value: -3.5943729877471924 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.06968248724517338, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04760051369003432, 'optimizer': 'adam', 'weight_decay': 9.621567004705897e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 62, 'hidden_dim_1': 175}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:32:59,457] Trial 22 finished with value: -2.17767071723938 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.010564733009769303, 'layernorm': False, 'weight_init': 'he', 'lr': 0.02447813343781215, 'optimizer': 'adam', 'weight_decay': 8.32349662794141e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 51, 'hidden_dim_1': 139}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:33:20,980] Trial 23 finished with value: -0.5536679029464722 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.19320391079791394, 'layernorm': False, 'weight_init': 'he', 'lr': 0.011061768492330573, 'optimizer': 'adam', 'weight_decay': 6.977044804648363e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 33, 'hidden_dim_1': 223}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:33:43,966] Trial 24 finished with value: -4.053606986999512 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.11883889092209302, 'layernorm': False, 'weight_init': 'he', 'lr': 0.044269717565638175, 'optimizer': 'adam', 'weight_decay': 5.887402034527084e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 83, 'hidden_dim_1': 256}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:34:04,397] Trial 25 finished with value: -0.6676867008209229 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.15858983560834122, 'layernorm': False, 'weight_init': 'he', 'lr': 0.01205953797603723, 'optimizer': 'adam', 'weight_decay': 5.692973732626376e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 81}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:34:28,826] Trial 26 finished with value: -3.109776496887207 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.11276679827939823, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.02654119476953692, 'optimizer': 'adam', 'weight_decay': 1.721278547474678e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 86, 'hidden_dim_1': 252, 'hidden_dim_2': 127}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:34:51,076] Trial 27 finished with value: 0.10321738570928574 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.4648206781878871, 'layernorm': False, 'weight_init': 'he', 'lr': 0.007529709665339846, 'optimizer': 'adamw', 'weight_decay': 7.355073446691984e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 52, 'hidden_dim_1': 238}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:35:13,625] Trial 28 finished with value: 1.1982426643371582 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.3939622604555988, 'layernorm': False, 'weight_init': 'he', 'lr': 0.001167809950879681, 'optimizer': 'adam', 'weight_decay': 9.731668770905396e-06, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 128, 'hidden_dim_1': 214}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:35:34,537] Trial 29 finished with value: 0.5563857555389404 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.3002467945519962, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.006513453131881546, 'optimizer': 'adamw', 'weight_decay': 4.200250807989377e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 52}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:35:56,920] Trial 30 finished with value: -1.681470513343811 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.21151725815272288, 'layernorm': False, 'weight_init': 'he', 'lr': 0.019994657353011817, 'optimizer': 'adamw', 'weight_decay': 3.3563848301807085e-05, 'gradient_clip': 1.0, 'patience': 10, 'hidden_dim_0': 114, 'hidden_dim_1': 187}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:36:19,728] Trial 31 finished with value: -4.007186412811279 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.0660855331955128, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04655676439066279, 'optimizer': 'adam', 'weight_decay': 8.866469745657173e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 67, 'hidden_dim_1': 256}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:36:41,966] Trial 32 finished with value: -3.9846205711364746 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.022386057197549436, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04792892193628362, 'optimizer': 'adam', 'weight_decay': 9.927446852264845e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 56, 'hidden_dim_1': 158}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:37:03,674] Trial 33 finished with value: -2.614422082901001 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.11469652149692595, 'layernorm': False, 'weight_init': 'he', 'lr': 0.03281967091188972, 'optimizer': 'adam', 'weight_decay': 6.359411821394654e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 75, 'hidden_dim_1': 118}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:37:25,008] Trial 34 finished with value: -2.1909868717193604 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.10475005296233574, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.02258833808403843, 'optimizer': 'adam', 'weight_decay': 9.136774439581069e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 90}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:37:45,735] Trial 35 finished with value: -0.8738246560096741 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.15139632858902036, 'layernorm': False, 'weight_init': 'he', 'lr': 0.013338994641810802, 'optimizer': 'adam', 'weight_decay': 8.478793251392102e-05, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 32}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:38:07,646] Trial 36 finished with value: -2.697510242462158 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.4290460366767833, 'layernorm': False, 'weight_init': 'he', 'lr': 0.037666822267280006, 'optimizer': 'adam', 'weight_decay': 4.438081426806662e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 156, 'hidden_dim_1': 34}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:38:30,908] Trial 37 finished with value: -0.9792260527610779 and parameters: {'n_hidden_layers': 2, 'activation': 'relu', 'dropout': 0.08536653976246923, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.02784879907243647, 'optimizer': 'adam', 'weight_decay': 5.920288019082911e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 45, 'hidden_dim_1': 239}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:38:51,470] Trial 38 finished with value: -3.434560775756836 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.2740787532013923, 'layernorm': False, 'weight_init': 'he', 'lr': 0.03747799591288749, 'optimizer': 'adam', 'weight_decay': 5.346178571549212e-05, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 77}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:39:17,353] Trial 39 finished with value: -0.1593398153781891 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.04062935128906903, 'layernorm': False, 'weight_init': 'he', 'lr': 0.009041750937720756, 'optimizer': 'adamw', 'weight_decay': 7.436134124223723e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 109, 'hidden_dim_1': 216, 'hidden_dim_2': 184}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:39:39,326] Trial 40 finished with value: -1.1161258220672607 and parameters: {'n_hidden_layers': 2, 'activation': 'relu', 'dropout': 0.0005513105595197076, 'layernorm': True, 'weight_init': 'he', 'lr': 0.015524105843404655, 'optimizer': 'adamw', 'weight_decay': 2.3852289577864036e-05, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 63, 'hidden_dim_1': 65}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:39:59,932] Trial 41 finished with value: -3.808163642883301 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.4611746796316755, 'layernorm': False, 'weight_init': 'he', 'lr': 0.030592066400432404, 'optimizer': 'adamw', 'weight_decay': 8.641440591676548e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 62}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:40:20,463] Trial 42 finished with value: -4.070237159729004 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.4726149238215192, 'layernorm': False, 'weight_init': 'he', 'lr': 0.03500223721936376, 'optimizer': 'adamw', 'weight_decay': 9.448018829277677e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 44}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:40:41,324] Trial 43 finished with value: -4.073972225189209 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.49781609828554935, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0372303567105305, 'optimizer': 'adamw', 'weight_decay': 9.341030223697411e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 39}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:41:01,682] Trial 44 finished with value: -2.7553658485412598 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.4804927425618383, 'layernorm': False, 'weight_init': 'he', 'lr': 0.02171959801964021, 'optimizer': 'adamw', 'weight_decay': 9.33340207024213e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 45}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:41:22,616] Trial 45 finished with value: -4.055028915405273 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.40513374043676054, 'layernorm': False, 'weight_init': 'he', 'lr': 0.03460572137928658, 'optimizer': 'adamw', 'weight_decay': 8.078764344866544e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 39}. Best is trial 12 with value: -4.2173051834106445.
[I 2026-09-14 17:41:43,599] Trial 46 finished with value: -3.843071460723877 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.4000869867797673, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.031491015469584424, 'optimizer': 'adamw', 'weight_decay': 8.082122616947782e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 233}. Best is trial 12 with value: -4.2173051834106445.

[I 2026-09-14 18:30:29,339] A new study created in memory with name: spy_qrnn_s_cross_alpha_0.750

Top 10 rank-based trials:
 trial  validation_nll  validation_crp  validation_crp_penalty  rank_nll  rank_crp  sum_rank
   188       -4.370070        0.985263                0.000217         7        14        21
   172       -4.362706        0.981053                0.000359        12        20        32
   170       -4.344680        1.006316                0.000040        23         9        32
   163       -4.382457        1.031579                0.000997         4        30        34
   192       -4.383747        0.960000                0.001600         3        37        40
   173       -4.364028        1.035789                0.001281        11        33        44
   153       -4.355944        1.027368                0.000749        16        28        44
   193       -4.389507        0.947368                0.002770         2        47        49
   131       -4.329461        1.014737                0.000217        34        16        50
   182       -4.333322        0.981053                0.000359        30        22        52

Selected trial: 188
Validation NLL: -4.37006950
Validation CRP: 0.98526317
Ranking saved to: spy_original_tuning_results/spy_qrnn_s_cross/spy_qrnn_s_cross_ranking_alpha_0.500.csv
Checkpoint saved to: spy_original_tuning_results/spy_qrnn_s_cross/spy_qrnn_s_cross_best_alpha_0.500.pt

========================================================================
Tuning spy_qrnn_s_cross at alpha=0.750
Trials=200 | sampler seed=2030
========================================================================

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-09-14 18:30:50,947] Trial 0 finished with value: 1.0423970222473145 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.11794446303511014, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.004456352949789044, 'optimizer': 'adam', 'weight_decay': 9.18884108501482e-05, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 171, 'hidden_dim_1': 72}. Best is trial 0 with value: 1.0423970222473145.
[I 2026-09-14 18:30:56,919] Trial 1 finished with value: 1.6812429428100586 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.030560119781983197, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.00010374739355459913, 'optimizer': 'adamw', 'weight_decay': 5.825305061215891e-06, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 106, 'hidden_dim_1': 96, 'hidden_dim_2': 171}. Best is trial 0 with value: 1.0423970222473145.
[I 2026-09-14 18:31:22,924] Trial 2 finished with value: 1.4124951362609863 and parameters: {'n_hidden_layers': 3, 'activation': 'relu', 'dropout': 0.12366464799285015, 'layernorm': True, 'weight_init': 'he', 'lr': 0.0017986964319211573, 'optimizer': 'adam', 'weight_decay': 6.479962277567599e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 198, 'hidden_dim_1': 188, 'hidden_dim_2': 142}. Best is trial 0 with value: 1.0423970222473145.
[I 2026-09-14 18:31:44,141] Trial 3 finished with value: 1.085731863975525 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.47075322566009137, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.0038488329492906656, 'optimizer': 'adamw', 'weight_decay': 3.354043176870869e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 140, 'hidden_dim_1': 73}. Best is trial 0 with value: 1.0423970222473145.
[I 2026-09-14 18:32:08,798] Trial 4 finished with value: 1.5331693887710571 and parameters: {'n_hidden_layers': 3, 'activation': 'tanh', 'dropout': 0.014904097544075123, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0016227273324551125, 'optimizer': 'adam', 'weight_decay': 9.841768793736445e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 246, 'hidden_dim_1': 97, 'hidden_dim_2': 232}. Best is trial 0 with value: 1.0423970222473145.
[I 2026-09-14 18:32:30,133] Trial 5 finished with value: 1.3773517608642578 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.06398356115647941, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.001708735124113337, 'optimizer': 'adamw', 'weight_decay': 7.777156667004601e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 221}. Best is trial 0 with value: 1.0423970222473145.
[I 2026-09-14 18:32:53,915] Trial 6 finished with value: -0.8160013556480408 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.4296628995851448, 'layernorm': False, 'weight_init': 'he', 'lr': 0.03707619829134775, 'optimizer': 'adam', 'weight_decay': 4.752441989733547e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 61, 'hidden_dim_1': 254, 'hidden_dim_2': 138}. Best is trial 6 with value: -0.8160013556480408.
[I 2026-09-14 18:33:14,856] Trial 7 finished with value: 0.4998219311237335 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.3051044830687017, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.007109080535189753, 'optimizer': 'adamw', 'weight_decay': 1.0017752006475256e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 253}. Best is trial 6 with value: -0.8160013556480408.
[I 2026-09-14 18:33:36,171] Trial 8 finished with value: 0.9148713946342468 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.17608920521192922, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.0053653054560280624, 'optimizer': 'adamw', 'weight_decay': 8.601843286568572e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 249}. Best is trial 6 with value: -0.8160013556480408.
[I 2026-09-14 18:33:56,349] Trial 9 finished with value: 1.361482858657837 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.3194364310103501, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.0020774680222804586, 'optimizer': 'adamw', 'weight_decay': 5.15935976337459e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 187}. Best is trial 6 with value: -0.8160013556480408.
[I 2026-09-14 18:34:16,882] Trial 10 finished with value: -3.3723983764648438 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.4966044973451056, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04120926758391325, 'optimizer': 'adam', 'weight_decay': 3.041967277590023e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 52, 'hidden_dim_1': 252, 'hidden_dim_2': 40}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:34:38,749] Trial 11 finished with value: -3.2486658096313477 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.48573099699699007, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04932719601723778, 'optimizer': 'adam', 'weight_decay': 2.9395486095011115e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 36, 'hidden_dim_1': 256, 'hidden_dim_2': 34}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:34:40,454] Trial 12 finished with value: 1.7554763555526733 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.39487790833019437, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04775771000104113, 'optimizer': 'adam', 'weight_decay': 2.7349447052387424e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 32, 'hidden_dim_1': 254}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:35:02,842] Trial 13 finished with value: -2.6205649375915527 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.4952292616419608, 'layernorm': False, 'weight_init': 'he', 'lr': 0.02481610171867167, 'optimizer': 'adam', 'weight_decay': 2.1181282177505855e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 82, 'hidden_dim_1': 182, 'hidden_dim_2': 33}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:35:25,591] Trial 14 finished with value: -1.186000943183899 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.3865873841542, 'layernorm': False, 'weight_init': 'he', 'lr': 0.016021448352563916, 'optimizer': 'adam', 'weight_decay': 4.0169786481727564e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 33, 'hidden_dim_1': 204, 'hidden_dim_2': 56}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:35:47,463] Trial 15 finished with value: -0.9766950011253357 and parameters: {'n_hidden_layers': 2, 'activation': 'relu', 'dropout': 0.33267974768454517, 'layernorm': False, 'weight_init': 'he', 'lr': 0.01424508010081829, 'optimizer': 'adam', 'weight_decay': 1.8054267020691196e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 113, 'hidden_dim_1': 224}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:35:48,764] Trial 16 finished with value: 1.7329254150390625 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.24819922190649568, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0006252032037019612, 'optimizer': 'adam', 'weight_decay': 5.8828669542359435e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 65, 'hidden_dim_1': 144, 'hidden_dim_2': 79}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:36:10,949] Trial 17 finished with value: -0.40639832615852356 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.43121636839202787, 'layernorm': False, 'weight_init': 'he', 'lr': 0.01191220689973331, 'optimizer': 'adam', 'weight_decay': 3.555406414276877e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 92, 'hidden_dim_1': 146}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:36:32,635] Trial 18 finished with value: -1.8843706846237183 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.23967177416277582, 'layernorm': False, 'weight_init': 'he', 'lr': 0.026477487796162227, 'optimizer': 'adam', 'weight_decay': 1.749809013753768e-06, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 57, 'hidden_dim_1': 228, 'hidden_dim_2': 91}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:36:33,755] Trial 19 finished with value: 1.7034273147583008 and parameters: {'n_hidden_layers': 3, 'activation': 'relu', 'dropout': 0.49696262370436045, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0005818310264245314, 'optimizer': 'adam', 'weight_decay': 1.8338780757473694e-05, 'gradient_clip': 1.0, 'patience': 10, 'hidden_dim_0': 129, 'hidden_dim_1': 155, 'hidden_dim_2': 33}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:36:43,754] Trial 20 finished with value: 1.708382487297058 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.3667594923166367, 'layernorm': False, 'weight_init': 'he', 'lr': 0.00010422933924903909, 'optimizer': 'adam', 'weight_decay': 4.5207426673207585e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 49, 'hidden_dim_1': 39}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:36:45,136] Trial 21 finished with value: 1.738437533378601 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.49574735060712277, 'layernorm': False, 'weight_init': 'he', 'lr': 0.023932229634859338, 'optimizer': 'adam', 'weight_decay': 2.4376895151418266e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 82, 'hidden_dim_1': 182, 'hidden_dim_2': 38}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:36:46,576] Trial 22 finished with value: 1.6845729351043701 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.4501345603794734, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04230555096173997, 'optimizer': 'adam', 'weight_decay': 1.4788903309669731e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 79, 'hidden_dim_1': 228, 'hidden_dim_2': 86}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:37:07,429] Trial 23 finished with value: -2.1684935092926025 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.42875335426517697, 'layernorm': False, 'weight_init': 'he', 'lr': 0.024309962838301842, 'optimizer': 'adam', 'weight_decay': 2.7795468348884252e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 44, 'hidden_dim_1': 252, 'hidden_dim_2': 33}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:37:28,629] Trial 24 finished with value: -0.06061124429106712 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.4984890177620645, 'layernorm': False, 'weight_init': 'he', 'lr': 0.010275937589640691, 'optimizer': 'adam', 'weight_decay': 3.682212120047974e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 72, 'hidden_dim_1': 211, 'hidden_dim_2': 71}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:37:48,413] Trial 25 finished with value: -2.093360185623169 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.39881097240373836, 'layernorm': False, 'weight_init': 'he', 'lr': 0.021552310755360956, 'optimizer': 'adam', 'weight_decay': 2.3840428958732266e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 100, 'hidden_dim_1': 168}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:38:09,346] Trial 26 finished with value: -3.2524750232696533 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.46635511133040686, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04724072089530728, 'optimizer': 'adam', 'weight_decay': 5.455184352986385e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 116, 'hidden_dim_1': 128, 'hidden_dim_2': 116}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:38:27,087] Trial 27 finished with value: -3.1336100101470947 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.3622535963273134, 'layernorm': False, 'weight_init': 'he', 'lr': 0.043919364301166566, 'optimizer': 'adam', 'weight_decay': 6.535205466731087e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 152, 'hidden_dim_1': 111, 'hidden_dim_2': 118}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:38:46,926] Trial 28 finished with value: -3.167893171310425 and parameters: {'n_hidden_layers': 2, 'activation': 'relu', 'dropout': 0.46358810266645817, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04976668032156526, 'optimizer': 'adam', 'weight_decay': 5.386914331920359e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 128, 'hidden_dim_1': 122}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:39:10,848] Trial 29 finished with value: 0.4104052782058716 and parameters: {'n_hidden_layers': 3, 'activation': 'tanh', 'dropout': 0.2924801907379462, 'layernorm': True, 'weight_init': 'he', 'lr': 0.008448614720193209, 'optimizer': 'adam', 'weight_decay': 7.46386785882983e-05, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 46, 'hidden_dim_1': 234, 'hidden_dim_2': 180}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:39:18,023] Trial 30 finished with value: 1.4959766864776611 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.19250713895745547, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0038618651989060083, 'optimizer': 'adam', 'weight_decay': 4.41752999538878e-05, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 168, 'hidden_dim_1': 128}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:39:37,724] Trial 31 finished with value: -3.1935460567474365 and parameters: {'n_hidden_layers': 2, 'activation': 'relu', 'dropout': 0.45465931820125416, 'layernorm': False, 'weight_init': 'he', 'lr': 0.049280081215441036, 'optimizer': 'adam', 'weight_decay': 5.080252526212117e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 126, 'hidden_dim_1': 122}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:39:57,222] Trial 32 finished with value: -2.7051539421081543 and parameters: {'n_hidden_layers': 2, 'activation': 'relu', 'dropout': 0.4544135501675885, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0323258738563174, 'optimizer': 'adam', 'weight_decay': 5.650640398143187e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 120, 'hidden_dim_1': 134}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:40:17,807] Trial 33 finished with value: -1.3616758584976196 and parameters: {'n_hidden_layers': 3, 'activation': 'relu', 'dropout': 0.4171822970589881, 'layernorm': False, 'weight_init': 'he', 'lr': 0.01663167916064215, 'optimizer': 'adam', 'weight_decay': 6.443112396551204e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 161, 'hidden_dim_1': 105, 'hidden_dim_2': 109}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:40:37,140] Trial 34 finished with value: -1.8514673709869385 and parameters: {'n_hidden_layers': 2, 'activation': 'relu', 'dropout': 0.4659428908849432, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.018475943038286022, 'optimizer': 'adamw', 'weight_decay': 3.079688479504752e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 100, 'hidden_dim_1': 80}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:40:57,240] Trial 35 finished with value: -3.2495157718658447 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.4675498023628488, 'layernorm': False, 'weight_init': 'he', 'lr': 0.033573370047745986, 'optimizer': 'adam', 'weight_decay': 4.015537718857873e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 142, 'hidden_dim_1': 50, 'hidden_dim_2': 65}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:41:17,473] Trial 36 finished with value: -3.2509069442749023 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.3495314563093962, 'layernorm': False, 'weight_init': 'he', 'lr': 0.030487087698063246, 'optimizer': 'adam', 'weight_decay': 4.2977798900464384e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 142, 'hidden_dim_1': 39, 'hidden_dim_2': 58}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:41:38,003] Trial 37 finished with value: -3.1979928016662598 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.3506404702076679, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.030405084206848815, 'optimizer': 'adamw', 'weight_decay': 4.0162345453652364e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 140, 'hidden_dim_1': 39, 'hidden_dim_2': 63}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:41:40,235] Trial 38 finished with value: 1.6624242067337036 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.4103978619977958, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0010484690704240735, 'optimizer': 'adam', 'weight_decay': 6.09573016600568e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 182, 'hidden_dim_1': 59, 'hidden_dim_2': 99}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:42:01,555] Trial 39 finished with value: 0.8647072911262512 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.2775729785068542, 'layernorm': True, 'weight_init': 'he', 'lr': 0.0050487921518772875, 'optimizer': 'adam', 'weight_decay': 7.13502996632119e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 205, 'hidden_dim_1': 57, 'hidden_dim_2': 59}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:42:23,270] Trial 40 finished with value: 1.6268365383148193 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.10886839665246051, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.00017640395943395015, 'optimizer': 'adamw', 'weight_decay': 4.115840137606928e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 154, 'hidden_dim_1': 80, 'hidden_dim_2': 121}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:42:43,229] Trial 41 finished with value: -3.268373727798462 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.4763854522903958, 'layernorm': False, 'weight_init': 'he', 'lr': 0.03280390965529723, 'optimizer': 'adam', 'weight_decay': 3.111130521074617e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 138, 'hidden_dim_1': 55, 'hidden_dim_2': 53}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:43:03,031] Trial 42 finished with value: -3.363774299621582 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.44385576261810006, 'layernorm': False, 'weight_init': 'he', 'lr': 0.033086073286305424, 'optimizer': 'adam', 'weight_decay': 3.4112350271747996e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 144, 'hidden_dim_1': 32, 'hidden_dim_2': 56}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:43:23,082] Trial 43 finished with value: -3.2549045085906982 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.37910607901583326, 'layernorm': False, 'weight_init': 'he', 'lr': 0.034240773655981285, 'optimizer': 'adam', 'weight_decay': 3.405743465368624e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 172, 'hidden_dim_1': 32, 'hidden_dim_2': 54}. Best is trial 10 with value: -3.3723983764648438.
[I 2026-09-14 18:43:43,774] Trial 44 finished with value: -0.3179510533809662 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.4368307843286323, 'layernorm': False, 'weight_init': 'he', 'lr': 0.011170920494635524, 'optimizer': 'adam', 'weight_decay': 3.4017124194886156e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 179, 'hidden_dim_1': 67, 'hidden_dim_2': 49}. Best is trial 10 with value: -3.3723983764648438.

[I 2026-09-14 19:34:29,036] A new study created in memory with name: spy_qrnn_s_cross_alpha_0.950

Top 10 rank-based trials:
 trial  validation_nll  validation_crp  validation_crp_penalty  rank_nll  rank_crp  sum_rank
   120       -4.055643        0.993684                0.000040         7         4        11
   198       -4.018480        1.002105                0.000004        18         1        19
   182       -4.039072        1.027368                0.000749        12        18        30
    78       -4.029004        0.976842                0.000536        15        15        30
   158       -4.017978        1.018947                0.000359        19        12        31
   133       -4.028048        1.035789                0.001281        16        20        36
   129       -4.038859        0.951579                0.002345        13        24        37
   191       -4.150801        1.086316                0.007450         1        40        41
   199       -4.020902        1.052632                0.002770        17        27        44
   181       -4.045062        1.069474                0.004827        10        35        45

Selected trial: 120
Validation NLL: -4.05564260
Validation CRP: 0.99368423
Ranking saved to: spy_original_tuning_results/spy_qrnn_s_cross/spy_qrnn_s_cross_ranking_alpha_0.750.csv
Checkpoint saved to: spy_original_tuning_results/spy_qrnn_s_cross/spy_qrnn_s_cross_best_alpha_0.750.pt

========================================================================
Tuning spy_qrnn_s_cross at alpha=0.950
Trials=200 | sampler seed=2031
========================================================================

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-09-14 19:34:51,406] Trial 0 finished with value: 1.9450041055679321 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.11155263989652436, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.007027131382827591, 'optimizer': 'adam', 'weight_decay': 1.3627456384020455e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 210, 'hidden_dim_1': 162}. Best is trial 0 with value: 1.9450041055679321.
[I 2026-09-14 19:35:14,806] Trial 1 finished with value: 0.6523973345756531 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.09630890988459678, 'layernorm': False, 'weight_init': 'he', 'lr': 0.014080280114638532, 'optimizer': 'adam', 'weight_decay': 6.431370011304687e-05, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 88, 'hidden_dim_1': 196, 'hidden_dim_2': 94}. Best is trial 1 with value: 0.6523973345756531.
[I 2026-09-14 19:35:36,905] Trial 2 finished with value: 2.916311264038086 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.19785540653503986, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.0008072865606011469, 'optimizer': 'adamw', 'weight_decay': 4.4470553539966454e-05, 'gradient_clip': 0.1, 'patience': 30, 'hidden_dim_0': 116, 'hidden_dim_1': 95}. Best is trial 1 with value: 0.6523973345756531.
[I 2026-09-14 19:35:56,856] Trial 3 finished with value: 2.352315902709961 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.36511529616788896, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.004436908259778856, 'optimizer': 'adam', 'weight_decay': 4.90717928045739e-05, 'gradient_clip': 1.0, 'patience': 10, 'hidden_dim_0': 146}. Best is trial 1 with value: 0.6523973345756531.
[I 2026-09-14 19:36:16,179] Trial 4 finished with value: -2.746159553527832 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.23950679237844785, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.03210699329967103, 'optimizer': 'adam', 'weight_decay': 2.0394649167534518e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 65}. Best is trial 4 with value: -2.746159553527832.
[I 2026-09-14 19:36:37,298] Trial 5 finished with value: 3.021714925765991 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.05374574445677838, 'layernorm': True, 'weight_init': 'he', 'lr': 0.00014658238997787367, 'optimizer': 'adamw', 'weight_decay': 7.032503245742506e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 121, 'hidden_dim_1': 256}. Best is trial 4 with value: -2.746159553527832.
[I 2026-09-14 19:36:39,598] Trial 6 finished with value: 2.9123129844665527 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.25974865965779464, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.02455883672587763, 'optimizer': 'adam', 'weight_decay': 8.79658941968362e-06, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 238}. Best is trial 4 with value: -2.746159553527832.
[I 2026-09-14 19:37:02,871] Trial 7 finished with value: 2.099085807800293 and parameters: {'n_hidden_layers': 3, 'activation': 'relu', 'dropout': 0.44504428255729295, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.006224954568742743, 'optimizer': 'adamw', 'weight_decay': 7.874342312784144e-06, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 90, 'hidden_dim_1': 184, 'hidden_dim_2': 107}. Best is trial 4 with value: -2.746159553527832.
[I 2026-09-14 19:37:04,644] Trial 8 finished with value: 3.0247578620910645 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.015615367767749744, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0002198203895856578, 'optimizer': 'adamw', 'weight_decay': 3.959913336899861e-05, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 202}. Best is trial 4 with value: -2.746159553527832.
[I 2026-09-14 19:37:25,732] Trial 9 finished with value: 2.8743951320648193 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.09138608959820499, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.0011521555710837658, 'optimizer': 'adam', 'weight_decay': 7.678896872867388e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 177}. Best is trial 4 with value: -2.746159553527832.
[I 2026-09-14 19:37:44,672] Trial 10 finished with value: 0.16225548088550568 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.26861552046873005, 'layernorm': True, 'weight_init': 'he', 'lr': 0.015444395433713507, 'optimizer': 'adam', 'weight_decay': 2.7407051221339646e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 32}. Best is trial 4 with value: -2.746159553527832.
[I 2026-09-14 19:38:03,703] Trial 11 finished with value: -3.601372241973877 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.26776117075371175, 'layernorm': True, 'weight_init': 'he', 'lr': 0.04789363106851436, 'optimizer': 'adam', 'weight_decay': 2.6287751271602634e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 34}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:38:23,297] Trial 12 finished with value: -3.3155596256256104 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.3387397837146129, 'layernorm': True, 'weight_init': 'he', 'lr': 0.04102610127291207, 'optimizer': 'adam', 'weight_decay': 3.1261627349700045e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 33}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:38:43,696] Trial 13 finished with value: -3.186497688293457 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.3552781175290972, 'layernorm': True, 'weight_init': 'he', 'lr': 0.040847104879167394, 'optimizer': 'adam', 'weight_decay': 3.005273585181031e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 32, 'hidden_dim_1': 46}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:39:03,281] Trial 14 finished with value: -3.587139368057251 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.3470522107504464, 'layernorm': True, 'weight_init': 'he', 'lr': 0.048201739363082335, 'optimizer': 'adam', 'weight_decay': 9.79529558934168e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 63}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:39:25,248] Trial 15 finished with value: 2.700778007507324 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.16769644332734537, 'layernorm': True, 'weight_init': 'he', 'lr': 0.002304282475060689, 'optimizer': 'adam', 'weight_decay': 9.53526825216799e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 70, 'hidden_dim_1': 37}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:39:44,572] Trial 16 finished with value: 0.6006362438201904 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.48667843074394623, 'layernorm': True, 'weight_init': 'he', 'lr': 0.013362874899309436, 'optimizer': 'adam', 'weight_decay': 9.641147836341306e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 57}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:40:09,455] Trial 17 finished with value: -3.0361502170562744 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.41483565939953254, 'layernorm': True, 'weight_init': 'he', 'lr': 0.04980328031329601, 'optimizer': 'adam', 'weight_decay': 5.974298890937588e-07, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 103, 'hidden_dim_1': 106, 'hidden_dim_2': 248}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:40:13,951] Trial 18 finished with value: 3.035949230194092 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.3110175891999777, 'layernorm': True, 'weight_init': 'he', 'lr': 0.00042490147271271857, 'optimizer': 'adamw', 'weight_decay': 5.759941133120316e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 148}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:40:36,601] Trial 19 finished with value: 2.8951351642608643 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.4028524829196639, 'layernorm': True, 'weight_init': 'he', 'lr': 0.003132584221429833, 'optimizer': 'adam', 'weight_decay': 8.396033142645176e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 56, 'hidden_dim_1': 248}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:40:55,833] Trial 20 finished with value: -0.9142076969146729 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.30250897359356643, 'layernorm': True, 'weight_init': 'he', 'lr': 0.020409063948640917, 'optimizer': 'adam', 'weight_decay': 5.9826491802393094e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 81}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:41:14,789] Trial 21 finished with value: 1.4567731618881226 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.31117350612226274, 'layernorm': True, 'weight_init': 'he', 'lr': 0.009195023915322776, 'optimizer': 'adam', 'weight_decay': 3.566745093629008e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 44}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:41:34,311] Trial 22 finished with value: -3.5049097537994385 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.3566575315749484, 'layernorm': True, 'weight_init': 'he', 'lr': 0.04809914710246096, 'optimizer': 'adam', 'weight_decay': 2.3515196237708694e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 52}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:41:53,176] Trial 23 finished with value: -1.6066585779190063 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.20708736439105452, 'layernorm': True, 'weight_init': 'he', 'lr': 0.024359328210887675, 'optimizer': 'adam', 'weight_decay': 2.3498042129620008e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 57}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:42:12,744] Trial 24 finished with value: 1.248259425163269 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.3853344879264061, 'layernorm': True, 'weight_init': 'he', 'lr': 0.010311314847195741, 'optimizer': 'adam', 'weight_decay': 1.5788996738165954e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 126}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:42:34,510] Trial 25 finished with value: -3.370574712753296 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.4732942595397345, 'layernorm': True, 'weight_init': 'he', 'lr': 0.04937458957245742, 'optimizer': 'adam', 'weight_decay': 8.68603888179307e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 76, 'hidden_dim_1': 115}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:42:54,139] Trial 26 finished with value: -1.6668720245361328 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.43100737891430285, 'layernorm': True, 'weight_init': 'he', 'lr': 0.02516945984910243, 'optimizer': 'adamw', 'weight_decay': 3.860897937206802e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 103}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:43:13,108] Trial 27 finished with value: -0.8041907548904419 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.3362145155748162, 'layernorm': True, 'weight_init': 'he', 'lr': 0.0196689475041835, 'optimizer': 'adam', 'weight_decay': 4.6733240067215715e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 47}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:43:36,197] Trial 28 finished with value: 2.8600082397460938 and parameters: {'n_hidden_layers': 2, 'activation': 'relu', 'dropout': 0.2776297777362987, 'layernorm': True, 'weight_init': 'he', 'lr': 0.0012029537007975275, 'optimizer': 'adam', 'weight_decay': 2.4326179736910316e-07, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 171, 'hidden_dim_1': 221}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:43:56,479] Trial 29 finished with value: 2.763216257095337 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.38750790886554926, 'layernorm': False, 'weight_init': 'he', 'lr': 0.006134221671454926, 'optimizer': 'adam', 'weight_decay': 1.8423709731407714e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 100, 'hidden_dim_1': 68}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:44:17,072] Trial 30 finished with value: -2.84037446975708 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.14758398238924605, 'layernorm': True, 'weight_init': 'he', 'lr': 0.032124673606762584, 'optimizer': 'adam', 'weight_decay': 9.972578115697011e-06, 'gradient_clip': 1.0, 'patience': 10, 'hidden_dim_0': 249}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:44:40,098] Trial 31 finished with value: -3.0266194343566895 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.4989004576920057, 'layernorm': True, 'weight_init': 'he', 'lr': 0.04128786793087981, 'optimizer': 'adam', 'weight_decay': 9.984027212878335e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 76, 'hidden_dim_1': 130, 'hidden_dim_2': 32}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:45:01,219] Trial 32 finished with value: -3.2548959255218506 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.4545752656868524, 'layernorm': True, 'weight_init': 'he', 'lr': 0.04641860865374239, 'optimizer': 'adam', 'weight_decay': 8.801949374567412e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 46, 'hidden_dim_1': 135}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:45:26,583] Trial 33 finished with value: 0.2691219747066498 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.2203688690649109, 'layernorm': True, 'weight_init': 'he', 'lr': 0.014750492884830959, 'optimizer': 'adam', 'weight_decay': 9.056385836988077e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 71, 'hidden_dim_1': 86, 'hidden_dim_2': 256}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:45:47,951] Trial 34 finished with value: -2.8065810203552246 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.46849984152382274, 'layernorm': False, 'weight_init': 'he', 'lr': 0.03280557459783312, 'optimizer': 'adam', 'weight_decay': 7.870804739831142e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 87, 'hidden_dim_1': 164}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:46:09,678] Trial 35 finished with value: 1.4890141487121582 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.3679138945689768, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.00955601348148926, 'optimizer': 'adam', 'weight_decay': 5.2183554474261486e-05, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 63, 'hidden_dim_1': 122}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:46:30,109] Trial 36 finished with value: -2.8265702724456787 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.2849260223297279, 'layernorm': False, 'weight_init': 'he', 'lr': 0.03166547185958779, 'optimizer': 'adamw', 'weight_decay': 7.312384320638706e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 49}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:46:50,492] Trial 37 finished with value: -0.024912936612963676 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.24029712224575783, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.0163281645127196, 'optimizer': 'adam', 'weight_decay': 6.657222286251619e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 96}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:47:15,323] Trial 38 finished with value: 2.3660690784454346 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.333079464366361, 'layernorm': True, 'weight_init': 'he', 'lr': 0.004508417583667303, 'optimizer': 'adam', 'weight_decay': 8.39613729676235e-05, 'gradient_clip': 0.1, 'patience': 30, 'hidden_dim_0': 114}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:47:37,476] Trial 39 finished with value: -2.1435139179229736 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.41810504776345125, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.028760615805818956, 'optimizer': 'adamw', 'weight_decay': 9.144897960225768e-05, 'gradient_clip': 1.0, 'patience': 10, 'hidden_dim_0': 75, 'hidden_dim_1': 66, 'hidden_dim_2': 191}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 19:47:58,686] Trial 40 finished with value: -0.43763384222984314 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.1672374485950475, 'layernorm': True, 'weight_init': 'he', 'lr': 0.020200451347618734, 'optimizer': 'adam', 'weight_decay': 2.281043183824493e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 129, 'hidden_dim_1': 153}. Best is trial 11 with value: -3.601372241973877.
[I 2026-09-14 20:03:17,033] Trial 41 finished with value: -3.6135311126708984 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.34592753445786417, 'layernorm': True, 'weight_init': 'he', 'lr': 0.04979561138672949, 'optimizer': 'adam', 'weight_decay': 3.2176514882653946e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 36}. Best is trial 41 with value: -3.6135311126708984.
[I 2026-09-14 20:03:35,080] Trial 42 finished with value: -3.5451362133026123 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.37784923145474725, 'layernorm': True, 'weight_init': 'he', 'lr': 0.04848941613898392, 'optimizer': 'adam', 'weight_decay': 4.1313723706046055e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 42}. Best is trial 41 with value: -3.6135311126708984.
[I 2026-09-14 20:18:56,737] Trial 43 finished with value: -2.3353874683380127 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.3627979515154631, 'layernorm': True, 'weight_init': 'he', 'lr': 0.030217242702863138, 'optimizer': 'adam', 'weight_decay': 4.2590336672257825e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 41}. Best is trial 41 with value: -3.6135311126708984.
[I 2026-09-14 20:19:15,575] Trial 44 finished with value: -3.120452404022217 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.3872820114616064, 'layernorm': True, 'weight_init': 'he', 'lr': 0.03573666962807541, 'optimizer': 'adam', 'weight_decay': 2.712300939073241e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 61}. Best is trial 41 with value: -3.6135311126708984.
[I 2026-09-14 20:19:33,741] Trial 45 finished with value: -1.5777339935302734 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.2932620729435782, 'layernorm': True, 'weight_init': 'he', 'lr': 0.024146376544574095, 'optimizer': 'adam', 'weight_decay': 3.470595261562818e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 38}. Best is trial 41 with value: -3.6135311126708984.
[I 2026-09-14 20:20:44,151] Trial 46 finished with value: -3.4503490924835205 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.3281156994324287, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.038628053569861306, 'optimizer': 'adam', 'weight_decay': 5.084649092212931e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 50}. Best is trial 41 with value: -3.6135311126708984.

[I 2026-09-14 23:25:28,793] A new study created in memory with name: spy_qrnn_s_cross_alpha_0.975

Top 10 rank-based trials:
 trial  validation_nll  validation_crp  validation_crp_penalty  rank_nll  rank_crp  sum_rank
   125       -3.693112        1.010526                0.000111        12         7        19
   102       -3.670436        1.010526                0.000111        20         5        25
    71       -3.681630        0.968421                0.000997        14        13        27
   142       -3.681123        0.968421                0.000997        15        15        30
   174       -3.664881        1.010526                0.000111        22         9        31
   144       -3.680998        0.968421                0.000997        16        16        32
   124       -3.720209        0.926316                0.005429         8        29        37
   112       -3.718977        0.926316                0.005429        10        28        38
   172       -3.668507        0.968421                0.000997        21        18        39
   181       -3.655194        1.052632                0.002770        24        23        47

Selected trial: 125
Validation NLL: -3.69311166
Validation CRP: 1.01052634
Ranking saved to: spy_original_tuning_results/spy_qrnn_s_cross/spy_qrnn_s_cross_ranking_alpha_0.950.csv
Checkpoint saved to: spy_original_tuning_results/spy_qrnn_s_cross/spy_qrnn_s_cross_best_alpha_0.950.pt

========================================================================
Tuning spy_qrnn_s_cross at alpha=0.975
Trials=200 | sampler seed=2032
========================================================================

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-09-14 23:25:53,355] Trial 0 finished with value: 2.461799144744873 and parameters: {'n_hidden_layers': 3, 'activation': 'relu', 'dropout': 0.11110238679748752, 'layernorm': False, 'weight_init': 'he', 'lr': 0.007412946243424984, 'optimizer': 'adam', 'weight_decay': 2.0378044529961404e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 189, 'hidden_dim_1': 194, 'hidden_dim_2': 105}. Best is trial 0 with value: 2.461799144744873.
[I 2026-09-14 23:26:15,712] Trial 1 finished with value: 3.398545980453491 and parameters: {'n_hidden_layers': 3, 'activation': 'elu', 'dropout': 0.40125521853112683, 'layernorm': False, 'weight_init': 'he', 'lr': 0.002129411642087111, 'optimizer': 'adamw', 'weight_decay': 1.3495676574961092e-06, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 133, 'hidden_dim_1': 222, 'hidden_dim_2': 66}. Best is trial 0 with value: 2.461799144744873.
[I 2026-09-14 23:26:34,483] Trial 2 finished with value: 3.540480136871338 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.11704142131088352, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.0011220458846697664, 'optimizer': 'adam', 'weight_decay': 4.8935528018822776e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 35, 'hidden_dim_1': 50}. Best is trial 0 with value: 2.461799144744873.
[I 2026-09-14 23:26:35,678] Trial 3 finished with value: 3.6937694549560547 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.3650614379308837, 'layernorm': True, 'weight_init': 'he', 'lr': 0.0003338716904797682, 'optimizer': 'adam', 'weight_decay': 9.002622176516085e-06, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 126}. Best is trial 0 with value: 2.461799144744873.
[I 2026-09-14 23:26:58,858] Trial 4 finished with value: 3.1008973121643066 and parameters: {'n_hidden_layers': 2, 'activation': 'relu', 'dropout': 0.39482338742862805, 'layernorm': True, 'weight_init': 'he', 'lr': 0.0041019115431704285, 'optimizer': 'adamw', 'weight_decay': 4.31981077292135e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 209, 'hidden_dim_1': 233}. Best is trial 0 with value: 2.461799144744873.
[I 2026-09-14 23:27:01,325] Trial 5 finished with value: 3.6934595108032227 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.1807238475801206, 'layernorm': True, 'weight_init': 'he', 'lr': 0.0004319904375565556, 'optimizer': 'adamw', 'weight_decay': 1.976416108795136e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 223}. Best is trial 0 with value: 2.461799144744873.
[I 2026-09-14 23:27:24,205] Trial 6 finished with value: 2.794069766998291 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.37482054372948037, 'layernorm': True, 'weight_init': 'he', 'lr': 0.006007577747829675, 'optimizer': 'adam', 'weight_decay': 9.749528887020755e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 190, 'hidden_dim_1': 250}. Best is trial 0 with value: 2.461799144744873.
[I 2026-09-14 23:27:43,109] Trial 7 finished with value: 3.524550676345825 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.37338142444916017, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.001242329944602, 'optimizer': 'adam', 'weight_decay': 6.236230520721388e-05, 'gradient_clip': 0.1, 'patience': 20, 'hidden_dim_0': 64, 'hidden_dim_1': 36}. Best is trial 0 with value: 2.461799144744873.
[I 2026-09-14 23:28:01,557] Trial 8 finished with value: 2.860638380050659 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.3111369622764302, 'layernorm': True, 'weight_init': 'glorot', 'lr': 0.005687540752854898, 'optimizer': 'adamw', 'weight_decay': 9.715330066026514e-05, 'gradient_clip': 0.1, 'patience': 10, 'hidden_dim_0': 112}. Best is trial 0 with value: 2.461799144744873.
[I 2026-09-14 23:28:20,777] Trial 9 finished with value: 1.1741626262664795 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.49693736334273647, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.013789672089291764, 'optimizer': 'adamw', 'weight_decay': 7.295637665298025e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 199}. Best is trial 9 with value: 1.1741626262664795.
[I 2026-09-14 23:28:40,189] Trial 10 finished with value: -3.3724887371063232 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.4965906264222399, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.04128591953624961, 'optimizer': 'adamw', 'weight_decay': 7.303146032701568e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 251}. Best is trial 10 with value: -3.3724887371063232.
[I 2026-09-14 23:28:59,586] Trial 11 finished with value: -3.3834280967712402 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.48112409306507137, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.04249384966974779, 'optimizer': 'adamw', 'weight_decay': 7.049630292149492e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 253}. Best is trial 11 with value: -3.3834280967712402.
[I 2026-09-14 23:29:19,336] Trial 12 finished with value: -3.574113368988037 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.4941543032587499, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.04919345631912801, 'optimizer': 'adamw', 'weight_decay': 7.543895310895055e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 246}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:29:38,797] Trial 13 finished with value: -3.25449275970459 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.012108782822865038, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.038752365518383215, 'optimizer': 'adamw', 'weight_decay': 8.017562083186606e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 245}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:29:57,843] Trial 14 finished with value: 0.35753315687179565 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.45886222593673737, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.01759145368370431, 'optimizer': 'adamw', 'weight_decay': 5.605914255144187e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 162}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:30:01,622] Trial 15 finished with value: 3.6886401176452637 and parameters: {'n_hidden_layers': 2, 'activation': 'tanh', 'dropout': 0.2746516217982533, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.00011294033408777731, 'optimizer': 'adamw', 'weight_decay': 8.019994294767676e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 250, 'hidden_dim_1': 119}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:30:21,217] Trial 16 finished with value: 0.02230909839272499 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.4358755878498837, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.019226498700100552, 'optimizer': 'adamw', 'weight_decay': 3.658273805276254e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 225}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:30:43,943] Trial 17 finished with value: -3.1754581928253174 and parameters: {'n_hidden_layers': 3, 'activation': 'gelu', 'dropout': 0.3014152580821909, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.04966134169556576, 'optimizer': 'adamw', 'weight_decay': 8.899782469737035e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 161, 'hidden_dim_1': 119, 'hidden_dim_2': 238}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:31:03,593] Trial 18 finished with value: 1.3463517427444458 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.21524263033809643, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.012772652300277307, 'optimizer': 'adamw', 'weight_decay': 6.181544863172678e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 88, 'hidden_dim_1': 167}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:31:22,763] Trial 19 finished with value: -1.3184828758239746 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.4465672933972732, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.026047088788382432, 'optimizer': 'adamw', 'weight_decay': 6.924994012961352e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 167}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:31:43,493] Trial 20 finished with value: 1.8694040775299072 and parameters: {'n_hidden_layers': 2, 'activation': 'gelu', 'dropout': 0.33646921659539974, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.010412736335023228, 'optimizer': 'adamw', 'weight_decay': 8.766786488687884e-05, 'gradient_clip': 1.0, 'patience': 10, 'hidden_dim_0': 233, 'hidden_dim_1': 82}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:32:03,812] Trial 21 finished with value: -2.3484268188476562 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.49902048496710477, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.03125865559793979, 'optimizer': 'adamw', 'weight_decay': 7.138557608997216e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 255}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:32:23,389] Trial 22 finished with value: -3.5444393157958984 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.45019116042737045, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.04936554294867364, 'optimizer': 'adamw', 'weight_decay': 7.947227308343536e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 218}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:32:42,744] Trial 23 finished with value: -0.8876180648803711 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.43335029782378875, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.023551187123254845, 'optimizer': 'adamw', 'weight_decay': 8.362569042196497e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 215}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:33:02,229] Trial 24 finished with value: -1.5487004518508911 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.45464743805937285, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.026853065462407847, 'optimizer': 'adamw', 'weight_decay': 6.176278435340439e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 234}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:33:21,533] Trial 25 finished with value: 3.234982490539551 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.4150307529507161, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.003165819187908549, 'optimizer': 'adamw', 'weight_decay': 9.128925330853684e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 180}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:33:40,662] Trial 26 finished with value: -3.5441884994506836 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.4708546212443874, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.046780685086923665, 'optimizer': 'adam', 'weight_decay': 5.190545017349616e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 213}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:34:01,495] Trial 27 finished with value: 1.9876906871795654 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.3502408335143108, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.009785322350626591, 'optimizer': 'adam', 'weight_decay': 3.6698630632803593e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 202, 'hidden_dim_1': 147}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:34:20,602] Trial 28 finished with value: 0.5122101306915283 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.40871151554019414, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.018565854217755084, 'optimizer': 'adam', 'weight_decay': 5.304845899379963e-05, 'gradient_clip': 0.1, 'patience': 30, 'hidden_dim_0': 175}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:34:41,683] Trial 29 finished with value: -2.908952236175537 and parameters: {'n_hidden_layers': 3, 'activation': 'relu', 'dropout': 0.24191748982759495, 'layernorm': False, 'weight_init': 'he', 'lr': 0.047935606404328576, 'optimizer': 'adam', 'weight_decay': 4.385698131931872e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 144, 'hidden_dim_1': 82, 'hidden_dim_2': 213}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:35:00,878] Trial 30 finished with value: 2.595146417617798 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.46456431775749785, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.006848805435331032, 'optimizer': 'adam', 'weight_decay': 2.8074552236455725e-05, 'gradient_clip': 5.0, 'patience': 20, 'hidden_dim_0': 234}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:35:20,193] Trial 31 finished with value: -2.2289018630981445 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.46959083137626767, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.030879249092031005, 'optimizer': 'adam', 'weight_decay': 6.567126762047244e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 214}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:35:39,469] Trial 32 finished with value: -3.5209009647369385 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.47731896456476786, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.048502830601216254, 'optimizer': 'adam', 'weight_decay': 7.687508840594477e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 239}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:35:58,791] Trial 33 finished with value: -2.4605350494384766 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.4201255673510124, 'layernorm': False, 'weight_init': 'glorot', 'lr': 0.03259084862357174, 'optimizer': 'adam', 'weight_decay': 7.877091985574139e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 194}. Best is trial 12 with value: -3.574113368988037.
[I 2026-09-14 23:36:18,241] Trial 34 finished with value: -3.7976391315460205 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.13904029203858015, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04985646484416264, 'optimizer': 'adam', 'weight_decay': 5.6341802470250455e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 225}. Best is trial 34 with value: -3.7976391315460205.
[I 2026-09-14 23:36:40,815] Trial 35 finished with value: 0.7478933334350586 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.11068333374983079, 'layernorm': True, 'weight_init': 'he', 'lr': 0.0154778598477018, 'optimizer': 'adam', 'weight_decay': 5.65630762320688e-05, 'gradient_clip': 5.0, 'patience': 30, 'hidden_dim_0': 220, 'hidden_dim_1': 193}. Best is trial 34 with value: -3.7976391315460205.
[I 2026-09-14 23:36:59,464] Trial 36 finished with value: 3.4171993732452393 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.12860610227085095, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0020012195041447427, 'optimizer': 'adam', 'weight_decay': 4.6560404330729056e-05, 'gradient_clip': 1.0, 'patience': 10, 'hidden_dim_0': 210}. Best is trial 34 with value: -3.7976391315460205.
[I 2026-09-14 23:37:19,986] Trial 37 finished with value: -0.31275036931037903 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.041930473749671654, 'layernorm': True, 'weight_init': 'he', 'lr': 0.02126515391941972, 'optimizer': 'adam', 'weight_decay': 3.6328755651189064e-05, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 146, 'hidden_dim_1': 84}. Best is trial 34 with value: -3.7976391315460205.
[I 2026-09-14 23:37:39,062] Trial 38 finished with value: 3.6151604652404785 and parameters: {'n_hidden_layers': 1, 'activation': 'elu', 'dropout': 0.18511579277292212, 'layernorm': False, 'weight_init': 'he', 'lr': 0.0006170667699143638, 'optimizer': 'adam', 'weight_decay': 4.9162249869837035e-05, 'gradient_clip': 0.1, 'patience': 30, 'hidden_dim_0': 187}. Best is trial 34 with value: -3.7976391315460205.
[I 2026-09-14 23:37:58,201] Trial 39 finished with value: 3.6942756175994873 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.14145374504067199, 'layernorm': True, 'weight_init': 'he', 'lr': 0.00016723086399123412, 'optimizer': 'adam', 'weight_decay': 5.420910712483263e-06, 'gradient_clip': 1.0, 'patience': 20, 'hidden_dim_0': 226}. Best is trial 34 with value: -3.7976391315460205.
[I 2026-09-14 23:38:00,838] Trial 40 finished with value: 3.610896587371826 and parameters: {'n_hidden_layers': 2, 'activation': 'elu', 'dropout': 0.390397096427756, 'layernorm': False, 'weight_init': 'he', 'lr': 0.010106729100254178, 'optimizer': 'adam', 'weight_decay': 2.0708514317243978e-05, 'gradient_clip': 5.0, 'patience': 10, 'hidden_dim_0': 202, 'hidden_dim_1': 194}. Best is trial 34 with value: -3.7976391315460205.
[I 2026-09-14 23:38:20,285] Trial 41 finished with value: -3.5959906578063965 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.07941493588589002, 'layernorm': False, 'weight_init': 'he', 'lr': 0.04883661746771592, 'optimizer': 'adam', 'weight_decay': 7.66376825852697e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 238}. Best is trial 34 with value: -3.7976391315460205.
[I 2026-09-14 23:38:40,038] Trial 42 finished with value: -2.710547924041748 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.08588453968833316, 'layernorm': False, 'weight_init': 'he', 'lr': 0.03369898935704577, 'optimizer': 'adam', 'weight_decay': 8.517814854083072e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 241}. Best is trial 34 with value: -3.7976391315460205.
[I 2026-09-14 23:38:59,333] Trial 43 finished with value: -1.3646680116653442 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.04684004679552589, 'layernorm': False, 'weight_init': 'he', 'lr': 0.025829382269320505, 'optimizer': 'adam', 'weight_decay': 9.494926926202318e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 227}. Best is trial 34 with value: -3.7976391315460205.
[I 2026-09-14 23:39:17,626] Trial 44 finished with value: -2.4107472896575928 and parameters: {'n_hidden_layers': 1, 'activation': 'relu', 'dropout': 0.08382888875122751, 'layernorm': False, 'weight_init': 'he', 'lr': 0.038049599575845014, 'optimizer': 'adam', 'weight_decay': 5.655947671249078e-05, 'gradient_clip': 0.1, 'patience': 30, 'hidden_dim_0': 36}. Best is trial 34 with value: -3.7976391315460205.
[I 2026-09-14 23:39:36,973] Trial 45 finished with value: -3.391849994659424 and parameters: {'n_hidden_layers': 1, 'activation': 'gelu', 'dropout': 0.14862317998905014, 'layernorm': True, 'weight_init': 'he', 'lr': 0.040292507446685596, 'optimizer': 'adam', 'weight_decay': 6.714816196882381e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 206}. Best is trial 34 with value: -3.7976391315460205.
[I 2026-09-14 23:39:56,301] Trial 46 finished with value: -0.7961010932922363 and parameters: {'n_hidden_layers': 1, 'activation': 'tanh', 'dropout': 0.17486973518877552, 'layernorm': False, 'weight_init': 'he', 'lr': 0.023062787254178485, 'optimizer': 'adam', 'weight_decay': 7.632697288672755e-05, 'gradient_clip': 1.0, 'patience': 30, 'hidden_dim_0': 240}. Best is trial 34 with value: -3.7976391315460205.

,alpha,selected_trial,validation_nll,validation_crp,validation_crp_penalty,validation_hit_rate,beta1,beta2,beta3,psi,sigma,valid_trials,runtime_hours
0,0.025,183,-3.815248,0.926316,0.005429,0.023158,0.025660,0.032829,NaN,0.992502,0.000244,200,1.077093
1,0.050,33,-3.903121,1.010526,0.000111,0.050526,0.029957,0.031336,NaN,0.991961,0.000455,200,1.080520
2,0.250,107,-4.292467,1.018947,0.000359,0.254737,0.033940,0.044671,NaN,0.985557,0.001126,200,1.079216
3,0.500,188,-4.370070,0.985263,0.000217,0.492632,0.038728,0.047816,NaN,0.987327,0.001535,200,1.063361
4,0.750,120,-4.055643,0.993684,0.000040,0.248421,0.053411,0.065776,NaN,0.987127,0.001438,200,1.066582
5,0.950,125,-3.693112,1.010526,0.000111,0.050526,0.052008,0.061853,NaN,0.977232,0.000536,200,3.849932
6,0.975,84,-3.670074,1.010526,0.000111,0.025263,0.030323,0.071749,NaN,0.990941,0.000308,200,1.139156

Total runtime (hours): 10.356
Summary saved to: spy_original_tuning_results/spy_qrnn_s_cross/spy_qrnn_s_cross_tuning_summary.csv
Selected configurations saved to: spy_original_tuning_results/spy_qrnn_s_cross/spy_qrnn_s_cross_selected_configs.json

## Test evaluation and plotting

This section loads the selected checkpoints and does not rerun tuning.

In [ ]:
# ============================================================
# TEST EVALUATION AND PLOTTING — SPY HYBRID QRNN S CROSS-LAGGED
# Loads saved checkpoints; does not retune any model
# ============================================================

from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
import matplotlib.dates as mdates


EVALUATION_MODEL_NAME = "spy_qrnn_s_cross"
EVALUATION_FORM = "S"
EVALUATION_LAG = "cross"

EVALUATION_LEVELS = [
    0.025,
    0.050,
    0.250,
    0.500,
    0.750,
    0.950,
    0.975,
]

required_evaluation_objects = [
    "X_test",
    "y_test",
    "test_df",
    "device",
]

missing_evaluation_objects = [
    name
    for name in required_evaluation_objects
    if name not in globals()
]

if missing_evaluation_objects:
    raise RuntimeError(
        "Missing SPY preparation objects: "
        + ", ".join(missing_evaluation_objects)
        + "\nRun only the SPY data-preparation cell, then rerun this cell."
    )

EVALUATION_DIR = (
    Path("spy_original_tuning_results")
    / EVALUATION_MODEL_NAME
)

if not EVALUATION_DIR.exists():
    raise FileNotFoundError(
        f"Results directory not found: {EVALUATION_DIR.resolve()}"
    )


# ------------------------------------------------------------
# 1. Self-contained checkpoint-compatible model
# ------------------------------------------------------------

def evaluation_recurrence(
    y,
    X,
    beta1,
    beta2,
    beta3,
    fnn,
    psi,
):
    fnn_output = fnn(X).squeeze(-1)
    zero_value = y.new_zeros(())
    statistical_forecasts = [zero_value]
    hybrid_forecasts = [zero_value]

    for time_index in range(1, len(y)):
        previous_return = y[time_index - 1]

        if EVALUATION_LAG == "self":
            previous_state = statistical_forecasts[time_index - 1]
        else:
            previous_state = hybrid_forecasts[time_index - 1]

        if EVALUATION_FORM == "S":
            statistical_value = (
                beta1 * previous_state
                + beta2 * torch.abs(previous_return)
            )

        elif EVALUATION_FORM == "A":
            positive_return = torch.clamp(previous_return, min=0)
            negative_return = torch.clamp(-previous_return, min=0)
            statistical_value = (
                beta1 * previous_state
                + beta2 * positive_return
                + beta3 * negative_return
            )

        elif EVALUATION_FORM == "SI":
            absolute_return = torch.abs(previous_return)
            statistical_value = (
                beta1 * previous_state
                + beta2 * absolute_return
                + beta3 * previous_state * absolute_return
            )

        else:
            raise ValueError(f"Unknown form: {EVALUATION_FORM}")

        hybrid_value = (
            psi * statistical_value
            + (1.0 - psi) * fnn_output[time_index]
        )

        statistical_forecasts.append(statistical_value)
        hybrid_forecasts.append(hybrid_value)

    return (
        torch.stack(hybrid_forecasts),
        torch.stack(statistical_forecasts),
    )


class EvaluationHybridQRNN(nn.Module):
    def __init__(self, input_dim, config):
        super().__init__()

        self.eps = 1e-6
        self.beta1_raw = nn.Parameter(torch.tensor(1.386))
        self.beta2_raw = nn.Parameter(torch.tensor(0.3))

        if EVALUATION_FORM in {"A", "SI"}:
            self.beta3_raw = nn.Parameter(torch.tensor(0.3))
        else:
            self.beta3_raw = None

        self.psi_raw = nn.Parameter(torch.tensor(0.0))
        self.sigma_raw = nn.Parameter(torch.tensor(0.5))

        layers = []
        previous_dimension = input_dim

        for layer_index in range(config["n_hidden_layers"]):
            hidden_dimension = config[f"hidden_dim_{layer_index}"]
            layers.append(nn.Linear(previous_dimension, hidden_dimension))

            if config["layernorm"]:
                layers.append(nn.LayerNorm(hidden_dimension))

            activation = {
                "relu": nn.ReLU(),
                "elu": nn.ELU(),
                "gelu": nn.GELU(),
                "tanh": nn.Tanh(),
            }[config["activation"]]

            layers.append(activation)

            if config["dropout"] > 0:
                layers.append(nn.Dropout(config["dropout"]))

            previous_dimension = hidden_dimension

        layers.append(nn.Linear(previous_dimension, 1))
        self.fnn = nn.Sequential(*layers)

    def forward(self, y, X):
        beta1 = torch.sigmoid(self.beta1_raw)
        beta2 = F.softplus(self.beta2_raw)

        beta3 = (
            F.softplus(self.beta3_raw)
            if self.beta3_raw is not None
            else None
        )

        psi = torch.sigmoid(self.psi_raw)
        sigma = F.softplus(self.sigma_raw) + self.eps

        hybrid_forecast, statistical_forecast = evaluation_recurrence(
            y=y,
            X=X,
            beta1=beta1,
            beta2=beta2,
            beta3=beta3,
            fnn=self.fnn,
            psi=psi,
        )

        return hybrid_forecast, sigma, statistical_forecast


# ------------------------------------------------------------
# 2. Evaluation functions
# ------------------------------------------------------------

def evaluation_ald_nll(y, forecast, sigma, alpha):
    sigma = torch.clamp(
        sigma,
        min=torch.finfo(forecast.dtype).eps,
    )

    alpha_tensor = torch.as_tensor(
        alpha,
        dtype=forecast.dtype,
        device=forecast.device,
    )

    residual = y - forecast
    indicator = (residual < 0).to(forecast.dtype)
    check_loss = residual * (alpha_tensor - indicator)

    observation_nll = (
        -torch.log(alpha_tensor * (1.0 - alpha_tensor))
        + torch.log(sigma)
        + check_loss / sigma
    )

    return observation_nll


# ------------------------------------------------------------
# 3. Load each selected checkpoint and forecast the test sample
# ------------------------------------------------------------

test_forecast_columns = []
test_nll_columns = []
test_metric_records = []
loaded_test_models = {}

for alpha in EVALUATION_LEVELS:
    alpha_label = f"{alpha:.3f}"

    checkpoint_path = EVALUATION_DIR / (
        f"{EVALUATION_MODEL_NAME}_best_alpha_{alpha_label}.pt"
    )

    if not checkpoint_path.exists():
        raise FileNotFoundError(
            f"Missing checkpoint: {checkpoint_path.resolve()}"
        )

    checkpoint = torch.load(
        checkpoint_path,
        map_location=device,
        weights_only=False,
    )

    model = EvaluationHybridQRNN(
        input_dim=X_test.shape[1],
        config=checkpoint["config"],
    ).to(device)

    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()

    with torch.no_grad():
        forecast, sigma, _ = model(y_test, X_test)

        observation_nll = evaluation_ald_nll(
            y=y_test,
            forecast=forecast,
            sigma=sigma,
            alpha=alpha,
        )

    forecast_np = forecast.detach().cpu().numpy()
    nll_np = observation_nll.detach().cpu().numpy()
    y_test_np = y_test.detach().cpu().numpy()

    hit_rate = float(np.mean(y_test_np <= forecast_np))
    hre = abs(hit_rate - alpha)

    test_forecast_columns.append(forecast_np)
    test_nll_columns.append(nll_np)
    loaded_test_models[alpha] = model

    test_metric_records.append({
        "alpha": alpha,
        "NLL": float(np.mean(nll_np)),
        "Hit_Rate": hit_rate,
        "HRE": hre,
        "Sigma": float(sigma.detach().cpu().item()),
        "Selected_Trial": checkpoint["selected_trial"],
    })


test_forecast_matrix = np.column_stack(test_forecast_columns)
test_nll_matrix = np.column_stack(test_nll_columns)
test_metrics = pd.DataFrame(test_metric_records)


# ------------------------------------------------------------
# 4. Crossover diagnostics
# ------------------------------------------------------------

crossover_records = []
total_crossovers = 0
tail_crossovers = 0

for pair_index in range(len(EVALUATION_LEVELS) - 1):
    lower_level = EVALUATION_LEVELS[pair_index]
    upper_level = EVALUATION_LEVELS[pair_index + 1]

    violation_mask = (
        test_forecast_matrix[:, pair_index]
        > test_forecast_matrix[:, pair_index + 1]
    )

    violations = int(violation_mask.sum())
    violation_rate = violations / len(test_df)
    is_tail_pair = pair_index in {0, len(EVALUATION_LEVELS) - 2}

    total_crossovers += violations

    if is_tail_pair:
        tail_crossovers += violations

    crossover_records.append({
        "Lower_Alpha": lower_level,
        "Upper_Alpha": upper_level,
        "Violations": violations,
        "Violation_Rate": violation_rate,
        "Tail_Pair": is_tail_pair,
    })

crossover_table = pd.DataFrame(crossover_records)


# ------------------------------------------------------------
# 5. Save predictions, observation-level NLL and metrics
# ------------------------------------------------------------

predictions_table = pd.DataFrame({
    "Date": test_df.index,
    "Actual": y_test.detach().cpu().numpy(),
})

nll_table = pd.DataFrame({
    "Date": test_df.index,
})

for level_index, alpha in enumerate(EVALUATION_LEVELS):
    predictions_table[f"q_{alpha:.3f}"] = (
        test_forecast_matrix[:, level_index]
    )

    nll_table[f"nll_{alpha:.3f}"] = (
        test_nll_matrix[:, level_index]
    )

nll_table["average_nll_across_levels"] = (
    test_nll_matrix.mean(axis=1)
)

predictions_path = EVALUATION_DIR / (
    f"{EVALUATION_MODEL_NAME}_test_predictions.csv"
)

nll_path = EVALUATION_DIR / (
    f"{EVALUATION_MODEL_NAME}_test_nll_by_date.csv"
)

metrics_path = EVALUATION_DIR / (
    f"{EVALUATION_MODEL_NAME}_test_metrics.csv"
)

crossover_path = EVALUATION_DIR / (
    f"{EVALUATION_MODEL_NAME}_test_crossovers.csv"
)

predictions_table.to_csv(predictions_path, index=False)
nll_table.to_csv(nll_path, index=False)
test_metrics.to_csv(metrics_path, index=False)
crossover_table.to_csv(crossover_path, index=False)


# ------------------------------------------------------------
# 6. Test-period prediction plot
# Bitcoin-style presentation: black actual, red median,
# and grey 50%, 90%, and 95% interval bands
# ------------------------------------------------------------

dates = test_df.index
actual = y_test.detach().cpu().numpy()

fig, ax = plt.subplots(figsize=(11, 5.2))

ax.plot(
    dates,
    actual,
    color="black",
    linewidth=0.75,
    alpha=0.70,
    label="Actual",
)

ax.fill_between(
    dates,
    test_forecast_matrix[:, 0],
    test_forecast_matrix[:, 6],
    color="grey",
    alpha=0.18,
    label="95% interval",
)

ax.fill_between(
    dates,
    test_forecast_matrix[:, 1],
    test_forecast_matrix[:, 5],
    color="grey",
    alpha=0.30,
    label="90% interval",
)

ax.fill_between(
    dates,
    test_forecast_matrix[:, 2],
    test_forecast_matrix[:, 4],
    color="grey",
    alpha=0.48,
    label="50% interval",
)

ax.plot(
    dates,
    test_forecast_matrix[:, 3],
    color="#B2182B",
    linewidth=1.1,
    label="Predicted median",
)

ax.set(
    title=(
        f"SPY Hybrid QRNN {EVALUATION_FORM} "
        f"{EVALUATION_LAG}-lagged"
    ),
    xlabel="Date",
    ylabel="Log return",
)

ax.xaxis.set_major_formatter(
    mdates.DateFormatter("%b %Y")
)

ax.xaxis.set_major_locator(
    mdates.MonthLocator(interval=2)
)

plt.setp(
    ax.xaxis.get_majorticklabels(),
    rotation=45,
    ha="right",
)

ax.grid(
    True,
    linestyle=":",
    linewidth=0.5,
    alpha=0.45,
)

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

ax.legend(
    frameon=False,
    fontsize=8,
    ncol=2,
    loc="upper left",
)

fig.tight_layout()

plot_path = EVALUATION_DIR / (
    f"{EVALUATION_MODEL_NAME}_test_predictions.png"
)

fig.savefig(
    plot_path,
    dpi=300,
    bbox_inches="tight",
)

plt.show()


# ------------------------------------------------------------
# 7. Display concise results
# ------------------------------------------------------------

print("\n" + "=" * 72)
print(
    "TEST METRICS — SPY HYBRID QRNN "
    "S CROSS-LAGGED"
)
print("=" * 72)
print(test_metrics.to_string(index=False))

print("\nAverage NLL:", f"{test_metrics['NLL'].mean():.6f}")
print("Average HRE:", f"{test_metrics['HRE'].mean():.6f}")

print("\n" + "=" * 72)
print("CROSSOVER ANALYSIS — RAW TEST FORECASTS")
print("=" * 72)
print(crossover_table.to_string(index=False))

print("\nTotal crossover violations:", total_crossovers)
print("Tail crossover violations:", tail_crossovers)

print("\nSaved outputs:")
print("Predictions:", predictions_path)
print("Observation-level NLL:", nll_path)
print("Metrics:", metrics_path)
print("Crossovers:", crossover_path)
print("Plot:", plot_path)